import {z} from "zod";import type{CalculatorDefinition}from "../types";
type Input={value:number;fromUnit:string;toUnit:string};type Output={result:number};type Unit={code:string;factor:number};
const nist={label:"NIST Guide to the SI — conversion factors",url:"https://www.nist.gov/pml/special-publication-811/nist-guide-si-appendix-b-conversion-factors/nist-guide-si-appendix-b9",note:"Reference conversion factors for SI and accepted non-SI units."};
const bipm={label:"BIPM — SI Brochure, 9th edition",url:"https://www.bipm.org/en/publications/si-brochure",note:"Authoritative definitions for SI units and prefixes."};
function def(id:string,slug:string,title:string,units:readonly Unit[],example:Input,expected:number,base:string,sources=[nist,bipm]):CalculatorDefinition<Input,Output>{const codes=units.map(u=>u.code),map=new Map(units.map(u=>[u.code,u.factor]));const inputSchema=z.object({value:z.number().finite(),fromUnit:z.string().refine(v=>codes.includes(v),"Unsupported source unit"),toUnit:z.string().refine(v=>codes.includes(v),"Unsupported target unit")});return{id,slug,title,category:"unit-conversions",version:1,riskClass:"standard",reviewStatus:"draft",inputSchema,calculate:({value,fromUnit,toUnit})=>{if(!Number.isFinite(value)||!map.has(fromUnit)||!map.has(toUnit))throw new Error("Conversion inputs must be finite and use supported units");if(fromUnit===toUnit)return{result:value};const ratio=map.get(fromUnit)!/map.get(toUnit)!;const result=value*ratio;if(!Number.isFinite(result))throw new Error("Converted result is outside the supported finite range");return{result}},formulas:[{id:"conversion",expression:"target = source × (source "+base+" / target "+base+")",description:"Converts with a direct ratio of fixed base-unit factors, avoiding lossy output rounding and unnecessary intermediate scaling."}],sources,examples:[{label:"Reference conversion",input:example,expected:{result:expected}}],goldenTests:[{label:"Reference conversion",input:example,expected:{result:expected}}],ui:{simpleInputKeys:["value","fromUnit","toUnit"]}}}
const iec={label:"IEC 80000-13 — binary prefixes",url:"https://www.iec.ch/prefixes-binary-multiples",note:"Reference for binary prefixes used for digital information."};
export const dataStorageConverter=def("conversion.data-storage","data-storage-converter","Data Storage Converter",[{code:"B",factor:1},{code:"KB",factor:1000},{code:"MB",factor:1e6},{code:"GB",factor:1e9},{code:"TB",factor:1e12},{code:"KiB",factor:1024},{code:"MiB",factor:1048576},{code:"GiB",factor:1073741824}],{value:1,fromUnit:"GiB",toUnit:"MiB"},1024,"bytes",[iec]);
export const densityConverter=def("conversion.density","density-converter","Density Converter",[{code:"kg_m3",factor:1},{code:"g_cm3",factor:1000},{code:"kg_l",factor:1000},{code:"lb_ft3",factor:16.01846337396}],{value:1,fromUnit:"g_cm3",toUnit:"kg_m3"},1000,"kilograms per cubic metre");
export const forceConverter=def("conversion.force","force-converter","Force Converter",[{code:"n",factor:1},{code:"kn",factor:1000},{code:"dyn",factor:1e-5},{code:"lbf",factor:4.4482216152605}],{value:1,fromUnit:"kn",toUnit:"n"},1000,"newtons");
const LBF_FT_TO_N_M=1.3558179483314;
export const torqueConverter=def("conversion.torque","torque-converter","Torque Converter",[{code:"n_m",factor:1},{code:"kn_m",factor:1000},{code:"lbf_ft",factor:LBF_FT_TO_N_M},{code:"lbf_in",factor:LBF_FT_TO_N_M/12}],{value:1,fromUnit:"lbf_ft",toUnit:"n_m"},1.3558179483314,"newton metres");
export const frequencyConverter=def("conversion.frequency","frequency-converter","Frequency Converter",[{code:"hz",factor:1},{code:"khz",factor:1e3},{code:"mhz",factor:1e6},{code:"ghz",factor:1e9}],{value:2.4,fromUnit:"ghz",toUnit:"mhz"},2400,"hertz");
export const conversionBatch3Definitions=[dataStorageConverter,densityConverter,forceConverter,torqueConverter,frequencyConverter]as const;
