import { z } from "zod";
import type { CalculatorDefinition } from "../types";
type Input={value:number;fromUnit:string;toUnit:string}; type Output={result:number}; type Unit={code:string;factor:number};
const nist={label:"NIST Guide to the SI — conversion factors",url:"https://www.nist.gov/pml/special-publication-811/nist-guide-si-appendix-b-conversion-factors/nist-guide-si-appendix-b9",note:"Reference conversion factors for SI and accepted non-SI units."};
const bipm={label:"BIPM — SI Brochure, 9th edition",url:"https://www.bipm.org/en/publications/si-brochure",note:"Authoritative definitions for SI units and prefixes."};
function definition(id:string,slug:string,title:string,units:readonly Unit[],example:Input,expected:number,baseLabel:string):CalculatorDefinition<Input,Output>{
 const codes=units.map(u=>u.code),map=new Map(units.map(u=>[u.code,u.factor]));
 const inputSchema=z.object({value:z.number().finite(),fromUnit:z.string().refine(v=>codes.includes(v),"Unsupported source unit"),toUnit:z.string().refine(v=>codes.includes(v),"Unsupported target unit")});
 return{id,slug,title,category:"unit-conversions",version:1,riskClass:"standard",reviewStatus:"draft",inputSchema,calculate:({value,fromUnit,toUnit})=>{if(!Number.isFinite(value)||!map.has(fromUnit)||!map.has(toUnit))throw new Error("Conversion inputs must be finite and use supported units");if(fromUnit===toUnit)return{result:value};const ratio=map.get(fromUnit)!/map.get(toUnit)!;const result=value*ratio;if(!Number.isFinite(result))throw new Error("Converted result is outside the supported finite range");return{result}},formulas:[{id:"conversion",expression:"target = source × (source "+baseLabel+" / target "+baseLabel+")",description:"Converts with a direct ratio of fixed SI base or derived-unit factors, avoiding lossy output rounding and unnecessary intermediate scaling."}],sources:[nist,bipm],examples:[{label:"Reference conversion",input:example,expected:{result:expected}}],goldenTests:[{label:"Reference conversion",input:example,expected:{result:expected}}],ui:{simpleInputKeys:["value","fromUnit","toUnit"]}};
}
export const pressureConverter=definition("conversion.pressure","pressure-converter","Pressure Converter",[{code:"pa",factor:1},{code:"kpa",factor:1000},{code:"mpa",factor:1e6},{code:"bar",factor:1e5},{code:"atm",factor:101325},{code:"psi",factor:6894.757293168}],{value:1,fromUnit:"atm",toUnit:"kpa"},101.325,"pascals");
export const energyConverter=definition("conversion.energy","energy-converter","Energy Converter",[{code:"j",factor:1},{code:"kj",factor:1000},{code:"mj",factor:1e6},{code:"wh",factor:3600},{code:"kwh",factor:3.6e6},{code:"cal",factor:4.184},{code:"kcal",factor:4184}],{value:1,fromUnit:"kwh",toUnit:"mj"},3.6,"joules");
export const powerConverter=definition("conversion.power","power-converter","Power Converter",[{code:"w",factor:1},{code:"kw",factor:1000},{code:"mw",factor:1e6},{code:"hp_mech",factor:745.6998715822702}],{value:1,fromUnit:"kw",toUnit:"w"},1000,"watts");
export const timeConverter=definition("conversion.time","time-converter","Time Converter",[{code:"s",factor:1},{code:"ms",factor:.001},{code:"min",factor:60},{code:"h",factor:3600},{code:"day",factor:86400},{code:"week",factor:604800}],{value:2,fromUnit:"h",toUnit:"min"},120,"seconds");
export const angleConverter=definition("conversion.angle","angle-converter","Angle Converter",[{code:"rad",factor:1},{code:"deg",factor:Math.PI/180},{code:"grad",factor:Math.PI/200},{code:"turn",factor:2*Math.PI}],{value:180,fromUnit:"deg",toUnit:"rad"},Math.PI,"radians");
export const conversionBatch2Definitions=[pressureConverter,energyConverter,powerConverter,timeConverter,angleConverter] as const;
