import{describe,expect,it}from"vitest";import{conversionBatch3Definitions,dataStorageConverter,densityConverter,forceConverter,frequencyConverter,torqueConverter}from"./catalog-batch-3";
describe("conversion catalog batch 3",()=>{it("keeps the technical converter batch standard and DRAFT",()=>{expect(conversionBatch3Definitions.map(x=>x.slug)).toEqual(["data-storage-converter","density-converter","force-converter","torque-converter","frequency-converter"]);for(const d of conversionBatch3Definitions){expect(d.riskClass).toBe("standard");expect(d.reviewStatus).toBe("draft");expect(d.sources.length).toBeGreaterThan(0);expect(d.examples.length).toBeGreaterThan(0)}});
it("converts reference values deterministically",()=>{expect(dataStorageConverter.calculate({value:1,fromUnit:"GiB",toUnit:"MiB"},{}).result).toBe(1024);expect(densityConverter.calculate({value:1,fromUnit:"g_cm3",toUnit:"kg_m3"},{}).result).toBe(1000);expect(forceConverter.calculate({value:1,fromUnit:"kn",toUnit:"n"},{}).result).toBe(1000);expect(torqueConverter.calculate({value:1,fromUnit:"lbf_ft",toUnit:"n_m"},{}).result).toBe(1.3558179483314);expect(frequencyConverter.calculate({value:2.4,fromUnit:"ghz",toUnit:"mhz"},{}).result).toBe(2400)});
it("preserves exact imperial torque geometry",()=>expect(torqueConverter.calculate({value:1,fromUnit:"lbf_ft",toUnit:"lbf_in"},{}).result).toBe(12));
it("preserves finite identity values exactly",()=>{for(const d of conversionBatch3Definitions){const e=d.examples[0]!.input;expect(d.calculate({...e,value:Number.MIN_VALUE,toUnit:e.fromUnit},{}).result).toBe(Number.MIN_VALUE);expect(d.calculate({...e,value:Number.MAX_VALUE,toUnit:e.fromUnit},{}).result).toBe(Number.MAX_VALUE)}});
it("keeps representable tiny conversions nonzero",()=>{const actual=frequencyConverter.calculate({value:1e-300,fromUnit:"ghz",toUnit:"hz"},{}).result;expect(actual).toBeGreaterThan(0);expect(Math.abs(actual-1e-291)/1e-291).toBeLessThan(1e-12)});
it("avoids intermediate overflow when the final result is finite",()=>{const actual=dataStorageConverter.calculate({value:Number.MAX_VALUE,fromUnit:"B",toUnit:"TB"},{}).result;const expected=Number.MAX_VALUE/1e12;expect(Number.isFinite(actual)).toBe(true);expect(Math.abs(actual-expected)/expected).toBeLessThan(1e-12)});
it("rejects genuinely non-finite converted results",()=>expect(()=>frequencyConverter.calculate({value:Number.MAX_VALUE,fromUnit:"ghz",toUnit:"hz"},{})).toThrow("outside the supported finite range"));
it("rejects cross-family units",()=>expect(forceConverter.inputSchema.safeParse({value:1,fromUnit:"hz",toUnit:"n"}).success).toBe(false))});
