import { z } from "zod";
import type { CalculatorDefinition } from "../types";

type Out={value:number;steps:readonly string[]};
const positive=z.number().finite().positive().max(1e100);
const prefix=z.number().int().min(0).max(32);
const checked=(v:number)=>{if(!Number.isFinite(v))throw new Error("Calculated result is outside the supported finite range");return v};
const def=<I>(x:CalculatorDefinition<I,Out>)=>x;
const src={label:"CalcuMint Technology Methodology",note:"Deterministic calculation from explicitly supplied technical inputs; implementation details, protocol behavior and hardware specifications should be checked separately."};
const cidrSource={label:"RFC 4632 — Classless Inter-domain Routing (CIDR)",url:"https://www.rfc-editor.org/rfc/rfc4632",note:"CIDR uses an IPv4 prefix length from 0 through 32; a prefix describes a power-of-two-sized block from one through 2^32 addresses."};
const aspectRatioSource={label:"NIST — Aspect Ratio",url:"https://www.nist.gov/glossary-term/37036",note:"NIST defines aspect ratio as the ratio of the width to the height of a rectangle such as an image, pixel, or active video frame."};
const binaryUnitSource={label:"NIST — Binary prefixes",url:"https://physics.nist.gov/cuu/Units/binary.html",note:"IEC binary prefixes distinguish 1024-based units such as MiB and GiB from decimal SI MB and GB."};
const mk=<I>(id:string,slug:string,title:string,schema:z.ZodType<I>,calc:(x:I)=>number,expression:string,description:string,example:I,expected:number)=>def({id,slug,title,category:"technology-computing",version:1,riskClass:"standard",reviewStatus:"reviewed",inputSchema:schema,calculate:(input:I)=>{const value=checked(calc(input));return{value,steps:[title.replace(" Calculator","")+" = "+value]}},formulas:[{id:slug,expression,description}],sources:[src],examples:[{label:"Verified example",input:example,expected:{value:expected,steps:[title.replace(" Calculator","")+" = "+expected]}}],goldenTests:[{label:"Verified example",input:example,expected:{value:expected,steps:[title.replace(" Calculator","")+" = "+expected]}}]});

const ipv4=z.string().regex(/^\d{1,3}(?:\.\d{1,3}){3}$/);
const ipToInt=(ip:string)=>{const p=ip.split(".").map(Number);if(p.length!==4||p.some(n=>n<0||n>255))throw new Error("Invalid IPv4 address");return (((p[0]*256+p[1])*256+p[2])*256+p[3])>>>0};
export const ipSubnetCalculator=mk("technology.ip-subnet","ip-subnet-calculator","IP Subnet Calculator",z.object({address:ipv4,prefixLength:prefix}),x=>{const ip=ipToInt(x.address);const mask=x.prefixLength===0?0:(0xffffffff << (32-x.prefixLength))>>>0;const network=(ip&mask)>>>0;const size=2**(32-x.prefixLength);return size>0?size:1},"Network size = 2^(32 − prefix length)","IPv4 subnet size from an address and CIDR prefix; the result reports the total IPv4 address count represented by the supplied subnet.",{address:"192.168.1.10",prefixLength:24},256);
export const cidrCalculator=mk("technology.cidr","cidr-calculator","CIDR Calculator",z.object({prefixLength:prefix}),x=>2**(32-x.prefixLength),"Addresses = 2^(32 − prefix length)","IPv4 address count represented by a CIDR prefix length.",{prefixLength:24},256);
export const bandwidthCalculator=mk("technology.bandwidth","bandwidth-calculator","Bandwidth Calculator",z.object({dataMegabytes:positive,timeSeconds:positive}),x=>x.dataMegabytes*8/x.timeSeconds,"Bandwidth (Mbps) = data MB × 8 ÷ time seconds","Average transfer rate from data size and elapsed time.",{dataMegabytes:100,timeSeconds:10},80);
export const downloadTimeCalculator=mk("technology.download-time","download-time-calculator","Download Time Calculator",z.object({dataMegabytes:positive,bandwidthMbps:positive}),x=>x.dataMegabytes*8/x.bandwidthMbps,"Time (s) = data MB × 8 ÷ bandwidth Mbps","Idealized transfer time using supplied data size and bandwidth, ignoring protocol and network overhead.",{dataMegabytes:100,bandwidthMbps:80},10);
export const uploadTimeCalculator=mk("technology.upload-time","upload-time-calculator","Upload Time Calculator",z.object({dataMegabytes:positive,bandwidthMbps:positive}),x=>x.dataMegabytes*8/x.bandwidthMbps,"Time (s) = data MB × 8 ÷ bandwidth Mbps","Idealized upload time using supplied data size and bandwidth.",{dataMegabytes:100,bandwidthMbps:80},10);
export const dataTransferCalculator=mk("technology.data-transfer","data-transfer-calculator","Data Transfer Calculator",z.object({bandwidthMbps:positive,timeSeconds:positive}),x=>x.bandwidthMbps*x.timeSeconds/8,"Data (MB) = bandwidth Mbps × seconds ÷ 8","Idealized transferred data from bandwidth and duration.",{bandwidthMbps:80,timeSeconds:10},100);
export const storageConversionCalculator=mk("technology.storage-conversion","storage-conversion-calculator","Storage Conversion Calculator",z.object({value:positive,fromUnit:z.enum(["B","KiB","MiB","GiB","TiB"]),toUnit:z.enum(["B","KiB","MiB","GiB","TiB"])}),x=>{const m:{[k:string]:number}={B:1,KiB:1024,MiB:1024**2,GiB:1024**3,TiB:1024**4};return x.value*m[x.fromUnit]/m[x.toUnit]},"Converted value = input bytes ÷ target-unit bytes","Binary IEC storage-unit conversion using 1024-based multiples.",{value:1,fromUnit:"GiB",toUnit:"MiB"},1024);
export const raidCapacityCalculator=mk("technology.raid-capacity","raid-capacity-calculator","RAID Capacity Calculator",z.object({diskCount:z.number().int().min(2).max(64),diskSizeGb:positive,raidLevel:z.enum(["0","1","5","6","10"])}),x=>{const n=x.diskCount,s=x.diskSizeGb;if(x.raidLevel==="5"&&n<3)throw new Error("RAID 5 requires at least 3 disks");if(x.raidLevel==="6"&&n<4)throw new Error("RAID 6 requires at least 4 disks");if(x.raidLevel==="10"&&(n<4||n%2!==0))throw new Error("RAID 10 requires an even disk count of at least 4");switch(x.raidLevel){case"0":return n*s;case"1":return s;case"5":return (n-1)*s;case"6":return (n-2)*s;case"10":return (n/2)*s;default:throw new Error("Unsupported RAID level")}},"Usable capacity = RAID-level-specific disk count × disk size","Simplified nominal RAID usable capacity; minimum disk counts and vendor/filesystem overhead are not modeled.",{diskCount:4,diskSizeGb:1000,raidLevel:"10"},2000);
export const screenPpiCalculator=mk("technology.screen-ppi","screen-ppi-calculator","Screen PPI Calculator",z.object({widthPixels:positive,heightPixels:positive,diagonalInches:positive}),x=>Math.sqrt(x.widthPixels**2+x.heightPixels**2)/x.diagonalInches,"PPI = √(width² + height²) ÷ diagonal inches","Pixel density from pixel dimensions and physical diagonal size.",{widthPixels:1920,heightPixels:1080,diagonalInches:15.6},141.211998082756);
export const aspectRatioCalculator=mk("technology.aspect-ratio","aspect-ratio-calculator","Aspect Ratio Calculator",z.object({width:positive,height:positive}),x=>x.width/x.height,"Ratio = width ÷ height","Numeric width-to-height ratio from the supplied dimensions.",{width:1920,height:1080},1.7777777777777777);
ipSubnetCalculator.sources=[cidrSource];
cidrCalculator.sources=[cidrSource];
storageConversionCalculator.sources=[binaryUnitSource];
aspectRatioCalculator.sources=[aspectRatioSource];

export const technologyBatch1Definitions=[ipSubnetCalculator,cidrCalculator,bandwidthCalculator,downloadTimeCalculator,uploadTimeCalculator,dataTransferCalculator,storageConversionCalculator,raidCapacityCalculator,screenPpiCalculator,aspectRatioCalculator] as const;
