import { z } from "zod";
import type { CalculatorDefinition } from "../types";

type Out={value:number;steps:readonly string[]};
const positive=z.number().finite().positive().max(1e100);
const nonnegative=z.number().finite().nonnegative().max(1e100);
const checked=(v:number)=>{if(!Number.isFinite(v))throw new Error("Calculated result is outside the supported finite range");return v};
const def=<I>(x:CalculatorDefinition<I,Out>)=>x;
const src={label:"CalcuMint Technology Methodology",note:"Deterministic calculation from explicitly supplied technical inputs; verify hardware, provider pricing, protocol and implementation requirements separately."};
const imageResolutionSource={label:"NIST — Nominal Resolution",url:"https://www.nist.gov/glossary-term/28116",note:"NIST defines nominal image resolution as the number of pixels per unit distance (for example ppi or ppmm). The CalcuMint DPI calculator reports the supplied linear pixel-count-per-inch ratio and does not treat printer dots and display pixels as interchangeable concepts."};
const wattHourSource={label:"NIST Handbook 44 — watthour definition",url:"https://www.nist.gov/document/2026-nist-handbook-44-appendix-d",note:"NIST defines the watthour (Wh) as the practical unit of electric energy expended in one hour when average power is one watt; runtime here remains an idealized energy/load estimate with explicit efficiency."};
const siStorageSource={label:"NIST — SI and binary prefixes",url:"https://physics.nist.gov/cuu/Units/binary.html",note:"NIST distinguishes decimal SI MB and GB (powers of 10) from IEC binary MiB and GiB (powers of 2)."};
const base64Source={label:"RFC 4648 — Base-N Encodings",url:"https://www.rfc-editor.org/rfc/rfc4648",note:"Base64 represents 24 input bits (three octets) as four encoded characters, with padding for incomplete final groups."};
const passwordSource={label:"NIST SP 800-63B — Passwords",url:"https://pages.nist.gov/800-63-4/sp800-63b/passwords/",note:"NIST cautions that entropy for user-chosen passwords is difficult to estimate; this calculator is only the theoretical uniform-random model."};
const mk=<I>(id:string,slug:string,title:string,schema:z.ZodType<I>,calc:(x:I)=>number,expression:string,description:string,example:I,expected:number)=>def({id,slug,title,category:"technology-computing",version:1,riskClass:"standard",reviewStatus:"reviewed",inputSchema:schema,calculate:(input:I)=>{const value=checked(calc(input));return{value,steps:[title.replace(" Calculator","")+" = "+value]}},formulas:[{id:slug,expression,description}],sources:[src],examples:[{label:"Verified example",input:example,expected:{value:expected,steps:[title.replace(" Calculator","")+" = "+expected]}}],goldenTests:[{label:"Verified example",input:example,expected:{value:expected,steps:[title.replace(" Calculator","")+" = "+expected]}}]});

export const resolutionCalculator=mk("technology.resolution","resolution-calculator","Resolution Calculator",z.object({widthPixels:positive,heightPixels:positive}),x=>x.widthPixels*x.heightPixels,"Pixels = width × height","Total pixel count from horizontal and vertical pixel dimensions.",{widthPixels:1920,heightPixels:1080},2073600);
export const dpiCalculator={...mk("technology.dpi","dpi-calculator","DPI Calculator",z.object({pixels:positive,lengthInches:positive}),x=>x.pixels/x.lengthInches,"DPI = pixels ÷ length inches","Linear pixel/dot density from a supplied pixel count and physical length.",{pixels:3000,lengthInches:10},300),sources:[imageResolutionSource]};
export const batteryRuntimeCalculator={...mk("technology.battery-runtime","battery-runtime-calculator","Battery Runtime Calculator",z.object({capacityWh:positive,loadWatts:positive,efficiencyPercent:z.number().finite().positive().max(100)}),x=>x.capacityWh*(x.efficiencyPercent/100)/x.loadWatts,"Runtime (h) = capacity Wh × efficiency ÷ load W","Idealized battery runtime from energy capacity, load and explicit efficiency.",{capacityWh:1000,loadWatts:200,efficiencyPercent:90},4.5),sources:[wattHourSource]};
export const upsRuntimeCalculator={...mk("technology.ups-runtime","ups-runtime-calculator","UPS Runtime Calculator",z.object({batteryWh:positive,loadWatts:positive,efficiencyPercent:z.number().finite().positive().max(100)}),x=>x.batteryWh*(x.efficiencyPercent/100)/x.loadWatts,"Runtime (h) = battery Wh × efficiency ÷ load W","Simplified UPS runtime from battery energy, load and explicit efficiency.",{batteryWh:600,loadWatts:300,efficiencyPercent:90},1.8),sources:[wattHourSource]};
export const powerSupplyCalculator=mk("technology.power-supply","power-supply-calculator","Power Supply Calculator",z.object({systemLoadWatts:positive,headroomPercent:z.number().finite().min(0).max(500)}),x=>x.systemLoadWatts*(1+x.headroomPercent/100),"Required W = system load × (1 + headroom %)","Planning wattage from measured/estimated system load plus explicit headroom; not a PSU model recommendation.",{systemLoadWatts:500,headroomPercent:20},600);
export const websiteBandwidthCalculator={...mk("technology.website-bandwidth","website-bandwidth-calculator","Website Bandwidth Calculator",z.object({pageSizeMb:positive,monthlyPageViews:nonnegative}),x=>x.pageSizeMb*x.monthlyPageViews/1000,"Monthly GB = page MB × page views ÷ 1000","Estimated monthly transfer using decimal SI megabytes and gigabytes; caching, bots and CDN behavior are not modeled.",{pageSizeMb:2,monthlyPageViews:100000},200),version:2,sources:[siStorageSource]};
export const cloudStorageCostCalculator=mk("technology.cloud-storage-cost","cloud-storage-cost-calculator","Cloud Storage Cost Calculator",z.object({storageGb:nonnegative,pricePerGbMonth:nonnegative}),x=>x.storageGb*x.pricePerGbMonth,"Monthly cost = storage GB × price per GB-month","Provider-neutral monthly storage estimate using a user-supplied unit price.",{storageGb:1000,pricePerGbMonth:0.02},20);
export const cloudDataTransferCostCalculator=mk("technology.cloud-data-transfer-cost","cloud-data-transfer-cost-calculator","Cloud Data Transfer Cost Calculator",z.object({transferGb:nonnegative,pricePerGb:nonnegative}),x=>x.transferGb*x.pricePerGb,"Transfer cost = transfer GB × price per GB","Provider-neutral transfer estimate using a user-supplied price; tiers and free allowances are not modeled.",{transferGb:500,pricePerGb:0.09},45);
export const base64SizeCalculator={...mk("technology.base64-size","base64-size-calculator","Base64 Size Calculator",z.object({inputBytes:z.number().int().nonnegative().max(1e15)}),x=>4*Math.ceil(x.inputBytes/3),"Encoded bytes = 4 × ceil(input bytes ÷ 3)","Base64 encoded payload length without line wrapping or data-URL/MIME headers.",{inputBytes:1000},1336),sources:[base64Source]};
export const passwordEntropyCalculator={...mk("technology.password-entropy","password-entropy-calculator","Password Entropy Calculator",z.object({length:z.number().int().min(1).max(10000),characterPoolSize:z.number().int().min(2).max(1114112)}),x=>x.length*Math.log2(x.characterPoolSize),"Entropy bits = length × log2(character pool size)","Theoretical entropy for uniformly random independent characters drawn from the supplied pool; not an estimate for human-chosen passwords.",{length:16,characterPoolSize:94},16*Math.log2(94)),sources:[passwordSource]};

export const technologyBatch2Definitions=[resolutionCalculator,dpiCalculator,batteryRuntimeCalculator,upsRuntimeCalculator,powerSupplyCalculator,websiteBandwidthCalculator,cloudStorageCostCalculator,cloudDataTransferCostCalculator,base64SizeCalculator,passwordEntropyCalculator] as const;
