import{z}from"zod";import type{CalculatorDefinition}from"../types";import{compileExpression}from"./expression-engine";
const expr=z.string().trim().min(1).max(500),finite=z.number().finite().min(-1e9).max(1e9);
function sample(expression:string,min:number,max:number,count:number){if(!(min<max))throw new Error("Minimum x must be less than maximum x");const f=compileExpression(expression),points:{x:number;y:number}[]=[];for(let i=0;i<count;i++){const x=min+(max-min)*i/(count-1);try{const y=f(x);if(Number.isFinite(y))points.push({x,y})}catch{}}if(points.length<2)throw new Error("Expression does not produce enough finite points in this range");return points}
export type GraphOutput={points:{x:number;y:number}[];minimum:number;maximum:number;steps:readonly string[]};
function graphDef(slug:string,title:string,id:string):CalculatorDefinition<{expression:string;minX:number;maxX:number},GraphOutput>{return{id,slug,title,category:"advanced-math-graphing",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({expression:expr,minX:finite,maxX:finite}).refine(v=>v.minX<v.maxX,{message:"Minimum x must be less than maximum x"}),calculate:({expression,minX,maxX})=>{const points=sample(expression,minX,maxX,81),ys=points.map(p=>p.y);return{points,minimum:Math.min(...ys),maximum:Math.max(...ys),steps:[`Parse f(x) = ${expression}`,`Sample 81 evenly spaced x positions from ${minX} to ${maxX}`,`Plot ${points.length} finite points from the deterministic expression engine`]};},formulas:[{id:"function-sampling",expression:"y=f(x)",description:"Evaluates the supported expression across a finite x-domain using the same deterministic expression engine as CalcuMint calculus tools."}],sources:[{label:"CalcuMint deterministic expression engine",note:"Restricted parser and finite numeric evaluator."}],examples:[{label:"Parabola",input:{expression:"x^2",minX:-5,maxX:5},expected:{points:[],minimum:0,maximum:25,steps:[]}}],goldenTests:[{label:"Parabola",input:{expression:"x^2",minX:-5,maxX:5},expected:{points:{length:81,items:{0:{x:-5,y:25},40:{x:0,y:0},80:{x:5,y:25}}},minimum:0,maximum:25,steps:{length:3,items:{0:"Parse f(x) = x^2",1:"Sample 81 evenly spaced x positions from -5 to 5",2:"Plot 81 finite points from the deterministic expression engine"}}}}]}}
export const graphingCalculator=graphDef("graphing-calculator","Graphing Calculator","advanced-math.graphing");
export const functionPlotter2dCalculator=graphDef("function-plotter-2d","2D Function Plotter","advanced-math.function-plotter-2d");
export type SeriesOutput={sum:number;terms:number[];partialSums:number[];steps:readonly string[]};
export const seriesCalculator:CalculatorDefinition<{expression:string;start:number;end:number},SeriesOutput>={id:"advanced-math.series",slug:"series-calculator",title:"Series Calculator",category:"advanced-math-graphing",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({expression:expr,start:z.number().int().min(-10000).max(10000),end:z.number().int().min(-10000).max(10000)}).refine(v=>v.start<=v.end&&v.end-v.start<=1000,{message:"Use an ordered range of at most 1,001 terms"}),calculate:({expression,start,end})=>{const f=compileExpression(expression),terms:number[]=[],partialSums:number[]=[];let sum=0;for(let n=start;n<=end;n++){const term=f(n);sum+=term;if(!Number.isFinite(sum))throw new Error("Series is outside the supported numeric range");terms.push(term);partialSums.push(sum)}return{sum,terms,partialSums,steps:[`Interpret x as the integer series index from ${start} through ${end}`,`Evaluate ${terms.length} terms with the deterministic expression engine`,`Finite series sum = ${sum}`]};},formulas:[{id:"finite-series",expression:"Σ f(n), n=start…end",description:"Computes a finite series by evaluating the supported expression at each integer index."}],sources:[{label:"CalcuMint deterministic expression engine",note:"Finite series evaluation only; no infinite-series convergence claims."}],examples:[{label:"Sum of squares 1 to 3",input:{expression:"x^2",start:1,end:3},expected:{sum:14,terms:[1,4,9],partialSums:[1,5,14],steps:["Interpret x as the integer series index from 1 through 3","Evaluate 3 terms with the deterministic expression engine","Finite series sum = 14"]}}],goldenTests:[{label:"Sum of squares 1 to 3",input:{expression:"x^2",start:1,end:3},expected:{sum:14,terms:[1,4,9],partialSums:[1,5,14],steps:["Interpret x as the integer series index from 1 through 3","Evaluate 3 terms with the deterministic expression engine","Finite series sum = 14"]}}]};
export const advancedMathBatch10Definitions=[graphingCalculator,seriesCalculator,functionPlotter2dCalculator]as const;