import{z}from"zod";import type{CalculatorDefinition}from"../types";import{compileExpression}from"./expression-engine";import{derivativeAt,integrate,limitAt,type LimitDirection}from"./numerical-calculus";
const expr=z.string().trim().min(1).max(500);const finite=z.number().finite().min(-1e12).max(1e12);
function samples(expression:string,center:number,span:number){const f=compileExpression(expression);const points:{x:number;y:number}[]=[];for(let i=0;i<=20;i++){const x=center-span+2*span*i/20;try{points.push({x,y:f(x)})}catch{}}return points}
export type DerivativeOutput={value:number;points:{x:number;y:number}[];steps:readonly string[]};
export const derivativeCalculator:CalculatorDefinition<{expression:string;x:number},DerivativeOutput>={id:"advanced-math.derivative",slug:"derivative-calculator",title:"Derivative Calculator",category:"advanced-math-graphing",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({expression:expr,x:finite}),calculate:({expression,x})=>{const value=derivativeAt(expression,x);return{value,points:samples(expression,x,Math.max(1,Math.abs(x)*.5)),steps:[`Parse f(x) = ${expression}`,`Evaluate a refined central-difference derivative around x = ${x}`,`f′(${x}) ≈ ${value}`]};},formulas:[{id:"numerical-derivative",expression:"f′(x) ≈ Richardson-refined central differences",description:"Estimates the derivative of a supported expression at a point using symmetric finite differences and refinement."}],sources:[{label:"CalcuMint deterministic numerical-calculus engine",note:"Versioned central-difference derivative with Richardson refinement."}],examples:[{label:"Derivative of x³ at 2",input:{expression:"x^3",x:2},expected:{value:12,points:[],steps:[]}}],goldenTests:[{label:"Derivative of x³ at 2",input:{expression:"x^3",x:2},expected:{value:12,points:{length:21,items:{0:{x:1,y:1},10:{x:2,y:8},20:{x:3,y:27}}},steps:{length:3,items:{0:"Parse f(x) = x^3",1:"Evaluate a refined central-difference derivative around x = 2"}}}}]};
export type IntegralOutput={value:number;estimatedError:number;intervals:number;points:{x:number;y:number}[];steps:readonly string[]};
export const integralCalculator:CalculatorDefinition<{expression:string;lower:number;upper:number},IntegralOutput>={id:"advanced-math.integral",slug:"integral-calculator",title:"Integral Calculator",category:"advanced-math-graphing",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({expression:expr,lower:finite,upper:finite}),calculate:({expression,lower,upper})=>{const r=integrate(expression,lower,upper);return{...r,points:samples(expression,(lower+upper)/2,Math.max(Math.abs(upper-lower)/2,1e-6)),steps:[`Parse f(x) = ${expression}`,`Integrate from ${lower} to ${upper} with adaptive Simpson refinement`,`Integral ≈ ${r.value}; estimated error ≈ ${r.estimatedError}; intervals = ${r.intervals}`]};},formulas:[{id:"adaptive-simpson",expression:"∫ₐᵇ f(x)dx via independently refined composite Simpson estimates",description:"Computes a finite definite integral and reports an estimated numerical error."}],sources:[{label:"CalcuMint deterministic numerical-calculus engine",note:"Adaptive composite Simpson refinement with convergence checks."}],examples:[{label:"Integral of x² from 0 to 3",input:{expression:"x^2",lower:0,upper:3},expected:{value:9,estimatedError:0,intervals:8,points:[],steps:[]}}],goldenTests:[{label:"Integral of x² from 0 to 3",input:{expression:"x^2",lower:0,upper:3},expected:{value:9,points:{length:21,items:{0:{x:0,y:0},10:{x:1.5,y:2.25},20:{x:3,y:9}}},steps:{length:3,items:{0:"Parse f(x) = x^2",1:"Integrate from 0 to 3 with adaptive Simpson refinement"}}}}]};
export type LimitOutput={value:number;left:number|null;right:number|null;points:{x:number;y:number}[];steps:readonly string[]};
export const limitCalculator:CalculatorDefinition<{expression:string;x:number;direction:LimitDirection},LimitOutput>={id:"advanced-math.limit",slug:"limit-calculator",title:"Limit Calculator",category:"advanced-math-graphing",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({expression:expr,x:finite,direction:z.enum(["both","left","right"])}),calculate:({expression,x,direction})=>{const r=limitAt(expression,x,direction);return{...r,points:samples(expression,x,Math.max(1,Math.abs(x)*.5)),steps:[`Parse f(x) = ${expression}`,`Sample progressively closer to x = ${x} from ${direction==="both"?"both sides":direction}`,`Certified finite limit ≈ ${r.value}`]};},formulas:[{id:"finite-limit",expression:"limₓ→ₐ f(x) from converging one-sided sample sequences",description:"Estimates finite one- or two-sided limits only when the numerical samples demonstrate stable convergence."}],sources:[{label:"CalcuMint deterministic numerical-calculus engine",note:"Finite limit estimator with one-sided convergence checks."}],examples:[{label:"Removable discontinuity",input:{expression:"(x^2-1)/(x-1)",x:1,direction:"both"},expected:{value:2,left:2,right:2,points:[],steps:[]}}],goldenTests:[{label:"Removable discontinuity",input:{expression:"(x^2-1)/(x-1)",x:1,direction:"both"},expected:{value:2,left:2,right:2,points:{length:20},steps:{length:3,items:{0:"Parse f(x) = (x^2-1)/(x-1)",1:"Sample progressively closer to x = 1 from both sides"}}}}]};
export const advancedMathBatch9Definitions=[derivativeCalculator,integralCalculator,limitCalculator]as const;
