import{z}from"zod";import type{CalculatorDefinition}from"../types";
const finite=z.number().finite().min(-1e100).max(1e100),nonnegative=z.number().finite().min(0).max(1e100),positive=z.number().finite().positive().max(1e100);type Out={value:number;steps:readonly string[]};const checked=(v:number)=>{if(!Number.isFinite(v))throw new Error("Calculated result is outside the supported finite range");return v};function def<I>(x:CalculatorDefinition<I,Out>){return x}
const mk=<I>(id:string,slug:string,title:string,schema:z.ZodType<I>,calc:(x:I)=>number,expression:string,description:string,example:I,expected:number)=>{const label=title.replace(" Calculator","");return def({id,slug,title,category:"science",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:schema,calculate:(input:I)=>{const value=checked(calc(input));return{value,steps:[label+" = "+value]};},formulas:[{id,expression,description}],sources:[{label:"CalcuMint deterministic physics engine"}],examples:[{label:"Verified example",input:example,expected:{value:expected,steps:[label+" = "+expected]}}],goldenTests:[{label:"Verified example",input:example,expected:{value:expected,steps:[label+" = "+expected]}}]});};
export const ohmsLawCalculator=mk("physics.ohms-law","ohms-law-calculator","Ohm's Law Calculator",z.object({current:finite,resistance:nonnegative}),x=>x.current*x.resistance,"V=IR","Voltage from current and resistance.",{current:2,resistance:5},10);
export const electricalPowerCalculator=mk("physics.electrical-power","electrical-power-calculator","Electrical Power Calculator",z.object({voltage:finite,current:finite}),x=>x.voltage*x.current,"P=VI","Electrical power from voltage and current.",{voltage:12,current:2},24);
export const voltageCalculator=mk("physics.voltage","voltage-calculator","Voltage Calculator",z.object({current:finite,resistance:nonnegative}),x=>x.current*x.resistance,"V=IR","Voltage from current and resistance.",{current:3,resistance:4},12);
export const currentCalculator=mk("physics.current","current-calculator","Current Calculator",z.object({voltage:finite,resistance:positive}),x=>x.voltage/x.resistance,"I=V/R","Current from voltage and positive resistance.",{voltage:12,resistance:4},3);
export const resistanceCalculator=mk("physics.resistance","resistance-calculator","Resistance Calculator",z.object({voltage:finite,current:finite.refine(v=>v!==0,"Current must not be zero")}),x=>x.voltage/x.current,"R=V/I","Resistance from voltage and nonzero current.",{voltage:12,current:3},4);
export const capacitanceCalculator=mk("physics.capacitance","capacitance-calculator","Capacitance Calculator",z.object({charge:finite,voltage:finite.refine(v=>v!==0,"Voltage must not be zero")}),x=>x.charge/x.voltage,"C=Q/V","Capacitance from charge and nonzero potential difference.",{charge:10,voltage:5},2);
const K=8.9875517923e9;
export const coulombForceCalculator=mk("physics.coulomb-force","coulomb-force-calculator","Coulomb Force Calculator",z.object({charge1:finite,charge2:finite,distance:positive}),x=>K*x.charge1*x.charge2/(x.distance*x.distance),"F=kq₁q₂/r²","Signed electrostatic force using Coulomb's law.",{charge1:1e-6,charge2:1e-6,distance:1},0.0089875517923);
export const projectileMotionCalculator=mk("physics.projectile-motion","projectile-motion-calculator","Projectile Motion Calculator",z.object({speed:nonnegative,angle:z.number().finite().min(0).max(90),gravity:positive}),x=>x.speed*x.speed*Math.sin(2*x.angle*Math.PI/180)/x.gravity,"R=v²sin(2θ)/g","Ideal level-ground projectile range without air resistance.",{speed:10,angle:45,gravity:10},10);
export const freeFallCalculator=mk("physics.free-fall","free-fall-calculator","Free Fall Calculator",z.object({time:nonnegative,gravity:nonnegative}),x=>.5*x.gravity*x.time*x.time,"d=½gt²","Distance fallen from rest under constant gravity.",{time:2,gravity:9.8},19.6);
export const torqueCalculator=mk("physics.torque","torque-calculator","Torque Calculator",z.object({force:nonnegative,leverArm:nonnegative,angle:z.number().finite().min(0).max(180)}),x=>x.force*x.leverArm*Math.sin(x.angle*Math.PI/180),"τ=rFsinθ","Torque magnitude from force, lever arm and included angle.",{force:10,leverArm:2,angle:90},20);
export const angularVelocityCalculator=mk("physics.angular-velocity","angular-velocity-calculator","Angular Velocity Calculator",z.object({angle:finite,time:positive}),x=>x.angle/x.time,"ω=Δθ/Δt","Average angular velocity from angular displacement and elapsed time.",{angle:6,time:2},3);
export const physicsBatch3Definitions=[ohmsLawCalculator,electricalPowerCalculator,voltageCalculator,currentCalculator,resistanceCalculator,capacitanceCalculator,coulombForceCalculator,projectileMotionCalculator,freeFallCalculator,torqueCalculator,angularVelocityCalculator] as const;
