import { z } from "zod";
import type { CalculatorDefinition } from "../types";
type Out={value:number;steps:readonly string[]};
const checked=(v:number)=>{if(!Number.isFinite(v))throw new Error("Calculated result is outside the supported finite range");return v};
const def=<I>(x:CalculatorDefinition<I,Out>)=>x;
const positive=z.number().finite().positive().max(1e6);
const proteinSource={label:"Dietary Reference Intakes / National Academies",url:"https://www.ncbi.nlm.nih.gov/books/NBK214995/",note:"The adult protein reference is 0.8 g/kg/day. This is a general reference value, not individualized medical nutrition advice."};
const macroRangeSource={label:"National Academies — Dietary Reference Intakes",url:"https://www.ncbi.nlm.nih.gov/books/NBK214995/",note:"Adult acceptable macronutrient distribution ranges include carbohydrate 45–65% of energy and fat 20–35% of energy. The calculator converts those percentages to grams from user-supplied calories."};
const metSource={label:"2024 Adult Compendium of Physical Activities",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC10818145/",note:"MET values are standardized estimates of activity energy cost; calorie expenditure calculated from METs is an estimate and varies by activity and person."};
const paceSource={label:"CalcuMint deterministic pace methodology",note:"Pace is calculated arithmetically as elapsed time divided by distance; it is not a health or performance prediction."};
const mk=<I>(id:string,slug:string,title:string,schema:z.ZodType<I>,calc:(x:I)=>number,expression:string,description:string,example:I,expected:number,sources:any[])=>def({id,slug,title,category:"health",version:1,riskClass:"health",reviewStatus:"draft",inputSchema:schema,calculate:(input:I)=>{const value=checked(calc(input));return{value,steps:[title.replace(" Calculator","")+" = "+value]}},formulas:[{id:slug,expression,description}],sources,examples:[{label:"Reference example",input:example,expected:{value:expected,steps:[title.replace(" Calculator","")+" = "+checked(calc(example))]}}],goldenTests:[{label:"Reference example",input:example,expected:{value:expected}}],jurisdictions:[{country:"GLOBAL"}]});
export const proteinIntakeCalculator=mk("health.protein-intake","protein-intake-calculator","Protein Intake Calculator",z.object({weightKg:positive}),x=>0.8*x.weightKg,"Reference protein intake = 0.8 × body weight(kg)","General adult protein reference based on body weight; not individualized for pregnancy, disease, athletes, or therapeutic diets.",{weightKg:70},56,[proteinSource]);
export const carbohydrateIntakeCalculator=mk("health.carbohydrate-intake","carbohydrate-intake-calculator","Carbohydrate Intake Calculator",z.object({dailyCalories:positive}),x=>dailyCaloriesToCarbMidpoint(x.dailyCalories),"Carbohydrate reference midpoint = calories × 55% ÷ 4","Converts the midpoint of the adult 45–65% carbohydrate energy range to grams; the full reference range is 45–65%.",{dailyCalories:2000},275,[macroRangeSource]);
function dailyCaloriesToCarbMidpoint(calories:number){return calories*0.55/4}
export const fatIntakeCalculator=mk("health.fat-intake","fat-intake-calculator","Fat Intake Calculator",z.object({dailyCalories:positive}),x=>x.dailyCalories*0.275/9,"Fat reference midpoint = calories × 27.5% ÷ 9","Converts the midpoint of the adult 20–35% fat energy range to grams; the full reference range is 20–35%.",{dailyCalories:2000},61.111111111111114,[macroRangeSource]);
export const caloriesBurnedCalculator=mk("health.calories-burned","calories-burned-calculator","Calories Burned Calculator",z.object({weightKg:positive,met:z.number().finite().min(1).max(20),minutes:z.number().finite().positive().max(1440)}),x=>x.met*3.5*x.weightKg/200*x.minutes,"Calories ≈ MET × 3.5 × weight(kg) ÷ 200 × minutes","MET-based estimate of gross energy expenditure; activity MET selection is itself an estimate.",{weightKg:70,met:3.5,minutes:30},128.625,[metSource]);
export const paceCalculator=mk("health.pace","pace-calculator","Pace Calculator",z.object({distanceKm:positive,timeMinutes:z.number().finite().positive().max(100000)}),x=>x.timeMinutes/x.distanceKm,"Pace = elapsed minutes ÷ distance(km)","Arithmetic running/walking pace in minutes per kilometre.",{distanceKm:5,timeMinutes:30},6,[paceSource]);
export const oneRepMaxCalculator=mk("health.one-rep-max","one-rep-max-calculator","One Rep Max Calculator",z.object({weightKg:positive,repetitions:z.number().int().min(1).max(30)}),x=>x.weightKg*(1+x.repetitions/30),"Epley estimate = weight × (1 + repetitions ÷ 30)","Estimated one-repetition maximum from a submaximal set; it is an exercise estimate, not a medical measure.",{weightKg:60,repetitions:10},80,[{label:"Epley one-repetition maximum estimate",note:"Epley's linear estimate is used as a training-planning approximation; actual 1RM can differ by lifter and exercise."}]);
export const healthBatch2Definitions=[proteinIntakeCalculator,carbohydrateIntakeCalculator,fatIntakeCalculator,caloriesBurnedCalculator,paceCalculator,oneRepMaxCalculator] as const;
