import type { Metadata } from "next";
import Link from "next/link";
import { CalculatorSearch } from "@/components/calculator-search";
import { calculatorRegistry } from "@/calculators/registry";
import { buildPublicCalculatorSearchIndex } from "@/calculators/search-index";
import { listPublicCalculators, listPublicCategories } from "@/calculators/public-content";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = { title: { absolute: "CalcuMint — Calculate Anything" }, description: siteConfig.description, alternates: { canonical: "/" }, openGraph: { type: "website", title: "CalcuMint — Calculate Anything", description: siteConfig.description, url: "/" } };

export default function HomePage() {
  const calculators = listPublicCalculators();
  const categories = listPublicCategories().map((category) => ({ ...category, count: calculators.filter((item) => item.category === category.slug).length })).filter((category) => category.count > 0);
  const searchItems = buildPublicCalculatorSearchIndex();
  const featured = calculators.slice(0, 8);
  const websiteJsonLd = { "@context": "https://schema.org", "@type": "WebSite", "@id": `${siteConfig.url}/#website`, url: `${siteConfig.url}/`, name: "CalcuMint" };
  const organizationJsonLd = { "@context": "https://schema.org", "@type": "Organization", "@id": `${siteConfig.url}/#organization`, name: "CalcuMint", url: `${siteConfig.url}/`, logo: `${siteConfig.url}/brand/calcumint-logo.png`, email: "support@calcumint.com" };

  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }} />
    <section className="hero container"><div className="hero-main"><span className="eyebrow">One place for every calculation</span><h1>Calculate anything.<br />Understand every result.</h1><p className="hero-copy">Reliable calculators for money, health, math, conversions, business and everyday decisions — with clear formulas and useful explanations.</p><div className="hero-actions"><Link className="button primary" href="/calculators">Explore calculators</Link><Link className="button secondary" href="/login?mode=signup">Create free account</Link></div><CalculatorSearch items={searchItems} /><div className="trust-strip"><span>✓ {calculators.length}+ published tools</span><span>✓ Clear formulas</span><span>✓ No account required</span><span>✓ Mobile friendly</span></div></div></section>
    <section className="container section category-first-section"><div className="section-heading"><div><span className="eyebrow">Start with a topic</span><h2>Browse calculator categories</h2><p className="muted-copy">Choose a category first, then narrow down to the calculation you need.</p></div><Link className="text-link" href="/calculators">All calculators →</Link></div><div className="category-grid">{categories.map((category) => <Link className="card category-link category-discovery-card" href={`/calculators/${category.slug}`} key={category.slug}><span className="category-count">{category.count} calculator{category.count === 1 ? "" : "s"}</span><h3>{category.name}</h3><p>{category.description}</p><span className="text-link">Browse category →</span></Link>)}</div></section>
    <section className="container section"><div className="section-heading"><div><span className="eyebrow">Featured tools</span><h2>Featured calculators</h2><p className="muted-copy">Quick access to a curated selection of useful calculators.</p></div><Link className="text-link" href="/calculators#all-calculators">View A–Z →</Link></div><div className="popular-grid">{featured.map((item) => { const definition = calculatorRegistry.getBySlug(item.slug); if (!definition) return null; return <Link className="popular-card" href={`/calculators/${item.category}/${item.slug}`} key={item.slug}><span className="category-count">{categories.find((category) => category.slug === item.category)?.name ?? item.category}</span><strong>{definition.title}</strong><span>{item.shortDescription}</span></Link>; })}</div></section>
    <section className="container section value-section"><div className="section-heading"><div><span className="eyebrow">Three ways to find an answer</span><h2>Browse, search, or describe what you need.</h2></div></div><div className="value-grid"><article className="card"><span className="feature-icon">▦</span><h3>Browse categories</h3><p>Explore calculators by topic when you want to see what is available.</p><Link className="text-link" href="/calculators">Browse calculators →</Link></article><article className="card"><span className="feature-icon">AI</span><h3>Find it with AI</h3><p>Describe what you need to calculate and CalcuMint helps you find the right tool.</p><Link className="text-link" href="/ai">Try AI Finder →</Link></article><article className="card"><span className="feature-icon">↗</span><h3>Save your work</h3><p>Create a free account for saved calculations, favorites and synced regional preferences.</p><Link className="text-link" href="/login?mode=signup">Sign up free →</Link></article></div></section>
    <section className="container section split"><div className="card accent-card"><span className="eyebrow">For professionals</span><h2>Go further with Pro.</h2><p>Remove ads, keep unlimited history and unlock advanced analysis and professional exports.</p><Link className="button primary" href="/pricing">Explore Pro</Link></div><div className="card business-card"><span className="eyebrow">Business Tools</span><h2>Build calculators for your audience.</h2><p>Create, brand, embed and automate calculators with team workspaces and business integrations.</p><Link className="button secondary" href="/business-platform">Explore Business Tools</Link></div></section>
    <section className="container section final-cta"><span className="eyebrow">Ready when you are</span><h2>Start calculating for free.</h2><p>No registration required for public calculators.</p><div className="hero-actions"><Link className="button primary" href="/calculators">Browse calculators</Link><Link className="button secondary" href="/pricing">Compare plans</Link></div></section>
  </>;
}