"use client";
import { useMemo,useState } from "react";
import { runCalculator } from "@/calculators/engine";
import { percentageCalculator } from "@/calculators/core/percentage";
import { unitConversionCalculator } from "@/calculators/core/unit-conversion";
import { getUnitFamily,supportedUnits } from "@/calculators/units";
import { getLaunchSpec,launchDefinition } from "@/calculators/launch-portfolio";
import { CalculatorAccountActions } from "@/components/calculator-account-actions";
import { AiResultExplanation } from "@/components/ai-result-explanation";
const unitLabels:Record<string,string>={m:"Metres (m)",km:"Kilometres (km)",cm:"Centimetres (cm)",mm:"Millimetres (mm)",in:"Inches (in)",ft:"Feet (ft)",yd:"Yards (yd)",mi:"Miles (mi)",kg:"Kilograms (kg)",g:"Grams (g)",lb:"Pounds (lb)",oz:"Ounces (oz)",l:"Litres (L)",ml:"Millilitres (mL)",m3:"Cubic metres (m³)",gal_us:"US gallons",qt_us:"US quarts",c:"Celsius (°C)",f:"Fahrenheit (°F)",k:"Kelvin (K)"};
function NumberField({label,value,onChange,min}:{label:string;value:string;onChange:(v:string)=>void;min?:number}){return <label className="field"><span>{label}</span><input inputMode="decimal" type="number" min={min} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function PercentageTool(){const[percentage,setPercentage]=useState("20");const[value,setValue]=useState("250");const input=useMemo(()=>({percentage:Number(percentage),value:Number(value)}),[percentage,value]);const result=useMemo(()=>{try{return runCalculator(percentageCalculator,input).output.result}catch{return null}},[input]);return <div className="calculator-ui"><div className="field-grid"><NumberField label="Percentage (%)" value={percentage} onChange={setPercentage}/><NumberField label="Value" value={value} onChange={setValue}/></div><Result value={result}/><CalculatorAccountActions calculatorSlug={percentageCalculator.slug} calculatorVersion={1} input={input} output={result===null?null:{result}}/>{result!==null&&<AiResultExplanation calculatorName="Percentage of a Value" formula="result = percentage / 100 × value" assumptions={["Inputs are finite decimal numbers."]} values={input} result={{result}}/>}</div>}
function UnitTool(){const[value,setValue]=useState("1");const[fromUnit,setFromUnit]=useState("mi");const[toUnit,setToUnit]=useState("km");const family=getUnitFamily(fromUnit);const targets=supportedUnits.filter(u=>getUnitFamily(u)===family);const input=useMemo(()=>({value:Number(value),fromUnit,toUnit}),[value,fromUnit,toUnit]);const result=useMemo(()=>{try{return runCalculator(unitConversionCalculator,input).output.result}catch{return null}},[input]);function source(u:string){setFromUnit(u);const fam=getUnitFamily(u);if(getUnitFamily(toUnit)!==fam)setToUnit(supportedUnits.find(x=>getUnitFamily(x)===fam&&x!==u)??u)}return <div className="calculator-ui"><div className="field-grid three"><NumberField label="Value" value={value} onChange={setValue}/><label className="field"><span>From</span><select value={fromUnit} onChange={e=>source(e.target.value)}>{supportedUnits.map(u=><option value={u} key={u}>{unitLabels[u]??u}</option>)}</select></label><label className="field"><span>To</span><select value={toUnit} onChange={e=>setToUnit(e.target.value)}>{targets.map(u=><option value={u} key={u}>{unitLabels[u]??u}</option>)}</select></label></div><Result value={result}/><CalculatorAccountActions calculatorSlug={unitConversionCalculator.slug} calculatorVersion={1} input={input} output={result===null?null:{result}}/></div>}
function Result({value}:{value:number|null}){return <div className="result-box" aria-live="polite"><span>Result</span><strong>{value===null||!Number.isFinite(value)?"Enter valid inputs":value.toLocaleString(undefined,{maximumFractionDigits:12})}</strong></div>}
function LaunchTool({slug}:{slug:string}){const spec=getLaunchSpec(slug)!;const definition=useMemo(()=>launchDefinition(spec),[spec]);const[values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(spec.fields.map(x=>[x.key,String(x.defaultValue)])));const input=useMemo(()=>Object.fromEntries(spec.fields.map(x=>[x.key,Number(values[x.key])])),[spec,values]);const result=useMemo(()=>{try{const n=runCalculator(definition,input).output.result;return Number.isFinite(n)?n:null}catch{return null}},[definition,input]);return <div className="calculator-ui"><div className="field-grid">{spec.fields.map(field=><NumberField key={field.key} label={field.label} min={field.min} value={values[field.key]??""} onChange={value=>setValues(current=>({...current,[field.key]:value}))}/>)}</div><Result value={result}/><CalculatorAccountActions calculatorSlug={slug} calculatorVersion={1} input={input} output={result===null?null:{result}}/>{result!==null&&<AiResultExplanation calculatorName={spec.title} formula={spec.formula} assumptions={["The displayed deterministic formula is the source of the numeric result."]} values={input} result={{result}}/>}</div>}
export function CalculatorInteractive({slug}:{slug:string}){if(slug===percentageCalculator.slug)return <PercentageTool/>;if(slug===unitConversionCalculator.slug)return <UnitTool/>;if(getLaunchSpec(slug))return <LaunchTool slug={slug}/>;return <p className="muted">This calculator does not yet have a public interface.</p>}
