"use client";
import { useMemo,useState } from "react";
import { runCalculator } from "@/calculators/engine";
import { percentageCalculator } from "@/calculators/core/percentage";
import { unitConversionCalculator } from "@/calculators/core/unit-conversion";
import { getUnitFamily,supportedUnits } from "@/calculators/units";
import { getLaunchSpec,launchDefinition } from "@/calculators/launch-portfolio";
import { CalculatorAccountActions } from "@/components/calculator-account-actions";
import { AiResultExplanation } from "@/components/ai-result-explanation";
import { simpleInterestCalculator } from "@/calculators/finance/simple-interest";
import { savingsGoalCalculator } from "@/calculators/finance/savings-goal";
import { emergencyFundCalculator } from "@/calculators/finance/emergency-fund";
import { roiCalculator } from "@/calculators/finance/roi";
import { inflationCalculator } from "@/calculators/finance/inflation";
import { rateConversionCalculator } from "@/calculators/finance/rate-conversion";
const unitLabels:Record<string,string>={m:"Metres (m)",km:"Kilometres (km)",cm:"Centimetres (cm)",mm:"Millimetres (mm)",in:"Inches (in)",ft:"Feet (ft)",yd:"Yards (yd)",mi:"Miles (mi)",kg:"Kilograms (kg)",g:"Grams (g)",lb:"Pounds (lb)",oz:"Ounces (oz)",l:"Litres (L)",ml:"Millilitres (mL)",m3:"Cubic metres (m³)",gal_us:"US gallons",qt_us:"US quarts",c:"Celsius (°C)",f:"Fahrenheit (°F)",k:"Kelvin (K)"};
function NumberField({label,value,onChange,min}:{label:string;value:string;onChange:(v:string)=>void;min?:number}){return <label className="field"><span>{label}</span><input inputMode="decimal" type="number" min={min} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function PercentageTool(){const[percentage,setPercentage]=useState("20");const[value,setValue]=useState("250");const input=useMemo(()=>({percentage:Number(percentage),value:Number(value)}),[percentage,value]);const result=useMemo(()=>{try{return runCalculator(percentageCalculator,input).output.result}catch{return null}},[input]);return <div className="calculator-ui"><div className="field-grid"><NumberField label="Percentage (%)" value={percentage} onChange={setPercentage}/><NumberField label="Value" value={value} onChange={setValue}/></div><Result value={result}/><CalculatorAccountActions calculatorSlug={percentageCalculator.slug} calculatorVersion={1} input={input} output={result===null?null:{result}}/>{result!==null&&<AiResultExplanation calculatorName="Percentage of a Value" formula="result = percentage / 100 × value" assumptions={["Inputs are finite decimal numbers."]} values={input} result={{result}}/>}</div>}
function UnitTool(){const[value,setValue]=useState("1");const[fromUnit,setFromUnit]=useState("mi");const[toUnit,setToUnit]=useState("km");const family=getUnitFamily(fromUnit);const targets=supportedUnits.filter(u=>getUnitFamily(u)===family);const input=useMemo(()=>({value:Number(value),fromUnit,toUnit}),[value,fromUnit,toUnit]);const result=useMemo(()=>{try{return runCalculator(unitConversionCalculator,input).output.result}catch{return null}},[input]);function source(u:string){setFromUnit(u);const fam=getUnitFamily(u);if(getUnitFamily(toUnit)!==fam)setToUnit(supportedUnits.find(x=>getUnitFamily(x)===fam&&x!==u)??u)}return <div className="calculator-ui"><div className="field-grid three"><NumberField label="Value" value={value} onChange={setValue}/><label className="field"><span>From</span><select value={fromUnit} onChange={e=>source(e.target.value)}>{supportedUnits.map(u=><option value={u} key={u}>{unitLabels[u]??u}</option>)}</select></label><label className="field"><span>To</span><select value={toUnit} onChange={e=>setToUnit(e.target.value)}>{targets.map(u=><option value={u} key={u}>{unitLabels[u]??u}</option>)}</select></label></div><Result value={result}/><CalculatorAccountActions calculatorSlug={unitConversionCalculator.slug} calculatorVersion={1} input={input} output={result===null?null:{result}}/></div>}
function SimpleInterestTool(){const[principal,setPrincipal]=useState("10000");const[rate,setRate]=useState("5");const[years,setYears]=useState("2");const input=useMemo(()=>({principal:Number(principal),annualRatePercent:Number(rate),years:Number(years)}),[principal,rate,years]);const output=useMemo(()=>{try{return runCalculator(simpleInterestCalculator,input).output}catch{return null}},[input]);return <div className="calculator-ui"><div className="field-grid three"><NumberField label="Principal" min={0} value={principal} onChange={setPrincipal}/><NumberField label="Annual rate (%)" min={0} value={rate} onChange={setRate}/><NumberField label="Time (years)" min={0} value={years} onChange={setYears}/></div><div className="result-box" aria-live="polite"><span>Interest</span><strong>{output?output.interest.toLocaleString():"Enter valid inputs"}</strong>{output&&<small>Total amount: {output.totalAmount.toLocaleString()}</small>}</div><CalculatorAccountActions calculatorSlug={simpleInterestCalculator.slug} calculatorVersion={1} input={input} output={output}/>{output&&<AiResultExplanation calculatorName={simpleInterestCalculator.title} formula="interest = principal × annual rate × time" assumptions={["Simple interest does not compound."]} values={input} result={output}/>}</div>}

function SavingsGoalTool(){const[current,setCurrent]=useState("5000");const[target,setTarget]=useState("25000");const[rate,setRate]=useState("6");const[months,setMonths]=useState("36");const[advanced,setAdvanced]=useState(false);const[monthly,setMonthly]=useState("");const input=useMemo(()=>({currentSavings:Number(current),targetAmount:Number(target),annualReturnPercent:Number(rate),months:Number(months),...(advanced&&monthly!==""?{monthlyContribution:Number(monthly)}:{})}),[current,target,rate,months,advanced,monthly]);const output=useMemo(()=>{try{return runCalculator(savingsGoalCalculator,input).output}catch{return null}},[input]);return <div className="calculator-ui"><button type="button" className="button secondary" onClick={()=>setAdvanced(v=>!v)}>{advanced?"Simple mode":"Advanced mode"}</button><div className="field-grid"><NumberField label="Current savings" min={0} value={current} onChange={setCurrent}/><NumberField label="Target amount" min={0} value={target} onChange={setTarget}/><NumberField label="Annual modeled return (%)" value={rate} onChange={setRate}/><NumberField label="Months" min={1} value={months} onChange={setMonths}/>{advanced&&<NumberField label="Monthly contribution (optional)" min={0} value={monthly} onChange={setMonthly}/>}</div><div className="result-box" aria-live="polite"><span>Required monthly contribution</span><strong>{output?output.requiredMonthlyContribution.toLocaleString():"Enter valid inputs"}</strong>{output&&<small>Projected value: {output.futureValue.toLocaleString()} · Gap: {output.gapToTarget.toLocaleString()}</small>}</div><CalculatorAccountActions calculatorSlug={savingsGoalCalculator.slug} calculatorVersion={1} input={input} output={output}/></div>}
function EmergencyFundTool(){const[expenses,setExpenses]=useState("3000");const[targetMonths,setTargetMonths]=useState("6");const[current,setCurrent]=useState("5000");const[advanced,setAdvanced]=useState(false);const[build,setBuild]=useState("12");const input=useMemo(()=>({monthlyEssentialExpenses:Number(expenses),targetMonths:Number(targetMonths),currentEmergencySavings:Number(current),...(advanced?{buildMonths:Number(build)}:{})}),[expenses,targetMonths,current,advanced,build]);const output=useMemo(()=>{try{return runCalculator(emergencyFundCalculator,input).output}catch{return null}},[input]);return <div className="calculator-ui"><button type="button" className="button secondary" onClick={()=>setAdvanced(v=>!v)}>{advanced?"Simple mode":"Advanced mode"}</button><div className="field-grid"><NumberField label="Monthly essential expenses" min={0} value={expenses} onChange={setExpenses}/><NumberField label="Target reserve (months)" min={1} value={targetMonths} onChange={setTargetMonths}/><NumberField label="Current emergency savings" min={0} value={current} onChange={setCurrent}/>{advanced&&<NumberField label="Build period (months)" min={1} value={build} onChange={setBuild}/>}</div><div className="result-box" aria-live="polite"><span>Target fund</span><strong>{output?output.targetFund.toLocaleString():"Enter valid inputs"}</strong>{output&&<small>Funding gap: {output.fundingGap.toLocaleString()}{output.requiredMonthlySavings!==null?` · Monthly build: ${output.requiredMonthlySavings.toLocaleString()}`:""}</small>}</div><CalculatorAccountActions calculatorSlug={emergencyFundCalculator.slug} calculatorVersion={1} input={input} output={output}/></div>}
function RoiTool(){const[initial,setInitial]=useState("10000");const[finalValue,setFinalValue]=useState("12500");const[months,setMonths]=useState("24");const[advanced,setAdvanced]=useState(false);const[costs,setCosts]=useState("0");const[income,setIncome]=useState("0");const input=useMemo(()=>({initialInvestment:Number(initial),finalValue:Number(finalValue),holdingMonths:Number(months),additionalCosts:advanced?Number(costs):0,incomeReceived:advanced?Number(income):0}),[initial,finalValue,months,advanced,costs,income]);const output=useMemo(()=>{try{return runCalculator(roiCalculator,input).output}catch{return null}},[input]);return <div className="calculator-ui"><button type="button" className="button secondary" onClick={()=>setAdvanced(v=>!v)}>{advanced?"Simple mode":"Advanced mode"}</button><div className="field-grid"><NumberField label="Initial investment" min={0} value={initial} onChange={setInitial}/><NumberField label="Final value" min={0} value={finalValue} onChange={setFinalValue}/><NumberField label="Holding period (months)" min={1} value={months} onChange={setMonths}/>{advanced&&<><NumberField label="Additional costs" min={0} value={costs} onChange={setCosts}/><NumberField label="Income received" min={0} value={income} onChange={setIncome}/></>}</div><div className="result-box" aria-live="polite"><span>ROI</span><strong>{output?`${output.roiPercent.toLocaleString()}%`:"Enter valid inputs"}</strong>{output&&<small>Net gain: {output.netGain.toLocaleString()} · Annualized: {output.annualizedReturnPercent===null?"N/A":`${output.annualizedReturnPercent.toLocaleString()}%`}</small>}</div><CalculatorAccountActions calculatorSlug={roiCalculator.slug} calculatorVersion={1} input={input} output={output}/></div>}
function InflationTool(){const[amount,setAmount]=useState("10000");const[rate,setRate]=useState("5");const[years,setYears]=useState("10");const input=useMemo(()=>({amount:Number(amount),annualInflationPercent:Number(rate),years:Number(years)}),[amount,rate,years]);const output=useMemo(()=>{try{return runCalculator(inflationCalculator,input).output}catch{return null}},[input]);return <div className="calculator-ui"><div className="field-grid three"><NumberField label="Amount" min={0} value={amount} onChange={setAmount}/><NumberField label="Annual inflation (%)" value={rate} onChange={setRate}/><NumberField label="Years" min={0} value={years} onChange={setYears}/></div><div className="result-box" aria-live="polite"><span>Future equivalent cost</span><strong>{output?output.futureEquivalentCost.toLocaleString():"Enter valid inputs"}</strong>{output&&<small>Future purchasing power of unchanged amount: {output.futurePurchasingPower.toLocaleString()}</small>}</div><CalculatorAccountActions calculatorSlug={inflationCalculator.slug} calculatorVersion={1} input={input} output={output}/></div>}

function RateConversionTool(){const[mode,setMode]=useState<"nominal-to-effective"|"effective-to-nominal">("nominal-to-effective");const[rate,setRate]=useState("12");const[frequency,setFrequency]=useState("12");const input=useMemo(()=>mode==="nominal-to-effective"?{mode,annualNominalPercent:Number(rate),compoundsPerYear:Number(frequency)}:{mode,annualEffectivePercent:Number(rate),compoundsPerYear:Number(frequency)},[mode,rate,frequency]);const output=useMemo(()=>{try{return runCalculator(rateConversionCalculator,input).output}catch{return null}},[input]);return <div className="calculator-ui"><div className="field-grid three"><label className="field"><span>Conversion</span><select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="nominal-to-effective">Nominal → Effective</option><option value="effective-to-nominal">Effective → Nominal</option></select></label><NumberField label={mode==="nominal-to-effective"?"Nominal annual rate (%)":"Effective annual rate (%)"} value={rate} onChange={setRate}/><NumberField label="Compounds per year" min={1} value={frequency} onChange={setFrequency}/></div><div className="result-box" aria-live="polite"><span>{mode==="nominal-to-effective"?"Effective annual rate":"Nominal annual rate"}</span><strong>{output?`${(mode==="nominal-to-effective"?output.annualEffectivePercent:output.annualNominalPercent).toLocaleString()}%`:"Enter valid inputs"}</strong></div><CalculatorAccountActions calculatorSlug={rateConversionCalculator.slug} calculatorVersion={1} input={input} output={output}/></div>}
function Result({value}:{value:number|null}){return <div className="result-box" aria-live="polite"><span>Result</span><strong>{value===null||!Number.isFinite(value)?"Enter valid inputs":value.toLocaleString(undefined,{maximumFractionDigits:12})}</strong></div>}
function LaunchTool({slug}:{slug:string}){const spec=getLaunchSpec(slug)!;const definition=useMemo(()=>launchDefinition(spec),[spec]);const[values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(spec.fields.map(x=>[x.key,String(x.defaultValue)])));const input=useMemo(()=>Object.fromEntries(spec.fields.map(x=>[x.key,Number(values[x.key])])),[spec,values]);const result=useMemo(()=>{try{const n=runCalculator(definition,input).output.result;return Number.isFinite(n)?n:null}catch{return null}},[definition,input]);return <div className="calculator-ui"><div className="field-grid">{spec.fields.map(field=><NumberField key={field.key} label={field.label} min={field.min} value={values[field.key]??""} onChange={value=>setValues(current=>({...current,[field.key]:value}))}/>)}</div><Result value={result}/><CalculatorAccountActions calculatorSlug={slug} calculatorVersion={1} input={input} output={result===null?null:{result}}/>{result!==null&&<AiResultExplanation calculatorName={spec.title} formula={spec.formula} assumptions={["The displayed deterministic formula is the source of the numeric result."]} values={input} result={{result}}/>}</div>}
export function CalculatorInteractive({slug}:{slug:string}){if(slug===percentageCalculator.slug)return <PercentageTool/>;if(slug===unitConversionCalculator.slug)return <UnitTool/>;if(slug===simpleInterestCalculator.slug)return <SimpleInterestTool/>;if(slug===savingsGoalCalculator.slug)return <SavingsGoalTool/>;if(slug===emergencyFundCalculator.slug)return <EmergencyFundTool/>;if(slug===roiCalculator.slug)return <RoiTool/>;if(slug===inflationCalculator.slug)return <InflationTool/>;if(slug===rateConversionCalculator.slug)return <RateConversionTool/>;if(getLaunchSpec(slug))return <LaunchTool slug={slug}/>;return <p className="muted">This calculator does not yet have a public interface.</p>}
