import{calculatorRegistry}from"./registry";import{runCalculator}from"./engine";
export type LaunchCertificationIssue={slug:string;reason:string};
const ABS=1e-10,REL=1e-9;
export function goldenMismatch(actual:unknown,expected:unknown,path="output"):string|null{
 if(typeof expected==="number"){if(typeof actual!=="number"||!Number.isFinite(actual)||!Number.isFinite(expected))return `${path}: expected finite number`;const tolerance=Math.max(ABS,REL*Math.max(1,Math.abs(expected)));return Math.abs(actual-expected)<=tolerance?null:`${path}: expected ${expected}, received ${actual}`;}
 if(Array.isArray(expected)){if(!Array.isArray(actual))return `${path}: expected array`;if(actual.length!==expected.length)return `${path}: expected array length ${expected.length}, received ${actual.length}`;for(let i=0;i<expected.length;i++){const issue=goldenMismatch(actual[i],expected[i],`${path}[${i}]`);if(issue)return issue}return null}
 if(expected&&typeof expected==="object"){if(!actual||typeof actual!=="object"||Array.isArray(actual))return `${path}: expected object`;const a=actual as Record<string,unknown>,e=expected as Record<string,unknown>;const ak=Object.keys(a).sort(),ek=Object.keys(e).sort();if(ak.join("\0")!==ek.join("\0"))return `${path}: object keys differ`;for(const key of ek){const issue=goldenMismatch(a[key],e[key],`${path}.${key}`);if(issue)return issue}return null}
 return Object.is(actual,expected)?null:`${path}: expected ${String(expected)}, received ${String(actual)}`;
}
export function auditLaunchCertification(now=new Date()):LaunchCertificationIssue[]{const issues:LaunchCertificationIssue[]=[];for(const d of calculatorRegistry.list()){if(d.reviewStatus!=="certified")continue;if(!d.version||d.version<1)issues.push({slug:d.slug,reason:"invalid version"});const fixtures=d.goldenTests?.length?d.goldenTests:d.examples;if(!fixtures?.length)issues.push({slug:d.slug,reason:"missing certification fixtures"});else for(const fixture of fixtures){try{const actual=runCalculator(d,fixture.input).output;const mismatch=goldenMismatch(actual,fixture.expected);if(mismatch)issues.push({slug:d.slug,reason:`golden fixture "${fixture.label}" mismatch: ${mismatch}`})}catch(error){issues.push({slug:d.slug,reason:`golden fixture "${fixture.label}" failed: ${error instanceof Error?error.message:String(error)}`})}}if(!d.formulas?.length)issues.push({slug:d.slug,reason:"missing formulas"});if(d.lastVerifiedAt){const t=Date.parse(d.lastVerifiedAt);if(!Number.isFinite(t)||t>now.getTime())issues.push({slug:d.slug,reason:"invalid verification date"});}if(["financial","tax","health"].includes(String(d.riskClass))){const sources=d.officialSources?.length?d.officialSources:d.sources;if(!sources?.length)issues.push({slug:d.slug,reason:"regulated calculator missing official sources"});}}return issues;}
export function assertLaunchCertification(now=new Date()):void{const issues=auditLaunchCertification(now);if(issues.length)throw new Error(`Launch certification failed: ${issues.map(i=>`${i.slug}: ${i.reason}`).join("; ")}`);}
