import { calculatorRegistry } from "./registry";
import { launchSpecs } from "./launch-portfolio";
export type PublicCalculatorContent={slug:string;category:string;shortDescription:string;intro:string;formulaExplanation:string;assumptions:readonly string[];faq:readonly {question:string;answer:string}[];relatedSlugs:readonly string[];keywords:readonly string[];};
const foundational:readonly PublicCalculatorContent[]=[
{slug:"percentage-of-value-calculator",category:"math",shortDescription:"Find a percentage of any number instantly.",intro:"Use this calculator to answer questions such as 20% of 250. Enter the percentage and base value for an immediate deterministic result.",formulaExplanation:"Convert the percentage to decimal form by dividing by 100, then multiply by the base value.",assumptions:["Inputs are finite decimal numbers.","No tax, currency or domain-specific rules are applied."],faq:[{question:"How do I calculate a percentage of a number?",answer:"Divide the percentage by 100 and multiply the decimal by the number."},{question:"Can I use decimals?",answer:"Yes. Both inputs can include decimals."}],relatedSlugs:["percentage-change-calculator","ratio-calculator"],keywords:["percentage calculator","percent of number","percentage of value"]},
{slug:"unit-conversion-calculator",category:"unit-conversions",shortDescription:"Convert common length, mass, volume and temperature units.",intro:"Convert between supported units using a verified conversion engine covering common metric and US customary measurements.",formulaExplanation:"Linear units convert through a common base unit. Temperature conversions use Kelvin as the intermediate scale.",assumptions:["Only units in the same measurement family can be converted.","US liquid gallon and quart definitions are used."],faq:[{question:"Can I convert temperature?",answer:"Yes. Celsius, Fahrenheit and Kelvin are supported."},{question:"Can I convert unrelated units?",answer:"No. Conversion remains within each measurement family."}],relatedSlugs:["degrees-to-radians-calculator","radians-to-degrees-calculator"],keywords:["unit converter","measurement converter","length conversion","temperature conversion"]}
];
const byCategory=new Map<string,string[]>(); for(const spec of launchSpecs){const list=byCategory.get(spec.category)??[];list.push(spec.slug);byCategory.set(spec.category,list);}
const generated:PublicCalculatorContent[]=launchSpecs.map((spec,index)=>{
 const peers=byCategory.get(spec.category)??[]; const position=peers.indexOf(spec.slug); const related=[peers[(position+1)%peers.length],peers[(position+2)%peers.length]].filter((x):x is string=>Boolean(x&&x!==spec.slug));
 return {slug:spec.slug,category:spec.category,shortDescription:spec.description,intro:`${spec.description} CalcuMint evaluates the stated formula deterministically from validated numeric inputs and shows the result immediately.`,formulaExplanation:spec.explanation,assumptions:["Use compatible units wherever the formula combines physical quantities.","The calculator applies only the formula and assumptions stated on this page; it does not infer missing domain-specific rules.","Results use finite-number arithmetic and should be interpreted with appropriate real-world measurement precision."],faq:[{question:`How does the ${spec.title} work?`,answer:spec.explanation},{question:"What units should I use?",answer:"Use mutually compatible units. The result follows the unit relationship implied by the displayed formula."},{question:"Is this result deterministic?",answer:"Yes. The same validated inputs and calculator version produce the same mathematical result; AI is not used for the calculation."}],relatedSlugs:related,keywords:[...spec.keywords,`${spec.category} calculator`,`online calculator ${index+1}`]};
});
const content:readonly PublicCalculatorContent[]=[...foundational,...generated];
export const categoryContent={math:{name:"Math Calculators",description:"Percentages, powers, logarithms, trigonometry, ratios and practical mathematics."},geometry:{name:"Geometry Calculators",description:"Areas, perimeters, volumes and common plane and solid geometry formulas."},statistics:{name:"Statistics Calculators",description:"Means, rates, proportions, variability and descriptive statistics."},science:{name:"Science Calculators",description:"Deterministic physics, chemistry, electrical and measurement formulas."},everyday:{name:"Everyday Calculators",description:"Practical calculators for costs, recipes, utilities, projects and daily decisions."},"unit-conversions":{name:"Unit Conversion Calculators",description:"Convert common units of length, mass, volume and temperature."}} as const;
export function getPublicCalculatorContent(slug:string){const definition=calculatorRegistry.getBySlug(slug);if(!definition||definition.reviewStatus!=="certified")return undefined;return content.find(item=>item.slug===slug);}
export function listPublicCalculators():readonly PublicCalculatorContent[]{return content.filter(item=>calculatorRegistry.getBySlug(item.slug)?.reviewStatus==="certified");}
export function listPublicCategories(){return Object.entries(categoryContent).map(([slug,value])=>({slug,...value}));}
