import { calculatorRegistry } from "./registry";
import { launchSpecs } from "./launch-portfolio";
import { financePublicContent } from "./finance/public-content";
export type PublicCalculatorContent={slug:string;category:string;shortDescription:string;intro:string;formulaExplanation:string;assumptions:readonly string[];faq:readonly {question:string;answer:string}[];relatedSlugs:readonly string[];keywords:readonly string[];};
const foundational:readonly PublicCalculatorContent[]=[
{slug:"percentage-of-value-calculator",category:"math",shortDescription:"Find a percentage of any number instantly.",intro:"Use this calculator to answer questions such as 20% of 250. Enter the percentage and base value for an immediate deterministic result.",formulaExplanation:"Convert the percentage to decimal form by dividing by 100, then multiply by the base value.",assumptions:["Inputs are finite decimal numbers.","No tax, currency or domain-specific rules are applied."],faq:[{question:"How do I calculate a percentage of a number?",answer:"Divide the percentage by 100 and multiply the decimal by the number."},{question:"Can I use decimals?",answer:"Yes. Both inputs can include decimals."}],relatedSlugs:["percentage-change-calculator","ratio-calculator"],keywords:["percentage calculator","percent of number","percentage of value"]},
{slug:"unit-conversion-calculator",category:"unit-conversions",shortDescription:"Convert miles to kilometres and common length, mass, volume and temperature units.",intro:"Convert between supported units using a verified conversion engine covering common metric and US customary measurements.",formulaExplanation:"Linear units convert through a common base unit. Temperature conversions use Kelvin as the intermediate scale.",assumptions:["Only units in the same measurement family can be converted.","US liquid gallon and quart definitions are used."],faq:[{question:"Can I convert temperature?",answer:"Yes. Celsius, Fahrenheit and Kelvin are supported."},{question:"Can I convert unrelated units?",answer:"No. Conversion remains within each measurement family."}],relatedSlugs:["degrees-to-radians-calculator","radians-to-degrees-calculator"],keywords:["unit converter","measurement converter","length conversion","temperature conversion","convert miles to kilometers","miles kilometers"]}
];
const byCategory=new Map<string,string[]>();for(const spec of launchSpecs){const list=byCategory.get(spec.category)??[];list.push(spec.slug);byCategory.set(spec.category,list)}
const generated:PublicCalculatorContent[]=launchSpecs.map((spec,index)=>{const peers=byCategory.get(spec.category)??[];const position=peers.indexOf(spec.slug);const related=[peers[(position+1)%peers.length],peers[(position+2)%peers.length]].filter((x):x is string=>Boolean(x&&x!==spec.slug));return{slug:spec.slug,category:spec.category,shortDescription:spec.description,intro:`${spec.description} CalcuMint evaluates the stated formula deterministically from validated numeric inputs and shows the result immediately.`,formulaExplanation:spec.explanation,assumptions:["Use compatible units wherever the formula combines physical quantities.","The calculator applies only the formula and assumptions stated on this page; it does not infer missing domain-specific rules.","Results use finite-number arithmetic and should be interpreted with appropriate real-world measurement precision."],faq:[{question:`How does the ${spec.title} work?`,answer:spec.explanation},{question:"What units should I use?",answer:"Use mutually compatible units. The result follows the unit relationship implied by the displayed formula."},{question:"Is this result deterministic?",answer:"Yes. The same validated inputs and calculator version produce the same mathematical result; AI is not used for the calculation."}],relatedSlugs:related,keywords:[...spec.keywords,`${spec.category} calculator`,`online calculator ${index+1}`]}});
const uniqueFinancePublicContent=financePublicContent.filter((item,index,items)=>items.findIndex((candidate)=>candidate.slug===item.slug)===index);
const content:readonly PublicCalculatorContent[]=[...foundational,...generated,...uniqueFinancePublicContent];
export const categoryContent={
math:{name:"Math Calculators",description:"Percentages, powers, logarithms, trigonometry, ratios and practical mathematics.",intro:"Solve common numerical problems with focused tools for percentages, ratios, powers, logarithms and trigonometry. Each published calculator exposes its formula and assumptions so you can understand how the result is produced.",guidance:"Choose the calculator that matches the operation you need. Keep units consistent where a formula uses measured quantities, and review the formula section on the calculator page when precision or interpretation matters."},
geometry:{name:"Geometry Calculators",description:"Areas, perimeters, volumes and common plane and solid geometry formulas.",intro:"Calculate dimensions and properties of common two-dimensional and three-dimensional shapes using explicit geometry formulas. The collection covers practical area, perimeter, surface-area and volume calculations.",guidance:"Use measurements from the same unit system unless the calculator explicitly supports conversion. Geometry results inherit squared or cubed units for area and volume, so confirm the input units before using a result in a real-world project."},
statistics:{name:"Statistics Calculators",description:"Means, rates, proportions, variability and descriptive statistics.",intro:"Explore descriptive statistics, rates and proportions with deterministic calculators designed to make the underlying operation visible. These tools are intended for transparent numerical analysis rather than hidden model-based estimation.",guidance:"Check that your inputs represent the population, sample or quantities required by the displayed formula. Statistical outputs can be mathematically correct while still being inappropriate for a dataset, so interpret each result in its original context."},
science:{name:"Science Calculators",description:"Deterministic physics, chemistry, electrical and measurement formulas.",intro:"Apply common scientific formulas across physics, chemistry, electricity and measurement. CalcuMint validates numeric inputs and evaluates the stated equation without using AI to generate the calculated value.",guidance:"Scientific formulas depend heavily on compatible units and stated assumptions. Review the formula, variables and methodology on the individual calculator page and use measurement precision appropriate to your source data."},
everyday:{name:"Everyday Calculators",description:"Practical calculators for costs, recipes, utilities, projects and daily decisions.",intro:"Handle recurring practical calculations for household, project and day-to-day decisions with simple tools that show what is being calculated. These calculators focus on repeatable arithmetic rather than opaque recommendations.",guidance:"Treat estimates as planning aids when real-world prices, usage or measurements can vary. Check the calculator assumptions and substitute values that reflect your own situation before relying on the output."},
"unit-conversions":{name:"Unit Conversion Calculators",description:"Convert common units of length, mass, volume and temperature.",intro:"Convert supported measurements between common metric and US customary units with explicit conversion logic. Conversion tools stay within compatible measurement families and use documented conversion relationships.",guidance:"Select units from the same measurement family and confirm whether a unit has regional definitions. For example, liquid-volume standards can differ; the individual calculator methodology states the convention used."},
"loans-mortgages":{name:"Loans & Mortgages",description:"Loan payments, affordability, payoff, prepayment, refinancing and debt comparison models.",intro:"Model borrowing and debt decisions with deterministic payment, amortization, affordability and payoff calculations. Generic mathematical models are kept separate from lender-, product- and jurisdiction-specific rules.",guidance:"Treat rates, fees and affordability thresholds as entered scenarios unless a calculator explicitly identifies a certified lender or jurisdiction rule pack. A mathematical affordability result is not a lending approval or eligibility decision."},
"finance-investment":{name:"Finance & Investment Calculators",description:"Loans, deposits, recurring investments, investment growth and withdrawal planning.",intro:"Model common financial cash flows with deterministic formulas, reverse solvers and explicit assumptions. CalcuMint separates generic mathematical models from country-, tax- and institution-specific rules so regulated logic can be versioned and certified independently.",guidance:"Treat assumed rates as scenarios rather than forecasts. Review timing, compounding and exclusions on each calculator. Country-specific taxes, product rules, fees or legal requirements apply only when the calculator explicitly identifies a certified jurisdiction rule pack."}
} as const;
export function getPublicCalculatorContent(slug:string){const definition=calculatorRegistry.getBySlug(slug);if(!definition||definition.reviewStatus!=="certified")return undefined;return content.find(item=>item.slug===slug)}
export function listPublicCalculators():readonly PublicCalculatorContent[]{return content.filter(item=>calculatorRegistry.getBySlug(item.slug)?.reviewStatus==="certified")}
export function listPublicCategories(){return Object.entries(categoryContent).map(([slug,value])=>({slug,...value}))}
