import type { CalculatorDefinition } from "./types";
import { percentageCalculator } from "./core/percentage";
import { unitConversionCalculator } from "./core/unit-conversion";
import { compoundInterestCalculator } from "./finance/compound-interest";
import { loanPaymentCalculator } from "./finance/loan-payment";
import { loanAnalysisCalculator } from "./finance/loan-analysis";
import { loanRefinanceCalculator } from "./finance/loan-refinance";
import { loanPrepaymentCalculator } from "./finance/loan-prepayment";
import { loanComparisonCalculator } from "./finance/loan-comparison";
import { loanAffordabilityCalculator } from "./finance/loan-affordability";
import { debtPayoffCalculator } from "./finance/debt-payoff";
import { creditCardPayoffCalculator } from "./finance/credit-card-payoff";
import { termDepositCalculator } from "./finance/term-deposit";
import { recurringDepositCalculator } from "./finance/recurring-deposit";
import { sipCalculator } from "./finance/sip";
import { stepUpSipCalculator } from "./finance/step-up-sip";
import { investmentMathCalculator } from "./finance/investment-math";
import { swpCalculator } from "./finance/swp";
import { rateConversionCalculator } from "./finance/rate-conversion";
import { savingsGoalCalculator } from "./finance/savings-goal";
import { roiCalculator } from "./finance/roi";
import { netWorthCalculator } from "./finance/net-worth";
import { inflationCalculator } from "./finance/inflation";
import { simpleInterestCalculator } from "./finance/simple-interest";
import { emergencyFundCalculator } from "./finance/emergency-fund";
import { launchDefinitions } from "./launch-portfolio";
import { bmiCalculator } from "./health/bmi";
import { breakEvenCalculator } from "./business/break-even";
import { advancedMathDefinitions } from "./advanced-math/catalog-batch-5";
type RegistryCalculator=CalculatorDefinition<unknown,unknown>;
function eraseCalculatorTypes<TInput,TOutput>(definition:CalculatorDefinition<TInput,TOutput>):RegistryCalculator{return definition as unknown as RegistryCalculator;}
const definitions:readonly RegistryCalculator[]=[eraseCalculatorTypes(percentageCalculator),eraseCalculatorTypes(unitConversionCalculator),eraseCalculatorTypes(compoundInterestCalculator),eraseCalculatorTypes(loanPaymentCalculator),eraseCalculatorTypes(loanAnalysisCalculator),eraseCalculatorTypes(loanRefinanceCalculator),eraseCalculatorTypes(loanPrepaymentCalculator),eraseCalculatorTypes(loanComparisonCalculator),eraseCalculatorTypes(loanAffordabilityCalculator),eraseCalculatorTypes(debtPayoffCalculator),eraseCalculatorTypes(creditCardPayoffCalculator),eraseCalculatorTypes(termDepositCalculator),eraseCalculatorTypes(recurringDepositCalculator),eraseCalculatorTypes(sipCalculator),eraseCalculatorTypes(stepUpSipCalculator),eraseCalculatorTypes(investmentMathCalculator),eraseCalculatorTypes(swpCalculator),eraseCalculatorTypes(rateConversionCalculator),eraseCalculatorTypes(savingsGoalCalculator),eraseCalculatorTypes(roiCalculator),eraseCalculatorTypes(netWorthCalculator),eraseCalculatorTypes(inflationCalculator),eraseCalculatorTypes(simpleInterestCalculator),eraseCalculatorTypes(emergencyFundCalculator),eraseCalculatorTypes(bmiCalculator),eraseCalculatorTypes(breakEvenCalculator),...launchDefinitions.map(eraseCalculatorTypes),...advancedMathDefinitions.map(definition=>eraseCalculatorTypes(definition))];
const bySlug=new Map<string,RegistryCalculator>();const byId=new Map<string,RegistryCalculator>();for(const definition of definitions){if(bySlug.has(definition.slug))throw new Error(`Duplicate calculator slug: ${definition.slug}`);if(byId.has(definition.id))throw new Error(`Duplicate calculator id: ${definition.id}`);bySlug.set(definition.slug,definition);byId.set(definition.id,definition);}export const calculatorRegistry={list:():readonly RegistryCalculator[]=>definitions,getBySlug:(slug:string)=>bySlug.get(slug),getById:(id:string)=>byId.get(id)} as const;
