import type { CalculatorDefinition } from "./types";
import { percentageCalculator } from "./core/percentage";
import { unitConversionCalculator } from "./core/unit-conversion";
import { compoundInterestCalculator } from "./finance/compound-interest";
import { loanPaymentCalculator } from "./finance/loan-payment";
import { loanAnalysisCalculator } from "./finance/loan-analysis";
import { loanRefinanceCalculator } from "./finance/loan-refinance";
import { loanPrepaymentCalculator } from "./finance/loan-prepayment";
import { loanComparisonCalculator } from "./finance/loan-comparison";
import { loanAffordabilityCalculator } from "./finance/loan-affordability";
import { debtPayoffCalculator } from "./finance/debt-payoff";
import { creditCardPayoffCalculator } from "./finance/credit-card-payoff";
import { termDepositCalculator } from "./finance/term-deposit";
import { recurringDepositCalculator } from "./finance/recurring-deposit";
import { sipCalculator } from "./finance/sip";
import { stepUpSipCalculator } from "./finance/step-up-sip";
import { investmentMathCalculator } from "./finance/investment-math";
import { swpCalculator } from "./finance/swp";
import { rateConversionCalculator } from "./finance/rate-conversion";
import { savingsGoalCalculator } from "./finance/savings-goal";
import { roiCalculator } from "./finance/roi";
import { netWorthCalculator } from "./finance/net-worth";
import { inflationCalculator } from "./finance/inflation";
import { simpleInterestCalculator } from "./finance/simple-interest";
import { emergencyFundCalculator } from "./finance/emergency-fund";
import { launchDefinitions } from "./launch-portfolio";
import { bmiCalculator } from "./health/bmi";
import { healthBatch1Definitions } from "./health/catalog-batch-1";
import { healthBatch2Definitions } from "./health/catalog-batch-2";
import { breakEvenCalculator } from "./business/break-even";
import { businessGrowthBatch1Definitions } from "./business/catalog-batch-1";
import { advancedMathDefinitions } from "./advanced-math/catalog-batch-5";
import { advancedMathBatch6Definitions } from "./advanced-math/catalog-batch-6";
import { advancedMathBatch7Definitions } from "./advanced-math/catalog-batch-7";
import { advancedMathBatch8Definitions } from "./advanced-math/catalog-batch-8";
import { advancedMathBatch9Definitions } from "./advanced-math/catalog-batch-9";
import { advancedMathBatch10Definitions } from "./advanced-math/catalog-batch-10";
import { advancedMathFinalDefinitions } from "./advanced-math/catalog-final";
import { geometryCompletionDefinitions } from "./geometry/catalog-completion";
import { statisticsBatch1Definitions } from "./statistics/catalog-batch-1";
import { statisticsBatch2Definitions } from "./statistics/catalog-batch-2";
import { statisticsBatch3Definitions } from "./statistics/catalog-batch-3";
import { statisticsBatch4Definitions } from "./statistics/catalog-batch-4";
import { physicsBatch1Definitions } from "./physics/catalog-batch-1";
import { physicsBatch2Definitions } from "./physics/catalog-batch-2";
import { physicsBatch3Definitions } from "./physics/catalog-batch-3";
import { chemistryBatch1Definitions } from "./chemistry/catalog-batch-1";
import { engineeringConstructionBatch1Definitions } from "./engineering-construction/catalog-batch-1";
import { engineeringConstructionBatch2Definitions } from "./engineering-construction/catalog-batch-2";
import { engineeringConstructionBatch3Definitions } from "./engineering-construction/catalog-batch-3";
import { technologyBatch1Definitions } from "./technology-computing/catalog-batch-1";
import { technologyBatch2Definitions } from "./technology-computing/catalog-batch-2";
type RegistryCalculator=CalculatorDefinition<unknown,unknown>;
function eraseCalculatorTypes<TInput,TOutput>(definition:CalculatorDefinition<TInput,TOutput>):RegistryCalculator{return definition as unknown as RegistryCalculator;}
const definitions:readonly RegistryCalculator[]=[eraseCalculatorTypes(percentageCalculator),eraseCalculatorTypes(unitConversionCalculator),eraseCalculatorTypes(compoundInterestCalculator),eraseCalculatorTypes(loanPaymentCalculator),eraseCalculatorTypes(loanAnalysisCalculator),eraseCalculatorTypes(loanRefinanceCalculator),eraseCalculatorTypes(loanPrepaymentCalculator),eraseCalculatorTypes(loanComparisonCalculator),eraseCalculatorTypes(loanAffordabilityCalculator),eraseCalculatorTypes(debtPayoffCalculator),eraseCalculatorTypes(creditCardPayoffCalculator),eraseCalculatorTypes(termDepositCalculator),eraseCalculatorTypes(recurringDepositCalculator),eraseCalculatorTypes(sipCalculator),eraseCalculatorTypes(stepUpSipCalculator),eraseCalculatorTypes(investmentMathCalculator),eraseCalculatorTypes(swpCalculator),eraseCalculatorTypes(rateConversionCalculator),eraseCalculatorTypes(savingsGoalCalculator),eraseCalculatorTypes(roiCalculator),eraseCalculatorTypes(netWorthCalculator),eraseCalculatorTypes(inflationCalculator),eraseCalculatorTypes(simpleInterestCalculator),eraseCalculatorTypes(emergencyFundCalculator),eraseCalculatorTypes(bmiCalculator),...healthBatch1Definitions.map(definition=>definition as unknown as RegistryCalculator),...healthBatch2Definitions.map(definition=>definition as unknown as RegistryCalculator),eraseCalculatorTypes(breakEvenCalculator),...businessGrowthBatch1Definitions.map(definition=>definition as unknown as RegistryCalculator),...launchDefinitions.filter(definition=>!new Set(["z-score-calculator","speed-calculator","acceleration-calculator","force-calculator","work-calculator","power-calculator","kinetic-energy-calculator","potential-energy-calculator","momentum-calculator","pressure-calculator","density-calculator","frequency-calculator","period-calculator","wavelength-calculator","ohms-law-calculator","electrical-power-calculator","voltage-calculator","current-calculator","resistance-calculator","capacitance-calculator","coulomb-force-calculator","projectile-motion-calculator","free-fall-calculator","torque-calculator","angular-velocity-calculator","titration-calculator","beer-lambert-law-calculator","nernst-equation-calculator","half-life-calculator","stoichiometry-calculator","solution-concentration-calculator","percent-composition-calculator","gas-density-calculator","ideal-gas-law-calculator","ph-calculator","dilution-calculator","moles-calculator","molecular-weight-calculator","molarity-calculator","molality-calculator"]).has(definition.slug)).map(eraseCalculatorTypes),...advancedMathDefinitions.map(definition=>definition as unknown as RegistryCalculator),...advancedMathBatch6Definitions.map(definition=>definition as unknown as RegistryCalculator),...advancedMathBatch7Definitions.map(definition=>definition as unknown as RegistryCalculator),...advancedMathBatch8Definitions.map(definition=>definition as unknown as RegistryCalculator),...advancedMathBatch9Definitions.map(definition=>definition as unknown as RegistryCalculator),...advancedMathBatch10Definitions.map(definition=>definition as unknown as RegistryCalculator),...advancedMathFinalDefinitions.map(definition=>definition as unknown as RegistryCalculator),...geometryCompletionDefinitions.map(definition=>definition as unknown as RegistryCalculator),...statisticsBatch1Definitions.map(definition=>definition as unknown as RegistryCalculator),...statisticsBatch2Definitions.map(definition=>definition as unknown as RegistryCalculator),...statisticsBatch3Definitions.map(definition=>definition as unknown as RegistryCalculator),...statisticsBatch4Definitions.map(definition=>definition as unknown as RegistryCalculator),...physicsBatch1Definitions.map(definition=>definition as unknown as RegistryCalculator),...physicsBatch2Definitions.map(definition=>definition as unknown as RegistryCalculator),...physicsBatch3Definitions.map(definition=>definition as unknown as RegistryCalculator),...chemistryBatch1Definitions.map(definition=>definition as unknown as RegistryCalculator),...engineeringConstructionBatch1Definitions.map(definition=>definition as unknown as RegistryCalculator),...engineeringConstructionBatch2Definitions.map(definition=>definition as unknown as RegistryCalculator),...engineeringConstructionBatch3Definitions.map(definition=>definition as unknown as RegistryCalculator),...technologyBatch1Definitions.map(definition=>definition as unknown as RegistryCalculator),...technologyBatch2Definitions.map(definition=>definition as unknown as RegistryCalculator)];
const bySlug=new Map<string,RegistryCalculator>();const byId=new Map<string,RegistryCalculator>();for(const definition of definitions){if(bySlug.has(definition.slug))throw new Error(`Duplicate calculator slug: ${definition.slug}`);if(byId.has(definition.id))throw new Error(`Duplicate calculator id: ${definition.id}`);bySlug.set(definition.slug,definition);byId.set(definition.id,definition);}export const calculatorRegistry={list:():readonly RegistryCalculator[]=>definitions,getBySlug:(slug:string)=>bySlug.get(slug),getById:(id:string)=>byId.get(id)} as const;
