import { describe,expect,it } from "vitest";
import { compareScenarios } from "./scenarios";
describe("compareScenarios",()=>{
 it("runs scenarios and compares explicit metrics",()=>{const r=compareScenarios([{id:"base",label:"Base",input:{principal:100}},{id:"extra",label:"Extra",input:{principal:80}}],i=>({cost:i.principal*1.1,value:200-i.principal}),[{id:"cost",value:o=>o.cost,preference:"lower"},{id:"value",value:o=>o.value,preference:"higher"}]);expect(r.metrics[0].preferredScenarioId).toBe("extra");expect(r.metrics[1].preferredScenarioId).toBe("extra");});
 it("does not invent preference without an explicit preference",()=>{const r=compareScenarios([{id:"a",label:"A",input:1},{id:"b",label:"B",input:2}],i=>({score:i}),[{id:"score",value:o=>o.score}]);expect(r.metrics[0].preferredScenarioId).toBeUndefined();});
 it("does not invent a winner for an exact tie",()=>{const r=compareScenarios([{id:"a",label:"A",input:1},{id:"b",label:"B",input:2}],()=>({score:5}),[{id:"score",value:o=>o.score,preference:"higher"}]);expect(r.metrics[0].preferredScenarioId).toBeUndefined();});
 it("rejects empty labels and empty or reserved identifiers",()=>{expect(()=>compareScenarios([{id:"a",label:" ",input:1},{id:"b",label:"B",input:2}],x=>x,[{id:"x",value:x=>x}])).toThrow(/label.*empty/);expect(()=>compareScenarios([{id:" ",label:"A",input:1},{id:"b",label:"B",input:2}],x=>x,[{id:"x",value:x=>x}])).toThrow(/empty/);expect(()=>compareScenarios([{id:"__proto__",label:"A",input:1},{id:"b",label:"B",input:2}],x=>x,[{id:"x",value:x=>x}])).toThrow(/reserved/);expect(()=>compareScenarios([{id:"a",label:"A",input:1},{id:"b",label:"B",input:2}],x=>x,[{id:"constructor",value:x=>x}])).toThrow(/reserved/);});
 it("validates scenarios metrics and finite outputs",()=>{expect(()=>compareScenarios([{id:"a",label:"A",input:1}],x=>x,[{id:"x",value:x=>x}])).toThrow(/at least two/);expect(()=>compareScenarios([{id:"a",label:"A",input:1},{id:"a",label:"Again",input:2}],x=>x,[{id:"x",value:x=>x}])).toThrow(/unique/);expect(()=>compareScenarios([{id:"a",label:"A",input:1},{id:"b",label:"B",input:2}],x=>x,[])).toThrow(/at least one metric/);expect(()=>compareScenarios([{id:"a",label:"A",input:1},{id:"b",label:"B",input:2}],()=>Number.POSITIVE_INFINITY,[{id:"x",value:x=>x}])).toThrow(/finite/);});
});
