import { z } from "zod";
import type { CalculatorDefinition } from "../types";

const source={label:"ISO 8601 date and time representation",url:"https://www.iso.org/iso-8601-date-and-time-format.html",note:"CalcuMint uses explicit timestamps and UTC offsets. This DRAFT calculator does not infer IANA timezone or daylight-saving rules."};
const base={category:"date-time",version:1,riskClass:"standard" as const,reviewStatus:"draft" as const,sources:[source]};
const LOCAL=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/;
const INSTANT=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})Z$/;
function utcMs(parts:number[]){const [y,mo,d,h,mi,s]=parts,dt=new Date(0);dt.setUTCHours(h!,mi!,s??0,0);dt.setUTCFullYear(y!,mo!-1,d!);if(dt.getUTCFullYear()!==y||dt.getUTCMonth()!==mo!-1||dt.getUTCDate()!==d||dt.getUTCHours()!==h||dt.getUTCMinutes()!==mi||dt.getUTCSeconds()!==(s??0))throw new Error("Invalid calendar timestamp");return dt.getTime()}
function parseLocal(v:string){const m=LOCAL.exec(v);if(!m)throw new Error("Timestamp must use YYYY-MM-DDTHH:MM");return utcMs(m.slice(1).map(Number))}
function parseInstant(v:string){const m=INSTANT.exec(v);if(!m)throw new Error("Instant must use YYYY-MM-DDTHH:MM:SSZ");return utcMs(m.slice(1).map(Number))}
const localTimestamp=z.string().refine(v=>{try{parseLocal(v);return true}catch{return false}},"Invalid local timestamp");
const instant=z.string().refine(v=>{try{parseInstant(v);return true}catch{return false}},"Invalid UTC instant");
const offset=z.number().int().min(-840).max(840);
function localString(ms:number){const d=new Date(ms);if(d.getUTCFullYear()<0||d.getUTCFullYear()>9999)throw new Error("Result is outside the supported four-digit date range");return `${String(d.getUTCFullYear()).padStart(4,"0")}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}T${String(d.getUTCHours()).padStart(2,"0")}:${String(d.getUTCMinutes()).padStart(2,"0")}`}

type ZoneIn={localDateTime:string;sourceOffsetMinutes:number;targetOffsetMinutes:number};type ZoneOut={localDateTime:string;utcOffsetMinutes:number};
export const timeZoneCalculator:CalculatorDefinition<ZoneIn,ZoneOut>={...base,id:"date-time.time-zone",slug:"time-zone-calculator",title:"Time Zone Calculator",inputSchema:z.object({localDateTime:localTimestamp,sourceOffsetMinutes:offset,targetOffsetMinutes:offset}),calculate:({localDateTime,sourceOffsetMinutes,targetOffsetMinutes})=>{if(!Number.isInteger(sourceOffsetMinutes)||sourceOffsetMinutes< -840||sourceOffsetMinutes>840||!Number.isInteger(targetOffsetMinutes)||targetOffsetMinutes< -840||targetOffsetMinutes>840)throw new Error("UTC offsets must be integer minutes between -840 and 840");const instantMs=parseLocal(localDateTime)-sourceOffsetMinutes*60000;return{localDateTime:localString(instantMs+targetOffsetMinutes*60000),utcOffsetMinutes:targetOffsetMinutes}},formulas:[{id:"offset-conversion",expression:"UTC = source local - source offset; target local = UTC + target offset",description:"Converts between explicit fixed UTC offsets. It does not infer DST or historical timezone rules."}],examples:[{label:"India to UTC",input:{localDateTime:"2026-09-29T12:00",sourceOffsetMinutes:330,targetOffsetMinutes:0},expected:{localDateTime:"2026-09-29T06:30",utcOffsetMinutes:0}}],goldenTests:[{label:"India to UTC",input:{localDateTime:"2026-09-29T12:00",sourceOffsetMinutes:330,targetOffsetMinutes:0},expected:{localDateTime:"2026-09-29T06:30",utcOffsetMinutes:0}}],ui:{simpleInputKeys:["localDateTime","sourceOffsetMinutes","targetOffsetMinutes"]}};

type CountdownIn={referenceInstant:string;targetInstant:string};type CountdownOut={days:number;hours:number;minutes:number;seconds:number;totalSeconds:number};
export const countdownCalculator:CalculatorDefinition<CountdownIn,CountdownOut>={...base,id:"date-time.countdown",slug:"countdown-calculator",title:"Countdown Calculator",inputSchema:z.object({referenceInstant:instant,targetInstant:instant}),calculate:({referenceInstant,targetInstant})=>{const start=parseInstant(referenceInstant),end=parseInstant(targetInstant);if(end<start)throw new Error("targetInstant must not precede referenceInstant");const totalSeconds=Math.floor((end-start)/1000);let r=totalSeconds;const days=Math.floor(r/86400);r%=86400;const hours=Math.floor(r/3600);r%=3600;const minutes=Math.floor(r/60),seconds=r%60;return{days,hours,minutes,seconds,totalSeconds}},formulas:[{id:"countdown",expression:"remaining = target instant - reference instant",description:"Deterministic countdown from an explicit UTC reference instant; the engine never reads the current clock."}],examples:[{label:"One day plus",input:{referenceInstant:"2026-09-29T00:00:00Z",targetInstant:"2026-09-30T01:02:03Z"},expected:{days:1,hours:1,minutes:2,seconds:3,totalSeconds:90123}}],goldenTests:[{label:"One day plus",input:{referenceInstant:"2026-09-29T00:00:00Z",targetInstant:"2026-09-30T01:02:03Z"},expected:{days:1,hours:1,minutes:2,seconds:3,totalSeconds:90123}}],ui:{simpleInputKeys:["referenceInstant","targetInstant"]}};

export const dateTimeBatch4Definitions=[timeZoneCalculator,countdownCalculator] as const;
