import { z } from "zod";
import type { CalculatorDefinition } from "../types";

function addMonthsClamped(p:DateParts,months:number){const total=p.year*12+(p.month-1)+months,y=Math.floor(total/12),m=((total%12)+12)%12+1,result={year:y,month:m,day:Math.min(p.day,dim(y,m))};if(!Number.isFinite(result.year)||!Number.isFinite(result.month)||!Number.isFinite(result.day))throw new Error("Result is outside the supported four-digit date range");return result}
const dateString=z.string().refine(v=>{try{parseDate(v);return true}catch{return false}},"Invalid ISO calendar date");
const base={category:"date-time",version:1,riskClass:"standard" as const,reviewStatus:"draft" as const,sources:[source]};

type AgeIn={birthDate:string;asOfDate:string};type AgeOut={years:number;months:number;days:number};
export const ageCalculator:CalculatorDefinition<AgeIn,AgeOut>={...base,id:"date-time.age",slug:"age-calculator",title:"Age Calculator",inputSchema:z.object({birthDate:dateString,asOfDate:dateString}),calculate:({birthDate,asOfDate})=>{const b=parseDate(birthDate),a=parseDate(asOfDate),end=epoch(a);if(end<epoch(b))throw new Error("asOfDate must not precede birthDate");let totalMonths=(a.year-b.year)*12+(a.month-b.month);let anchor=addMonthsClamped(b,totalMonths);if(epoch(anchor)>end){totalMonths--;anchor=addMonthsClamped(b,totalMonths)}const years=Math.trunc(totalMonths/12),months=totalMonths-years*12;return{years,months,days:end-epoch(anchor)}},formulas:[{id:"calendar-age",expression:"calendar difference from birthDate to asOfDate",description:"Whole calendar years, then months, then remaining days."}],examples:[{label:"Calendar age",input:{birthDate:"2000-01-15",asOfDate:"2026-09-28"},expected:{years:26,months:8,days:13}}],goldenTests:[{label:"Calendar age",input:{birthDate:"2000-01-15",asOfDate:"2026-09-28"},expected:{years:26,months:8,days:13}}],ui:{simpleInputKeys:["birthDate","asOfDate"]}};

type DiffIn={startDate:string;endDate:string};type DiffOut={days:number};
export const dateDifferenceCalculator:CalculatorDefinition<DiffIn,DiffOut>={...base,id:"date-time.date-difference",slug:"date-difference-calculator",title:"Date Difference Calculator",inputSchema:z.object({startDate:dateString,endDate:dateString}),calculate:({startDate,endDate})=>({days:epoch(parseDate(endDate))-epoch(parseDate(startDate))}),formulas:[{id:"elapsed-days",expression:"days = endDate - startDate",description:"Signed elapsed calendar days; equal dates return zero."}],examples:[{label:"Leap-day span",input:{startDate:"2024-02-28",endDate:"2024-03-01"},expected:{days:2}}],goldenTests:[{label:"Leap-day span",input:{startDate:"2024-02-28",endDate:"2024-03-01"},expected:{days:2}}],ui:{simpleInputKeys:["startDate","endDate"]}};

type AddIn={date:string;years:number;months:number;days:number};type AddOut={date:string};
export const dateAddSubtractCalculator:CalculatorDefinition<AddIn,AddOut>={...base,id:"date-time.date-add-subtract",slug:"date-add-subtract-calculator",title:"Date Add/Subtract Calculator",inputSchema:z.object({date:dateString,years:z.number().int().safe(),months:z.number().int().safe(),days:z.number().int().safe()}),calculate:({date,years,months,days})=>{if(!Number.isSafeInteger(years)||!Number.isSafeInteger(months)||!Number.isSafeInteger(days))throw new Error("Date offsets must be safe integers");const p=parseDate(date),totalMonths=years*12+months;if(!Number.isSafeInteger(totalMonths))throw new Error("Date offset arithmetic exceeds the safe integer range");const clamped=addMonthsClamped(p,totalMonths),finalDay=narrowDay(epochBig(clamped)+BigInt(days));const result=fromEpoch(finalDay);assertRange(result);return{date:iso(result)}},formulas:[{id:"calendar-add",expression:"target = clamp(date + years + months) + days",description:"Years/months use calendar arithmetic with end-of-month clamping; days are then added as calendar days."}],examples:[{label:"Month-end clamp",input:{date:"2024-01-31",years:0,months:1,days:0},expected:{date:"2024-02-29"}}],goldenTests:[{label:"Month-end clamp",input:{date:"2024-01-31",years:0,months:1,days:0},expected:{date:"2024-02-29"}}],ui:{simpleInputKeys:["date","years","months","days"]}};

export const dayCounterCalculator:CalculatorDefinition<DiffIn,DiffOut>={...base,id:"date-time.day-counter",slug:"day-counter",title:"Day Counter",inputSchema:z.object({startDate:dateString,endDate:dateString}),calculate:({startDate,endDate})=>({days:epoch(parseDate(endDate))-epoch(parseDate(startDate))}),formulas:[{id:"day-count",expression:"days = endDate - startDate",description:"Counts elapsed date boundaries; equal dates return zero and reversed ranges are negative."}],examples:[{label:"One week",input:{startDate:"2026-09-21",endDate:"2026-09-28"},expected:{days:7}}],goldenTests:[{label:"One week",input:{startDate:"2026-09-21",endDate:"2026-09-28"},expected:{days:7}}],ui:{simpleInputKeys:["startDate","endDate"]}};

type DowIn={date:string};type DowOut={dayIndex:number;dayName:string};
const names=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"] as const;
export const dayOfWeekCalculator:CalculatorDefinition<DowIn,DowOut>={...base,id:"date-time.day-of-week",slug:"day-of-week-calculator",title:"Day of Week Calculator",inputSchema:z.object({date:dateString}),calculate:({date})=>{const i=((epoch(parseDate(date))+4)%7+7)%7;return{dayIndex:i,dayName:names[i]!}},formulas:[{id:"weekday",expression:"weekday = Gregorian weekday(date)",description:"Returns Sunday=0 through Saturday=6 using UTC calendar arithmetic."}],examples:[{label:"Known Sunday",input:{date:"2026-09-27"},expected:{dayIndex:0,dayName:"Sunday"}}],goldenTests:[{label:"Known Sunday",input:{date:"2026-09-27"},expected:{dayIndex:0,dayName:"Sunday"}}],ui:{simpleInputKeys:["date"]}};
export const dateTimeBatch1Definitions=[ageCalculator,dateDifferenceCalculator,dateAddSubtractCalculator,dayCounterCalculator,dayOfWeekCalculator] as const;
