import{molecularWeightCalculator}from"./molecular-weight";import{z}from"zod";import type{CalculatorDefinition}from"../types";
const nonnegative=z.number().finite().min(0).max(1e100),positive=z.number().finite().positive().max(1e100);type Out={value:number;steps:readonly string[]};const checked=(v:number)=>{if(!Number.isFinite(v))throw new Error("Calculated result is outside the supported finite range");return v};function def<I>(x:CalculatorDefinition<I,Out>){return x}
const mk=<I>(id:string,slug:string,title:string,schema:z.ZodType<I>,calc:(x:I)=>number,expression:string,description:string,example:I,expected:number)=>{const label=title.replace(" Calculator","");return def({id,slug,title,category:"science",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:schema,calculate:(input:I)=>{const value=checked(calc(input));return{value,steps:[label+" = "+value]};},formulas:[{id,expression,description}],sources:[{label:"CalcuMint deterministic chemistry engine"}],examples:[{label:"Verified example",input:example,expected:{value:expected,steps:[label+" = "+expected]}}],goldenTests:[{label:"Verified example",input:example,expected:{value:expected,steps:[label+" = "+expected]}}]});};
export const molarityCalculator=mk("chemistry.molarity","molarity-calculator","Molarity Calculator",z.object({moles:nonnegative,solutionVolumeLiters:positive}),x=>x.moles/x.solutionVolumeLiters,"M=n/V","Molar concentration from amount of solute in moles and total solution volume in liters.",{moles:1,solutionVolumeLiters:2},0.5);
export const molalityCalculator=mk("chemistry.molality","molality-calculator","Molality Calculator",z.object({moles:nonnegative,solventMassKg:positive}),x=>x.moles/x.solventMassKg,"m=n/m_solvent","Molal concentration from amount of solute in moles and solvent mass in kilograms.",{moles:1,solventMassKg:2},0.5);
export const molesCalculator=mk("chemistry.moles","moles-calculator","Moles Calculator",z.object({massGrams:nonnegative,molarMass:positive}),x=>x.massGrams/x.molarMass,"n=m/M","Amount of substance from sample mass and molar mass.",{massGrams:18,molarMass:18},1);
export const dilutionCalculator=mk("chemistry.dilution","dilution-calculator","Dilution Calculator",z.object({initialConcentration:nonnegative,initialVolume:nonnegative,finalVolume:positive}),x=>x.initialConcentration*x.initialVolume/x.finalVolume,"C₂=C₁V₁/V₂","Final concentration from conservation of solute during dilution.",{initialConcentration:2,initialVolume:100,finalVolume:200},1);
export const phCalculator=mk("chemistry.ph","ph-calculator","pH Calculator",z.object({hydrogenIonConcentration:positive}),x=>-Math.log10(x.hydrogenIonConcentration),"pH=-log₁₀[H⁺]","pH from positive hydrogen-ion concentration in mol/L.",{hydrogenIonConcentration:1e-7},7);
export const idealGasLawCalculator=mk("chemistry.ideal-gas-law","ideal-gas-law-calculator","Ideal Gas Law Calculator",z.object({moles:nonnegative,temperatureKelvin:nonnegative,volumeLiters:positive}),x=>x.moles*0.082057366080960*x.temperatureKelvin/x.volumeLiters,"P=nRT/V","Pressure in atm from the ideal gas law using R=0.082057366080960 L·atm·mol⁻¹·K⁻¹.",{moles:1,temperatureKelvin:300,volumeLiters:24.617209824288},1);
export const gasDensityCalculator=mk("chemistry.gas-density","gas-density-calculator","Gas Density Calculator",z.object({pressureAtm:nonnegative,molarMassGPerMol:nonnegative,temperatureKelvin:positive}),x=>x.pressureAtm*x.molarMassGPerMol/(0.082057366080960*x.temperatureKelvin),"ρ=PM/RT","Ideal-gas density in g/L from pressure, molar mass and absolute temperature.",{pressureAtm:1,molarMassGPerMol:28,temperatureKelvin:273.15},1.249220935353164);
export const percentCompositionCalculator=mk("chemistry.percent-composition","percent-composition-calculator","Percent Composition Calculator",z.object({componentMass:nonnegative,totalMass:positive}),x=>100*x.componentMass/x.totalMass,"%=(component mass/total mass)×100","Mass percent of a component in a sample.",{componentMass:25,totalMass:100},25);
export const solutionConcentrationCalculator=mk("chemistry.solution-concentration","solution-concentration-calculator","Solution Concentration Calculator",z.object({soluteMassGrams:nonnegative,solutionVolumeLiters:positive}),x=>x.soluteMassGrams/x.solutionVolumeLiters,"c=m/V","Mass concentration in g/L from solute mass and total solution volume.",{soluteMassGrams:10,solutionVolumeLiters:2},5);
export const stoichiometryCalculator=mk("chemistry.stoichiometry","stoichiometry-calculator","Stoichiometry Calculator",z.object({knownMoles:nonnegative,knownCoefficient:positive,targetCoefficient:nonnegative}),x=>x.knownMoles*x.targetCoefficient/x.knownCoefficient,"n₂=n₁(ν₂/ν₁)","Target moles from a balanced-equation stoichiometric coefficient ratio.",{knownMoles:2,knownCoefficient:2,targetCoefficient:1},1);
export const halfLifeCalculator=mk("chemistry.half-life","half-life-calculator","Half-Life Calculator",z.object({initialAmount:nonnegative,elapsedTime:nonnegative,halfLife:positive}),x=>x.initialAmount*Math.pow(.5,x.elapsedTime/x.halfLife),"N=N₀(1/2)^(t/t½)","Remaining amount after first-order half-life decay.",{initialAmount:100,elapsedTime:20,halfLife:10},25);
export const nernstEquationCalculator=mk("chemistry.nernst-equation","nernst-equation-calculator","Nernst Equation Calculator",z.object({standardPotential:z.number().finite().min(-1e100).max(1e100),temperatureKelvin:positive,electronCount:positive,reactionQuotient:positive}),x=>x.standardPotential-(8.31446261815324*x.temperatureKelvin/(x.electronCount*96485.33212))*Math.log(x.reactionQuotient),"E=E°-(RT/nF)lnQ","Cell potential from the Nernst equation with SI constants.",{standardPotential:1,temperatureKelvin:298.15,electronCount:1,reactionQuotient:1},1);
export const beerLambertLawCalculator=mk("chemistry.beer-lambert-law","beer-lambert-law-calculator","Beer-Lambert Law Calculator",z.object({molarAbsorptivity:nonnegative,pathLength:nonnegative,concentration:nonnegative}),x=>x.molarAbsorptivity*x.pathLength*x.concentration,"A=εbc","Absorbance from molar absorptivity, optical path length and concentration.",{molarAbsorptivity:2,pathLength:1,concentration:.5},1);
export const titrationCalculator=mk("chemistry.titration","titration-calculator","Titration Calculator",z.object({titrantConcentration:nonnegative,titrantVolume:nonnegative,analyteVolume:positive,titrantCoefficient:positive,analyteCoefficient:positive}),x=>x.titrantConcentration*x.titrantVolume*x.analyteCoefficient/(x.analyteVolume*x.titrantCoefficient),"Cₐ=CₜVₜνₐ/(Vₐνₜ)","Analyte concentration at equivalence using balanced-reaction stoichiometric coefficients.",{titrantConcentration:.1,titrantVolume:25,analyteVolume:25,titrantCoefficient:1,analyteCoefficient:1},.1);
export const chemistryBatch1Definitions=[molarityCalculator,molalityCalculator,molecularWeightCalculator,molesCalculator,dilutionCalculator,phCalculator,idealGasLawCalculator,gasDensityCalculator,percentCompositionCalculator,solutionConcentrationCalculator,stoichiometryCalculator,halfLifeCalculator,nernstEquationCalculator,beerLambertLawCalculator,titrationCalculator] as const;