import { z } from "zod";
import type { CalculatorDefinition } from "../types";
type Out={value:number;steps:string[]};
const money=z.number().finite().nonnegative().max(1e12);
const source={label:"CalcuMint Master Calculator Catalog 2026 — Travel & Everyday scope",note:"Catalog-authorized DRAFT scope. Independent formula/source review remains required before certification or publication."};
const base={category:"everyday",version:1,riskClass:"standard" as const,reviewStatus:"draft" as const,sources:[source],jurisdictions:[{country:"GLOBAL"}]};
export const householdUtilityCostCalculator:CalculatorDefinition<{electricity:number;water:number;gas:number;internet:number;other:number},Out>={...base,id:"travel.household-utility-cost",slug:"household-utility-cost-calculator",title:"Household Utility Cost Calculator",inputSchema:z.object({electricity:money,water:money,gas:money,internet:money,other:money}),calculate:i=>{z.object({electricity:money,water:money,gas:money,internet:money,other:money}).parse(i);const value=i.electricity+i.water+i.gas+i.internet+i.other;if(!Number.isFinite(value))throw new Error("Calculated result is outside the supported finite range");return{value,steps:[`Total utility cost = ${value}`]};},formulas:[{id:"household-utility-total",expression:"total utility cost = electricity + water + gas + internet + other",description:"Sum user-supplied household utility cost components."}],examples:[{label:"Reference example",input:{electricity:100,water:30,gas:40,internet:50,other:20},expected:{value:240,steps:["Total utility cost = 240"]}}],goldenTests:[{label:"Reference example",input:{electricity:100,water:30,gas:40,internet:50,other:20},expected:{value:240}}]};
export const movingCostCalculator:CalculatorDefinition<{transport:number;packing:number;labor:number;storage:number;other:number},Out>={...base,id:"travel.moving-cost",slug:"moving-cost-calculator",title:"Moving Cost Calculator",inputSchema:z.object({transport:money,packing:money,labor:money,storage:money,other:money}),calculate:i=>{z.object({transport:money,packing:money,labor:money,storage:money,other:money}).parse(i);const value=i.transport+i.packing+i.labor+i.storage+i.other;if(!Number.isFinite(value))throw new Error("Calculated result is outside the supported finite range");return{value,steps:[`Total moving cost = ${value}`]};},formulas:[{id:"moving-cost-total",expression:"total moving cost = transport + packing + labor + storage + other",description:"Sum user-supplied moving cost components."}],examples:[{label:"Reference example",input:{transport:500,packing:100,labor:300,storage:150,other:50},expected:{value:1100,steps:["Total moving cost = 1100"]}}],goldenTests:[{label:"Reference example",input:{transport:500,packing:100,labor:300,storage:150,other:50},expected:{value:1100}}]};
export const travelEverydayBatch3Definitions=[householdUtilityCostCalculator,movingCostCalculator] as const;
