-- CalcuMint B5: Business organizations, teams, shared workspaces and audit foundation
-- Apply after B3 accounts and B4 billing migrations.

create type public.organization_role as enum ('owner','admin','manager','member','viewer');
create type public.invitation_status as enum ('pending','accepted','revoked','expired');

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$'),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.organization_role not null default 'member',
  joined_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create table public.organization_invitations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  email text not null,
  role public.organization_role not null default 'member',
  token_hash text not null unique,
  status public.invitation_status not null default 'pending',
  invited_by uuid not null references auth.users(id),
  expires_at timestamptz not null default (now() + interval '7 days'),
  accepted_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index organization_pending_invite_unique
  on public.organization_invitations (organization_id, lower(email))
  where status = 'pending';

create table public.business_projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 120),
  description text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.client_workspaces (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 160),
  reference_code text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.shared_calculations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  project_id uuid references public.business_projects(id) on delete set null,
  client_workspace_id uuid references public.client_workspaces(id) on delete set null,
  calculator_slug text not null,
  calculator_version integer not null check (calculator_version > 0),
  title text,
  input_data jsonb not null default '{}'::jsonb,
  output_data jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.shared_templates (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  calculator_slug text not null,
  name text not null check (char_length(name) between 1 and 120),
  preset_input jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.organization_audit_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index organization_members_user_idx on public.organization_members(user_id);
create index business_projects_org_idx on public.business_projects(organization_id, created_at desc);
create index client_workspaces_org_idx on public.client_workspaces(organization_id, created_at desc);
create index shared_calculations_org_idx on public.shared_calculations(organization_id, created_at desc);
create index shared_templates_org_idx on public.shared_templates(organization_id, created_at desc);
create index organization_audit_org_idx on public.organization_audit_events(organization_id, created_at desc);

create or replace function public.organization_role_rank(p_role public.organization_role)
returns integer language sql immutable as $$
  select case p_role
    when 'viewer' then 10 when 'member' then 20 when 'manager' then 30 when 'admin' then 40 when 'owner' then 50
  end;
$$;

create or replace function public.has_organization_role(p_organization_id uuid, p_min_role public.organization_role)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.organization_members m
    where m.organization_id = p_organization_id
      and m.user_id = auth.uid()
      and public.organization_role_rank(m.role) >= public.organization_role_rank(p_min_role)
  );
$$;

create or replace function public.create_business_organization(p_name text, p_slug text)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_id uuid;
begin
  if not exists (select 1 from public.profiles where id = auth.uid() and plan = 'business') then
    raise exception 'Business plan required';
  end if;
  insert into public.organizations(name, slug, created_by)
  values (trim(p_name), lower(trim(p_slug)), auth.uid()) returning id into v_id;
  insert into public.organization_members(organization_id, user_id, role)
  values (v_id, auth.uid(), 'owner');
  insert into public.organization_audit_events(organization_id, actor_user_id, action, target_type, target_id)
  values (v_id, auth.uid(), 'organization.created', 'organization', v_id::text);
  return v_id;
end;
$$;

create or replace function public.accept_business_invitation(p_token_hash text)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_invite public.organization_invitations%rowtype;
  v_email text;
begin
  select lower(coalesce(auth.jwt()->>'email','')) into v_email;
  select * into v_invite
  from public.organization_invitations
  where token_hash = p_token_hash
    and status = 'pending'
    and expires_at > now()
    and lower(email) = v_email
  for update;
  if v_invite.id is null then raise exception 'Invitation is invalid or expired'; end if;
  insert into public.organization_members(organization_id, user_id, role)
  values (v_invite.organization_id, auth.uid(), v_invite.role)
  on conflict (organization_id, user_id) do update set role = excluded.role;
  update public.organization_invitations
  set status = 'accepted', accepted_at = now()
  where id = v_invite.id;
  insert into public.organization_audit_events(organization_id, actor_user_id, action, target_type, target_id)
  values (v_invite.organization_id, auth.uid(), 'invitation.accepted', 'invitation', v_invite.id::text);
  return v_invite.organization_id;
end;
$$;

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.organization_invitations enable row level security;
alter table public.business_projects enable row level security;
alter table public.client_workspaces enable row level security;
alter table public.shared_calculations enable row level security;
alter table public.shared_templates enable row level security;
alter table public.organization_audit_events enable row level security;

create policy organizations_member_read on public.organizations for select using (public.has_organization_role(id, 'viewer'));
create policy organizations_admin_update on public.organizations for update using (public.has_organization_role(id, 'admin')) with check (public.has_organization_role(id, 'admin'));

create policy members_member_read on public.organization_members for select using (public.has_organization_role(organization_id, 'viewer'));
create policy members_admin_insert on public.organization_members for insert with check (public.has_organization_role(organization_id, 'admin'));
create policy members_admin_update on public.organization_members for update using (public.has_organization_role(organization_id, 'admin')) with check (public.has_organization_role(organization_id, 'admin'));
create policy members_admin_delete on public.organization_members for delete using (public.has_organization_role(organization_id, 'admin') and role <> 'owner');

create policy invitations_admin_read on public.organization_invitations for select using (public.has_organization_role(organization_id, 'admin') or lower(email) = lower(coalesce(auth.jwt()->>'email','')));
create policy invitations_admin_insert on public.organization_invitations for insert with check (public.has_organization_role(organization_id, 'admin') and invited_by = auth.uid() and role <> 'owner');
create policy invitations_admin_update on public.organization_invitations for update using (public.has_organization_role(organization_id, 'admin')) with check (public.has_organization_role(organization_id, 'admin'));

create policy projects_member_read on public.business_projects for select using (public.has_organization_role(organization_id, 'viewer'));
create policy projects_manager_insert on public.business_projects for insert with check (public.has_organization_role(organization_id, 'manager') and created_by = auth.uid());
create policy projects_manager_update on public.business_projects for update using (public.has_organization_role(organization_id, 'manager')) with check (public.has_organization_role(organization_id, 'manager'));
create policy projects_manager_delete on public.business_projects for delete using (public.has_organization_role(organization_id, 'manager'));

create policy clients_member_read on public.client_workspaces for select using (public.has_organization_role(organization_id, 'viewer'));
create policy clients_manager_insert on public.client_workspaces for insert with check (public.has_organization_role(organization_id, 'manager') and created_by = auth.uid());
create policy clients_manager_update on public.client_workspaces for update using (public.has_organization_role(organization_id, 'manager')) with check (public.has_organization_role(organization_id, 'manager'));
create policy clients_manager_delete on public.client_workspaces for delete using (public.has_organization_role(organization_id, 'manager'));

create policy calculations_member_read on public.shared_calculations for select using (public.has_organization_role(organization_id, 'viewer'));
create policy calculations_member_insert on public.shared_calculations for insert with check (public.has_organization_role(organization_id, 'member') and created_by = auth.uid());
create policy calculations_member_update on public.shared_calculations for update using (public.has_organization_role(organization_id, 'member')) with check (public.has_organization_role(organization_id, 'member'));
create policy calculations_manager_delete on public.shared_calculations for delete using (public.has_organization_role(organization_id, 'manager') or created_by = auth.uid());

create policy templates_member_read on public.shared_templates for select using (public.has_organization_role(organization_id, 'viewer'));
create policy templates_manager_insert on public.shared_templates for insert with check (public.has_organization_role(organization_id, 'manager') and created_by = auth.uid());
create policy templates_manager_update on public.shared_templates for update using (public.has_organization_role(organization_id, 'manager')) with check (public.has_organization_role(organization_id, 'manager'));
create policy templates_manager_delete on public.shared_templates for delete using (public.has_organization_role(organization_id, 'manager'));

create policy audit_member_read on public.organization_audit_events for select using (public.has_organization_role(organization_id, 'manager'));

revoke all on function public.create_business_organization(text,text) from public;
grant execute on function public.create_business_organization(text,text) to authenticated;
revoke all on function public.accept_business_invitation(text) from public;
grant execute on function public.accept_business_invitation(text) to authenticated;
