-- CalcuMint B5: Business organizations, roles, projects, clients and audit trail

create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  owner_user_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','admin','manager','member','viewer')),
  joined_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create table if not exists public.organization_invitations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  email text not null,
  role text not null check (role in ('admin','manager','member','viewer')),
  token_hash text not null unique,
  invited_by uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  accepted_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists organization_pending_invite_email_idx
  on public.organization_invitations(organization_id, lower(email))
  where accepted_at is null;

create table if not exists public.business_projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 140),
  description text check (description is null or char_length(description)<=2000),
  status text not null default 'active' check (status in ('active','archived')),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.client_workspaces (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  project_id uuid references public.business_projects(id) on delete set null,
  name text not null check (char_length(name) between 2 and 140),
  client_reference text check (client_reference is null or char_length(client_reference)<=240),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shared_calculations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  project_id uuid references public.business_projects(id) on delete set null,
  client_workspace_id uuid references public.client_workspaces(id) on delete set null,
  calculator_slug text not null check (char_length(calculator_slug) between 1 and 160),
  calculator_version integer not null check (calculator_version > 0),
  title text check (title is null or char_length(title)<=240),
  input_data jsonb not null default '{}'::jsonb,
  output_data jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_audit_log (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists organization_members_user_idx on public.organization_members(user_id);
create index if not exists business_projects_org_idx on public.business_projects(organization_id, created_at desc);
create index if not exists client_workspaces_org_idx on public.client_workspaces(organization_id, created_at desc);
create index if not exists shared_calculations_org_idx on public.shared_calculations(organization_id, created_at desc);
create index if not exists organization_audit_log_org_idx on public.organization_audit_log(organization_id, created_at desc);

create or replace function public.is_org_member(target_org uuid)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists(
    select 1 from public.organization_members m
    where m.organization_id = target_org and m.user_id = auth.uid()
  );
$$;

create or replace function public.org_role(target_org uuid)
returns text language sql stable security definer set search_path = public
as $$
  select m.role from public.organization_members m
  where m.organization_id = target_org and m.user_id = auth.uid()
  limit 1;
$$;

create or replace function public.has_org_role(target_org uuid, allowed_roles text[])
returns boolean language sql stable security definer set search_path = public
as $$
  select coalesce(public.org_role(target_org) = any(allowed_roles), false);
$$;

create or replace function public.create_business_organization(org_name text, org_slug text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare new_id uuid;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not exists(select 1 from public.profiles where id = auth.uid() and plan = 'business') then
    raise exception 'Business plan required';
  end if;

  insert into public.organizations(name, slug, owner_user_id)
  values (trim(org_name), lower(trim(org_slug)), auth.uid())
  returning id into new_id;

  insert into public.organization_members(organization_id, user_id, role)
  values (new_id, auth.uid(), 'owner');

  insert into public.organization_audit_log(organization_id, actor_user_id, action, entity_type, entity_id)
  values (new_id, auth.uid(), 'organization.created', 'organization', new_id::text);

  return new_id;
end;
$$;

create or replace function public.accept_business_invitation(invite_token_hash text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare inv public.organization_invitations%rowtype;
declare member_count integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;

  select * into inv from public.organization_invitations
  where token_hash = invite_token_hash and accepted_at is null and expires_at > now()
  limit 1;
  if inv.id is null then raise exception 'Invitation is invalid or expired'; end if;
  if lower(inv.email) <> lower(coalesce((select email from auth.users where id = auth.uid()), '')) then
    raise exception 'Invitation email does not match signed-in account';
  end if;

  select count(*) into member_count from public.organization_members where organization_id = inv.organization_id;
  if member_count >= 5 then raise exception 'Included Business seat limit reached'; end if;

  insert into public.organization_members(organization_id, user_id, role)
  values (inv.organization_id, auth.uid(), inv.role)
  on conflict (organization_id, user_id) do update set role = excluded.role;

  update public.organization_invitations set accepted_at = now() where id = inv.id;
  insert into public.organization_audit_log(organization_id, actor_user_id, action, entity_type, entity_id)
  values (inv.organization_id, auth.uid(), 'member.joined', 'user', auth.uid()::text);
  return inv.organization_id;
end;
$$;

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.organization_invitations enable row level security;
alter table public.business_projects enable row level security;
alter table public.client_workspaces enable row level security;
alter table public.shared_calculations enable row level security;
alter table public.organization_audit_log enable row level security;

create policy "organizations_member_select" on public.organizations for select using (public.is_org_member(id));
create policy "organizations_admin_update" on public.organizations for update using (public.has_org_role(id, array['owner','admin'])) with check (public.has_org_role(id, array['owner','admin']));

create policy "members_org_select" on public.organization_members for select using (public.is_org_member(organization_id));
create policy "members_admin_update" on public.organization_members for update using (public.has_org_role(organization_id, array['owner','admin'])) with check (role <> 'owner' or public.org_role(organization_id) = 'owner');
create policy "members_admin_delete" on public.organization_members for delete using (public.has_org_role(organization_id, array['owner','admin']) and role <> 'owner');

create policy "invites_admin_select" on public.organization_invitations for select using (public.has_org_role(organization_id, array['owner','admin']));
create policy "invites_admin_insert" on public.organization_invitations for insert with check (public.has_org_role(organization_id, array['owner','admin']) and invited_by = auth.uid());
create policy "invites_admin_delete" on public.organization_invitations for delete using (public.has_org_role(organization_id, array['owner','admin']));

create policy "projects_member_select" on public.business_projects for select using (public.is_org_member(organization_id));
create policy "projects_manager_insert" on public.business_projects for insert with check (public.has_org_role(organization_id, array['owner','admin','manager']) and created_by = auth.uid());
create policy "projects_manager_update" on public.business_projects for update using (public.has_org_role(organization_id, array['owner','admin','manager']));

create policy "clients_member_select" on public.client_workspaces for select using (public.is_org_member(organization_id));
create policy "clients_manager_insert" on public.client_workspaces for insert with check (public.has_org_role(organization_id, array['owner','admin','manager']) and created_by = auth.uid());
create policy "clients_manager_update" on public.client_workspaces for update using (public.has_org_role(organization_id, array['owner','admin','manager']));

create policy "shared_member_select" on public.shared_calculations for select using (public.is_org_member(organization_id));
create policy "shared_editor_insert" on public.shared_calculations for insert with check (public.has_org_role(organization_id, array['owner','admin','manager','member']) and created_by = auth.uid());
create policy "shared_editor_update" on public.shared_calculations for update using (public.has_org_role(organization_id, array['owner','admin','manager','member']));

create policy "audit_member_select" on public.organization_audit_log for select using (public.is_org_member(organization_id));

revoke all on function public.create_business_organization(text, text) from public;
grant execute on function public.create_business_organization(text, text) to authenticated;
revoke all on function public.accept_business_invitation(text) from public;
grant execute on function public.accept_business_invitation(text) to authenticated;
