-- CalcuMint B7: white-label embeds, share links, leads, consent and delivery analytics

create table if not exists public.embed_configs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  calculator_id uuid not null references public.custom_calculators(id) on delete cascade,
  public_key text not null unique check (public_key ~ '^[A-Za-z0-9_-]{24,96}$'),
  name text not null check (char_length(name) between 2 and 120),
  status text not null default 'active' check (status in ('active','paused','archived')),
  allowed_domains text[] not null default '{}',
  allow_direct boolean not null default true,
  company_name text,
  logo_url text,
  accent_color text not null default '#0b7a66' check (accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  hide_calcumint_brand boolean not null default false,
  cta_label text,
  cta_url text,
  lead_capture_enabled boolean not null default false,
  lead_fields text[] not null default array['name','email'],
  consent_text text,
  privacy_url text,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.share_links (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  calculator_id uuid not null references public.custom_calculators(id) on delete cascade,
  token_hash text not null unique,
  label text,
  expires_at timestamptz,
  password_hash text,
  is_revoked boolean not null default false,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.embed_leads (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  embed_config_id uuid not null references public.embed_configs(id) on delete cascade,
  calculator_id uuid not null references public.custom_calculators(id) on delete cascade,
  name text,
  email text,
  phone text,
  company text,
  custom_data jsonb not null default '{}'::jsonb,
  calculation_input jsonb,
  calculation_output jsonb,
  source_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.lead_consents (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.embed_leads(id) on delete cascade,
  consent_text text not null,
  privacy_url text,
  consented boolean not null,
  captured_at timestamptz not null default now()
);

create table if not exists public.embed_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  embed_config_id uuid not null references public.embed_configs(id) on delete cascade,
  calculator_id uuid not null references public.custom_calculators(id) on delete cascade,
  event_type text not null check (event_type in ('view','calculate','lead_submit','cta_click')),
  source_url text,
  referrer text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists embed_configs_org_idx on public.embed_configs(organization_id, updated_at desc);
create index if not exists embed_configs_calculator_idx on public.embed_configs(calculator_id);
create index if not exists share_links_org_idx on public.share_links(organization_id, created_at desc);
create index if not exists embed_leads_org_idx on public.embed_leads(organization_id, created_at desc);
create index if not exists embed_events_org_idx on public.embed_events(organization_id, created_at desc);

alter table public.embed_configs enable row level security;
alter table public.share_links enable row level security;
alter table public.embed_leads enable row level security;
alter table public.lead_consents enable row level security;
alter table public.embed_events enable row level security;

create policy "embed_configs_members_read" on public.embed_configs
for select using (public.is_org_member(organization_id));
create policy "embed_configs_admin_write" on public.embed_configs
for all using (public.has_org_role(organization_id, array['owner','admin','manager']))
with check (public.has_org_role(organization_id, array['owner','admin','manager']) and created_by = auth.uid());

create policy "share_links_members_read" on public.share_links
for select using (public.is_org_member(organization_id));
create policy "share_links_builder_write" on public.share_links
for all using (public.has_org_role(organization_id, array['owner','admin','manager']))
with check (public.has_org_role(organization_id, array['owner','admin','manager']) and created_by = auth.uid());

create policy "embed_leads_members_read" on public.embed_leads
for select using (public.is_org_member(organization_id));
create policy "lead_consents_members_read" on public.lead_consents
for select using (exists (
  select 1 from public.embed_leads l
  where l.id = lead_id and public.is_org_member(l.organization_id)
));
create policy "embed_events_members_read" on public.embed_events
for select using (public.is_org_member(organization_id));

-- Public visitors never receive direct INSERT/SELECT permissions on lead/event tables.
-- B7 server endpoints use the server-only service role after validating the public embed key.
