-- CalcuMint B8: Business API, usage metering, batch jobs and outbound webhooks

create table if not exists public.business_api_keys (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 120),
  key_prefix text not null,
  key_hash text not null unique,
  scopes jsonb not null default '[]'::jsonb,
  status text not null default 'active' check (status in ('active','revoked')),
  rate_limit_per_minute integer not null default 60 check (rate_limit_per_minute between 1 and 5000),
  monthly_quota integer not null default 10000 check (monthly_quota between 1 and 10000000),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

create table if not exists public.api_usage_events (
  id bigint generated by default as identity primary key,
  api_key_id uuid not null references public.business_api_keys(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  request_kind text not null,
  units integer not null default 1 check (units > 0),
  request_id uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now()
);

create table if not exists public.batch_calculation_jobs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  api_key_id uuid references public.business_api_keys(id) on delete set null,
  calculator_id uuid not null references public.custom_calculators(id) on delete cascade,
  calculator_version integer not null check (calculator_version > 0),
  status text not null default 'queued' check (status in ('queued','processing','completed','failed')),
  input_rows jsonb not null,
  output_rows jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create table if not exists public.business_webhook_endpoints (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 120),
  endpoint_url text not null check (endpoint_url ~ '^https://'),
  secret_ciphertext text not null,
  event_types jsonb not null default '[]'::jsonb,
  status text not null default 'active' check (status in ('active','paused','disabled')),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.webhook_deliveries (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  endpoint_id uuid not null references public.business_webhook_endpoints(id) on delete cascade,
  event_type text not null,
  event_id uuid not null default gen_random_uuid(),
  payload jsonb not null,
  status text not null default 'queued' check (status in ('queued','delivering','delivered','failed','dead_letter')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  next_attempt_at timestamptz not null default now(),
  last_http_status integer,
  last_error text,
  created_at timestamptz not null default now(),
  delivered_at timestamptz
);

create index if not exists business_api_keys_org_idx on public.business_api_keys(organization_id, created_at desc);
create index if not exists api_usage_key_time_idx on public.api_usage_events(api_key_id, created_at desc);
create index if not exists api_usage_org_time_idx on public.api_usage_events(organization_id, created_at desc);
create index if not exists batch_jobs_org_idx on public.batch_calculation_jobs(organization_id, created_at desc);
create index if not exists webhook_endpoints_org_idx on public.business_webhook_endpoints(organization_id, created_at desc);
create index if not exists webhook_delivery_queue_idx on public.webhook_deliveries(status, next_attempt_at);

alter table public.business_api_keys enable row level security;
alter table public.api_usage_events enable row level security;
alter table public.batch_calculation_jobs enable row level security;
alter table public.business_webhook_endpoints enable row level security;
alter table public.webhook_deliveries enable row level security;

create policy "api_keys_admin_read" on public.business_api_keys for select using (public.has_org_role(organization_id, array['owner','admin']));
create policy "api_keys_admin_insert" on public.business_api_keys for insert with check (public.has_org_role(organization_id, array['owner','admin']) and created_by = auth.uid());
create policy "api_keys_admin_update" on public.business_api_keys for update using (public.has_org_role(organization_id, array['owner','admin'])) with check (public.has_org_role(organization_id, array['owner','admin']));
create policy "usage_org_read" on public.api_usage_events for select using (public.has_org_role(organization_id, array['owner','admin','manager']));
create policy "batch_org_read" on public.batch_calculation_jobs for select using (public.is_org_member(organization_id));
create policy "webhook_admin_read" on public.business_webhook_endpoints for select using (public.has_org_role(organization_id, array['owner','admin']));
create policy "webhook_admin_insert" on public.business_webhook_endpoints for insert with check (public.has_org_role(organization_id, array['owner','admin']) and created_by = auth.uid());
create policy "webhook_admin_update" on public.business_webhook_endpoints for update using (public.has_org_role(organization_id, array['owner','admin']));
create policy "webhook_delivery_admin_read" on public.webhook_deliveries for select using (public.has_org_role(organization_id, array['owner','admin','manager']));

create or replace function public.consume_business_api_quota(p_api_key_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare v_key public.business_api_keys%rowtype;
declare v_month_count bigint;
declare v_minute_count bigint;
begin
  select * into v_key from public.business_api_keys where id = p_api_key_id and status = 'active';
  if v_key.id is null then return false; end if;

  select coalesce(sum(units),0) into v_month_count from public.api_usage_events
  where api_key_id = p_api_key_id and created_at >= date_trunc('month', now());
  if v_month_count >= v_key.monthly_quota then return false; end if;

  select coalesce(sum(units),0) into v_minute_count from public.api_usage_events
  where api_key_id = p_api_key_id and created_at >= now() - interval '1 minute';
  if v_minute_count >= v_key.rate_limit_per_minute then return false; end if;

  insert into public.api_usage_events(api_key_id, organization_id, request_kind, units)
  values (v_key.id, v_key.organization_id, 'request', 1);
  return true;
end;
$$;

create or replace function public.enqueue_business_webhook_event(p_organization_id uuid, p_event_type text, p_payload jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare inserted_count integer;
begin
  insert into public.webhook_deliveries(organization_id, endpoint_id, event_type, payload)
  select p_organization_id, e.id, p_event_type, p_payload
  from public.business_webhook_endpoints e
  where e.organization_id = p_organization_id
    and e.status = 'active'
    and e.event_types ? p_event_type;
  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

create or replace function public.queue_calculation_webhooks()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.enqueue_business_webhook_event(new.organization_id, 'calculation.completed', jsonb_build_object(
    'run_id', new.id,
    'calculator_id', new.calculator_id,
    'calculator_version', new.calculator_version,
    'input', new.input_data,
    'output', new.output_data,
    'created_at', new.created_at
  ));
  return new;
end;
$$;

create or replace function public.queue_lead_webhooks()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  perform public.enqueue_business_webhook_event(new.organization_id, 'lead.created', jsonb_build_object(
    'lead_id', new.id,
    'calculator_id', new.calculator_id,
    'email', new.email,
    'name', new.name,
    'company', new.company,
    'created_at', new.created_at
  ));
  return new;
end;
$$;

drop trigger if exists custom_runs_queue_webhooks on public.custom_calculator_runs;
create trigger custom_runs_queue_webhooks after insert on public.custom_calculator_runs for each row execute function public.queue_calculation_webhooks();
drop trigger if exists embed_leads_queue_webhooks on public.embed_leads;
create trigger embed_leads_queue_webhooks after insert on public.embed_leads for each row execute function public.queue_lead_webhooks();

revoke all on function public.consume_business_api_quota(uuid) from public;
grant execute on function public.consume_business_api_quota(uuid) to service_role;
revoke all on function public.enqueue_business_webhook_event(uuid,text,jsonb) from public;
grant execute on function public.enqueue_business_webhook_event(uuid,text,jsonb) to service_role;
