-- CalcuMint B9: AI request metering and plan-aware quotas

create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  organization_id uuid references public.organizations(id) on delete set null,
  feature text not null check (feature in ('finder','explain','scenario','builder')),
  provider text,
  model text,
  input_tokens integer check (input_tokens is null or input_tokens >= 0),
  output_tokens integer check (output_tokens is null or output_tokens >= 0),
  succeeded boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_user_time_idx on public.ai_usage_events(user_id, created_at desc);
create index if not exists ai_usage_org_time_idx on public.ai_usage_events(organization_id, created_at desc);

alter table public.ai_usage_events enable row level security;
create policy "ai_usage_user_read" on public.ai_usage_events for select using (user_id = auth.uid());
create policy "ai_usage_org_admin_read" on public.ai_usage_events for select using (organization_id is not null and public.has_org_role(organization_id, array['owner','admin']));

create or replace function public.consume_ai_quota(p_feature text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare v_user uuid := auth.uid();
declare v_plan text;
declare v_limit integer;
declare v_count bigint;
declare v_org uuid;
declare v_id bigint;
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  if p_feature not in ('finder','explain','scenario','builder') then raise exception 'Unknown AI feature'; end if;

  select plan into v_plan from public.profiles where id = v_user;
  v_plan := coalesce(v_plan, 'free');
  if p_feature = 'builder' and v_plan <> 'business' then raise exception 'Business plan required'; end if;
  if p_feature in ('explain','scenario') and v_plan not in ('pro','business') then raise exception 'Pro or Business plan required'; end if;

  v_limit := case v_plan when 'business' then 1000 when 'pro' then 200 else 10 end;
  select count(*) into v_count from public.ai_usage_events
    where user_id = v_user and created_at >= date_trunc('month', now());
  if v_count >= v_limit then raise exception 'Monthly AI request limit reached'; end if;
  if p_feature='builder' and not exists(select 1 from public.organization_members m where m.user_id=v_user and public.has_org_role(m.organization_id,array['owner','admin','manager'])) then raise exception 'Builder permission required'; end if;

  if exists(select 1 from public.ai_usage_events where user_id = v_user and created_at >= now() - interval '1 minute' having count(*) >= 10) then
    raise exception 'AI request rate limit reached';
  end if;

  select organization_id into v_org from public.organization_members where user_id = v_user order by joined_at asc limit 1;
  insert into public.ai_usage_events(user_id, organization_id, feature)
    values (v_user, v_org, p_feature) returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.consume_ai_quota(text) from public;
grant execute on function public.consume_ai_quota(text) to authenticated;

create or replace function public.finish_ai_usage(
  p_usage_id bigint,
  p_provider text,
  p_model text,
  p_input_tokens integer,
  p_output_tokens integer,
  p_succeeded boolean
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.ai_usage_events set
    provider = left(p_provider, 120),
    model = left(p_model, 160),
    input_tokens = greatest(coalesce(p_input_tokens, 0), 0),
    output_tokens = greatest(coalesce(p_output_tokens, 0), 0),
    succeeded = p_succeeded
  where id = p_usage_id and user_id = auth.uid();
end;
$$;

revoke all on function public.finish_ai_usage(bigint,text,text,integer,integer,boolean) from public;
grant execute on function public.finish_ai_usage(bigint,text,text,integer,integer,boolean) to authenticated;
