-- CalcuMint B10: platform administration, review workflow and publishing factory

create table if not exists public.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','admin','reviewer','editor')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.is_platform_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.platform_admins a where a.user_id = auth.uid() and a.active)
$$;

create or replace function public.has_platform_role(allowed text[])
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.platform_admins a where a.user_id = auth.uid() and a.active and a.role = any(allowed))
$$;

create table if not exists public.calculator_catalog_admin (
  id uuid primary key default gen_random_uuid(),
  calculator_key text not null unique,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  title text not null check (char_length(title) between 2 and 160),
  category text not null check (char_length(category) between 2 and 100),
  risk_class text not null default 'standard' check (risk_class in ('standard','financial','health','tax')),
  lifecycle text not null default 'draft' check (lifecycle in ('draft','review','certified','published','archived')),
  version integer not null default 1 check (version > 0),
  reviewer_id uuid references auth.users(id) on delete set null,
  review_notes text,
  source_count integer not null default 0 check (source_count >= 0),
  publish_at timestamptz,
  published_at timestamptz,
  last_reviewed_at timestamptz,
  next_review_due_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.calculator_qa_checks (
  id uuid primary key default gen_random_uuid(),
  calculator_id uuid not null references public.calculator_catalog_admin(id) on delete cascade,
  check_type text not null check (check_type in ('engine-tests','formula-review','sources','methodology','seo-content','accessibility','ymyl-review')),
  status text not null default 'pending' check (status in ('pending','passed','failed','waived')),
  details text,
  checked_by uuid references auth.users(id) on delete set null,
  checked_at timestamptz,
  unique(calculator_id, check_type)
);

create table if not exists public.calculator_review_events (
  id bigint generated by default as identity primary key,
  calculator_id uuid not null references public.calculator_catalog_admin(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete restrict,
  event_type text not null,
  from_state text,
  to_state text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.calculator_bulk_jobs (
  id uuid primary key default gen_random_uuid(),
  job_type text not null check (job_type in ('inventory-import','qa-refresh','review-reminder','scheduled-publish')),
  status text not null default 'queued' check (status in ('queued','processing','completed','failed')),
  requested_by uuid not null references auth.users(id) on delete restrict,
  payload jsonb not null default '{}'::jsonb,
  result jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create table if not exists public.admin_alerts (
  id uuid primary key default gen_random_uuid(),
  calculator_id uuid references public.calculator_catalog_admin(id) on delete cascade,
  severity text not null check (severity in ('info','warning','critical')),
  alert_type text not null,
  message text not null,
  status text not null default 'open' check (status in ('open','acknowledged','resolved')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists calculator_admin_lifecycle_idx on public.calculator_catalog_admin(lifecycle, updated_at desc);
create index if not exists calculator_admin_review_due_idx on public.calculator_catalog_admin(next_review_due_at) where lifecycle = 'published';
create index if not exists qa_checks_calculator_idx on public.calculator_qa_checks(calculator_id, check_type);
create index if not exists review_events_calculator_idx on public.calculator_review_events(calculator_id, created_at desc);
create index if not exists admin_alerts_status_idx on public.admin_alerts(status, severity, created_at desc);

alter table public.platform_admins enable row level security;
alter table public.calculator_catalog_admin enable row level security;
alter table public.calculator_qa_checks enable row level security;
alter table public.calculator_review_events enable row level security;
alter table public.calculator_bulk_jobs enable row level security;
alter table public.admin_alerts enable row level security;

create policy "admins_read_self" on public.platform_admins for select using (user_id = auth.uid() and active);
create policy "catalog_admin_read" on public.calculator_catalog_admin for select using (public.is_platform_admin());
create policy "catalog_editor_insert" on public.calculator_catalog_admin for insert with check (public.has_platform_role(array['owner','admin','reviewer','editor']) and created_by = auth.uid());
create policy "catalog_editor_update" on public.calculator_catalog_admin for update using (public.has_platform_role(array['owner','admin','reviewer','editor'])) with check (public.has_platform_role(array['owner','admin','reviewer','editor']));
create policy "qa_admin_read" on public.calculator_qa_checks for select using (public.is_platform_admin());
create policy "qa_reviewer_write" on public.calculator_qa_checks for all using (public.has_platform_role(array['owner','admin','reviewer'])) with check (public.has_platform_role(array['owner','admin','reviewer']));
create policy "events_admin_read" on public.calculator_review_events for select using (public.is_platform_admin());
create policy "events_admin_insert" on public.calculator_review_events for insert with check (public.is_platform_admin() and actor_id = auth.uid());
create policy "jobs_admin_read" on public.calculator_bulk_jobs for select using (public.is_platform_admin());
create policy "jobs_admin_insert" on public.calculator_bulk_jobs for insert with check (public.has_platform_role(array['owner','admin']) and requested_by = auth.uid());
create policy "alerts_admin_read" on public.admin_alerts for select using (public.is_platform_admin());
create policy "alerts_admin_update" on public.admin_alerts for update using (public.has_platform_role(array['owner','admin','reviewer']));

-- platform_admins intentionally has no authenticated INSERT/UPDATE/DELETE policy.
-- Bootstrap/role changes must be performed with the service role or controlled operations tooling.

create or replace function public.validate_calculator_publish_gate(p_calculator_id uuid)
returns table(ok boolean, failures text[])
language plpgsql
security definer
set search_path = public
as $$
declare v_calc public.calculator_catalog_admin%rowtype;
declare v_failures text[] := '{}';
declare v_required text[] := array['engine-tests','formula-review','sources','methodology','seo-content','accessibility'];
declare v_check text;
declare v_status text;
begin
  select * into v_calc from public.calculator_catalog_admin where id = p_calculator_id;
  if v_calc.id is null then return query select false, array['Calculator not found']; return; end if;
  if v_calc.source_count < 1 then v_failures := array_append(v_failures, 'At least one reviewed source is required'); end if;
  if v_calc.risk_class in ('financial','health','tax') then
    v_required := array_append(v_required, 'ymyl-review');
    if v_calc.reviewer_id is null then v_failures := array_append(v_failures, 'YMYL reviewer is required'); end if;
  end if;
  foreach v_check in array v_required loop
    select status into v_status from public.calculator_qa_checks where calculator_id = p_calculator_id and check_type = v_check;
    if coalesce(v_status, 'pending') not in ('passed','waived') then
      v_failures := array_append(v_failures, format('%s must pass', v_check));
    end if;
  end loop;
  return query select cardinality(v_failures) = 0, v_failures;
end;
$$;

revoke all on function public.validate_calculator_publish_gate(uuid) from public;
grant execute on function public.validate_calculator_publish_gate(uuid) to authenticated, service_role;

create or replace function public.enforce_calculator_publish_gate()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_ok boolean; declare v_failures text[];
begin
  if new.lifecycle in ('certified','published') and new.lifecycle is distinct from old.lifecycle then
    select ok, failures into v_ok, v_failures from public.validate_calculator_publish_gate(new.id);
    if not v_ok then raise exception 'Publishing gate failed: %', array_to_string(v_failures, '; '); end if;
  end if;
  if new.lifecycle = 'published' and new.published_at is null then new.published_at := now(); end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger calculator_publish_gate_before_update before update on public.calculator_catalog_admin
for each row execute function public.enforce_calculator_publish_gate();
