import { z } from "zod";
import type { CalculatorDefinition } from "../types";
import { roundTo } from "../precision";
type In={absorbance260:number;dilutionFactor:number}; type Out={concentrationNgPerUl:number;steps:readonly string[]};
const schema=z.object({absorbance260:z.number().finite().min(0).max(1e6),dilutionFactor:z.number().finite().positive().max(1e9)});
const mk=(id:string,slug:string,title:string,factor:number,kind:string):CalculatorDefinition<In,Out>=>({id,slug,title,category:"biology",version:1,riskClass:"standard",reviewStatus:"draft",inputSchema:schema,calculate:x=>{schema.parse(x);const concentrationNgPerUl=roundTo(x.absorbance260*factor*x.dilutionFactor,6);return{concentrationNgPerUl,steps:[`${kind} concentration = A260 × ${factor} × dilution factor = ${concentrationNgPerUl} ng/µL`]};},formulas:[{id:slug,expression:`concentration (ng/µL) = A260 × ${factor} × dilution factor`,description:`UV A260 concentration estimate for ${kind}; the dilution factor is explicit and the standard 1-cm-pathlength conversion factor is used.`}],sources:[{label:"New England Biolabs — Nucleic Acid Data",url:"https://www.neb.com/en/tools-and-resources/usage-guidelines/nucleic-acid-data",note:"Lists A260=1 conversion factors of 50 µg/mL for dsDNA and 40 µg/mL for RNA; 1 µg/mL equals 1 ng/µL."}],examples:[{label:"A260 0.2 at 10× dilution",input:{absorbance260:.2,dilutionFactor:10},expected:{concentrationNgPerUl:.2*factor*10,steps:[`${kind} concentration = A260 × ${factor} × dilution factor = ${.2*factor*10} ng/µL`]}}],goldenTests:[{label:"A260 conversion",input:{absorbance260:1,dilutionFactor:1},expected:{concentrationNgPerUl:factor}}],ui:{simpleInputKeys:["absorbance260","dilutionFactor"]}});
export const dnaConcentrationCalculator=mk("biology.dna-concentration","dna-concentration-calculator","DNA Concentration Calculator",50,"dsDNA");
export const rnaConcentrationCalculator=mk("biology.rna-concentration","rna-concentration-calculator","RNA Concentration Calculator",40,"RNA");
export const biologyBatch8Definitions=[dnaConcentrationCalculator,rnaConcentrationCalculator] as const;
