import{z}from"zod";import type{CalculatorDefinition}from"../types";
const nonnegativeInteger=z.number().int().min(0).max(10000);
const probability=z.number().finite().min(0).max(1);
const finite=z.number().finite().min(-1e100).max(1e100);
const productRange=(start:number,end:number)=>{let result=1;for(let i=start;i<=end;i++){result*=i;if(!Number.isSafeInteger(result))throw new Error("Result exceeds the supported exact integer range")}return result};

export type CombinationOutput={combinations:number;n:number;r:number;steps:readonly string[]};
export const combinationCalculator:CalculatorDefinition<{n:number;r:number},CombinationOutput>={id:"statistics.combination",slug:"combination-calculator",title:"Combination Calculator",category:"statistics",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({n:nonnegativeInteger,r:nonnegativeInteger}).refine(({n,r})=>r<=n,{message:"r must be less than or equal to n"}),calculate:({n,r})=>{const k=Math.min(r,n-r);let combinations=1;for(let i=1;i<=k;i++){combinations=combinations*(n-k+i)/i;if(!Number.isSafeInteger(combinations))throw new Error("Result exceeds the supported exact integer range")}return{combinations,n,r,steps:[`n = ${n}; r = ${r}`,`C(n,r) = n!/(r!(n-r)!) = ${combinations}`]};},formulas:[{id:"combination",expression:"C(n,r)=n!/(r!(n−r)!)",description:"Counts unordered selections of r objects from n distinct objects without replacement."}],sources:[{label:"CalcuMint deterministic statistics engine"}],examples:[{label:"Five choose three",input:{n:5,r:3},expected:{combinations:10,n:5,r:3,steps:["n = 5; r = 3","C(n,r) = n!/(r!(n-r)!) = 10"]}}],goldenTests:[{label:"Five choose three",input:{n:5,r:3},expected:{combinations:10,n:5,r:3,steps:["n = 5; r = 3","C(n,r) = n!/(r!(n-r)!) = 10"]}}]};

const logCombination=(n:number,k:number)=>{const m=Math.min(k,n-k);let value=0;for(let i=1;i<=m;i++)value+=Math.log(n-m+i)-Math.log(i);return value};
export type BinomialProbabilityOutput={probability:number;n:number;k:number;p:number;steps:readonly string[]};
export const binomialProbabilityCalculator:CalculatorDefinition<{n:number;k:number;p:number},BinomialProbabilityOutput>={id:"statistics.binomial-probability",slug:"binomial-probability-calculator",title:"Binomial Probability Calculator",category:"statistics",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({n:nonnegativeInteger,k:nonnegativeInteger,p:probability}).refine(({n,k})=>k<=n,{message:"k must be less than or equal to n"}),calculate:({n,k,p})=>{let result:number;if(p===0)result=k===0?1:0;else if(p===1)result=k===n?1:0;else result=Math.exp(logCombination(n,k)+k*Math.log(p)+(n-k)*Math.log1p(-p));if(!Number.isFinite(result))throw new Error("Probability is outside the supported numeric range");const bounded=Math.min(1,Math.max(0,result));return{probability:bounded,n,k,p,steps:[`n = ${n}; k = ${k}; p = ${p}`,`P(X=k) = C(n,k)p^k(1-p)^(n-k) = ${bounded}`]};},formulas:[{id:"binomial-pmf",expression:"P(X=k)=C(n,k)p^k(1−p)^(n−k)",description:"Calculates the probability of exactly k successes in n independent Bernoulli trials."}],sources:[{label:"CalcuMint deterministic statistics engine"}],examples:[{label:"Three successes in ten fair trials",input:{n:10,k:3,p:0.5},expected:{probability:0.1171875,n:10,k:3,p:0.5,steps:["n = 10; k = 3; p = 0.5","P(X=k) = C(n,k)p^k(1-p)^(n-k) = 0.11718750000000014"]}}],goldenTests:[{label:"Three successes in ten fair trials",input:{n:10,k:3,p:0.5},expected:{probability:0.1171875,n:10,k:3,p:0.5,steps:["n = 10; k = 3; p = 0.5","P(X=k) = C(n,k)p^k(1-p)^(n-k) = 0.11718750000000014"]}}]};

const normalCdf=(zValue:number)=>{const sign=zValue<0?-1:1,x=Math.abs(zValue)/Math.sqrt(2),t=1/(1+0.3275911*x),a1=0.254829592,a2=-0.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429;const erf=sign*(1-(((((a5*t+a4)*t)+a3)*t+a2)*t+a1)*t*Math.exp(-x*x));return(1+erf)/2};
export type NormalDistributionOutput={zScore:number;pdf:number;cdf:number;upperTail:number;steps:readonly string[]};
export const normalDistributionCalculator:CalculatorDefinition<{x:number;mean:number;standardDeviation:number},NormalDistributionOutput>={id:"statistics.normal-distribution",slug:"normal-distribution-calculator",title:"Normal Distribution Calculator",category:"statistics",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({x:finite,mean:finite,standardDeviation:z.number().finite().positive().max(1e100)}),calculate:({x,mean,standardDeviation})=>{const zScore=(x-mean)/standardDeviation;if(!Number.isFinite(zScore))throw new Error("Z-score is outside the supported numeric range");const pdf=Math.exp(-0.5*zScore*zScore)/(standardDeviation*Math.sqrt(2*Math.PI)),cdf=normalCdf(zScore),upperTail=1-cdf;return{zScore,pdf,cdf,upperTail,steps:[`z = (x-μ)/σ = ${zScore}`,`PDF = ${pdf}`,`P(X≤x) ≈ ${cdf}`]};},formulas:[{id:"normal-distribution",expression:"z=(x−μ)/σ; f(x)=exp(−z²/2)/(σ√(2π))",description:"Standardizes x and evaluates normal density plus an approximation to the cumulative distribution."}],sources:[{label:"CalcuMint deterministic statistics engine"}],examples:[{label:"At the mean",input:{x:0,mean:0,standardDeviation:1},expected:{zScore:0,pdf:0.3989422804014327,cdf:0.5000000005,upperTail:0.4999999995,steps:["z = (x-μ)/σ = 0","PDF = 0.3989422804014327","P(X≤x) ≈ 0.5000000005"]}}],goldenTests:[{label:"At the mean",input:{x:0,mean:0,standardDeviation:1},expected:{zScore:0,pdf:0.3989422804014327,cdf:0.5000000005,upperTail:0.4999999995,steps:["z = (x-μ)/σ = 0","PDF = 0.3989422804014327","P(X≤x) ≈ 0.5000000005"]}}]};

const dataset=z.array(z.number().finite().min(-1e100).max(1e100)).min(2).max(10000);
export type CorrelationOutput={correlation:number;count:number;meanX:number;meanY:number;steps:readonly string[]};
export const correlationCalculator:CalculatorDefinition<{xValues:number[];yValues:number[]},CorrelationOutput>={id:"statistics.correlation",slug:"correlation-calculator",title:"Correlation Calculator",category:"statistics",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({xValues:dataset,yValues:dataset}).refine(({xValues,yValues})=>xValues.length===yValues.length,{message:"Datasets must have equal length"}),calculate:({xValues,yValues})=>{const count=xValues.length,meanX=xValues.reduce((a,b)=>a+b,0)/count,meanY=yValues.reduce((a,b)=>a+b,0)/count;let cross=0,sx=0,sy=0;for(let i=0;i<count;i++){const dx=xValues[i]-meanX,dy=yValues[i]-meanY;cross+=dx*dy;sx+=dx*dx;sy+=dy*dy}if(sx===0||sy===0)throw new Error("Correlation is undefined for a constant dataset");const correlation=Math.max(-1,Math.min(1,cross/Math.sqrt(sx*sy)));return{correlation,count,meanX,meanY,steps:[`n = ${count}; mean(x) = ${meanX}; mean(y) = ${meanY}`,`r = Σ((x-x̄)(y-ȳ))/√(Σ(x-x̄)²Σ(y-ȳ)²) = ${correlation}`]};},formulas:[{id:"pearson-correlation",expression:"r=Σ((x−x̄)(y−ȳ))/√(Σ(x−x̄)²Σ(y−ȳ)²)",description:"Calculates the Pearson product-moment correlation coefficient for paired numeric observations."}],sources:[{label:"CalcuMint deterministic statistics engine"}],examples:[{label:"Perfect positive relationship",input:{xValues:[1,2,3],yValues:[2,4,6]},expected:{correlation:1,count:3,meanX:2,meanY:4,steps:["n = 3; mean(x) = 2; mean(y) = 4","r = Σ((x-x̄)(y-ȳ))/√(Σ(x-x̄)²Σ(y-ȳ)²) = 1"]}}],goldenTests:[{label:"Perfect positive relationship",input:{xValues:[1,2,3],yValues:[2,4,6]},expected:{correlation:1,count:3,meanX:2,meanY:4,steps:["n = 3; mean(x) = 2; mean(y) = 4","r = Σ((x-x̄)(y-ȳ))/√(Σ(x-x̄)²Σ(y-ȳ)²) = 1"]}}]};

export const statisticsBatch3Definitions=[combinationCalculator,binomialProbabilityCalculator,normalDistributionCalculator,correlationCalculator]as const;
