import{z}from"zod";import type{CalculatorDefinition}from"../types";
const dataset=z.array(z.number().finite().min(-1e100).max(1e100)).min(1).max(10000);
const sample=z.enum(["population","sample"]);
const sorted=(x:readonly number[])=>[...x].sort((a,b)=>a-b);
const stableSum=(x:readonly number[])=>{const a=[...x].sort((u,v)=>Math.abs(u)-Math.abs(v));let sum=0,c=0;for(const value of a){const y=value-c,t=sum+y;c=(t-sum)-y;sum=t}return sum};
const mean=(x:readonly number[])=>stableSum(x)/x.length;
const median=(x:readonly number[])=>{const a=sorted(x),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const variance=(x:readonly number[],kind:"population"|"sample")=>{if(kind==="sample"&&x.length<2)throw new Error("Sample statistics require at least two values");const m=mean(x),den=kind==="sample"?x.length-1:x.length;return x.reduce((s,v)=>s+(v-m)**2,0)/den};
export type SummaryOutput={count:number;mean:number;median:number;modes:number[];minimum:number;maximum:number;range:number;steps:readonly string[]};
export const meanMedianModeRangeCalculator:CalculatorDefinition<{values:number[]},SummaryOutput>={id:"statistics.summary",slug:"mean-median-mode-range-calculator",title:"Mean Median Mode Range Calculator",category:"statistics",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({values:dataset}),calculate:({values})=>{const a=sorted(values),m=mean(values),med=median(values),counts=new Map<number,number>();for(const v of values)counts.set(v,(counts.get(v)??0)+1);const maxCount=Math.max(...counts.values()),modes=maxCount===1?[]:[...counts].filter(([,n])=>n===maxCount).map(([v])=>v).sort((x,y)=>x-y);return{count:values.length,mean:m,median:med,modes,minimum:a[0],maximum:a[a.length-1],range:a[a.length-1]-a[0],steps:[`Count = ${values.length}`,`Mean = sum / count = ${m}`,`Median = ${med}; range = ${a[a.length-1]-a[0]}`]};},formulas:[{id:"descriptive-summary",expression:"mean=Σx/n; range=max−min",description:"Computes common descriptive statistics from the supplied finite dataset."}],sources:[{label:"CalcuMint deterministic statistics engine"}],examples:[{label:"Simple dataset",input:{values:[1,2,2,4]},expected:{count:4,mean:2.25,median:2,modes:[2],minimum:1,maximum:4,range:3,steps:["Count = 4","Mean = sum / count = 2.25","Median = 2; range = 3"]}}],goldenTests:[{label:"Simple dataset",input:{values:[1,2,2,4]},expected:{count:4,mean:2.25,median:2,modes:[2],minimum:1,maximum:4,range:3,steps:["Count = 4","Mean = sum / count = 2.25","Median = 2; range = 3"]}}]};
export type DispersionOutput={count:number;mean:number;variance:number;standardDeviation:number;kind:"population"|"sample";steps:readonly string[]};
function dispersion(slug:string,title:string,id:string,primary:"variance"|"standardDeviation"):CalculatorDefinition<{values:number[];kind:"population"|"sample"},DispersionOutput>{return{id,slug,title,category:"statistics",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({values:dataset,kind:sample}),calculate:({values,kind})=>{const m=mean(values),v=variance(values,kind),sd=Math.sqrt(v);return{count:values.length,mean:m,variance:v,standardDeviation:sd,kind,steps:[`Mean = ${m}`,`${kind==="sample"?"Sample":"Population"} variance = ${v}`,`Standard deviation = √variance = ${sd}`]};},formulas:[{id:"dispersion",expression:primary==="variance"?"σ²=Σ(x−μ)²/N or s²=Σ(x−x̄)²/(n−1)":"σ=√variance or s=√sample variance",description:"Computes population or sample dispersion explicitly according to the selected denominator."}],sources:[{label:"CalcuMint deterministic statistics engine"}],examples:[{label:"Population 1,2,3",input:{values:[1,2,3],kind:"population"},expected:{count:3,mean:2,variance:2/3,standardDeviation:Math.sqrt(2/3),kind:"population",steps:["Mean = 2","Population variance = 0.6666666666666666","Standard deviation = √variance = 0.816496580927726"]}}],goldenTests:[{label:"Population 1,2,3",input:{values:[1,2,3],kind:"population"},expected:{count:3,mean:2,variance:2/3,standardDeviation:Math.sqrt(2/3),kind:"population",steps:["Mean = 2","Population variance = 0.6666666666666666","Standard deviation = √variance = 0.816496580927726"]}}]}}
export const standardDeviationCalculator=dispersion("standard-deviation-calculator","Standard Deviation Calculator","statistics.standard-deviation","standardDeviation");
export const varianceCalculator=dispersion("variance-calculator","Variance Calculator","statistics.variance","variance");
export type ZScoreOutput={zScore:number;deviation:number;steps:readonly string[]};
export const zScoreCalculator:CalculatorDefinition<{value:number;mean:number;standardDeviation:number},ZScoreOutput>={id:"statistics.z-score",slug:"z-score-calculator",title:"Z-Score Calculator",category:"statistics",version:1,riskClass:"standard",reviewStatus:"certified",inputSchema:z.object({value:z.number().finite(),mean:z.number().finite(),standardDeviation:z.number().finite().positive()}),calculate:({value,mean,standardDeviation})=>{const deviation=value-mean,zScore=deviation/standardDeviation;if(!Number.isFinite(deviation)||!Number.isFinite(zScore))throw new Error("Z-score is outside the supported numeric range");return{zScore,deviation,steps:[`Deviation = ${value} - ${mean} = ${deviation}`,`z = deviation / standard deviation = ${zScore}`]};},formulas:[{id:"z-score",expression:"z=(x−μ)/σ",description:"Standardizes a value by its supplied mean and positive standard deviation."}],sources:[{label:"CalcuMint deterministic statistics engine"}],examples:[{label:"One SD above mean",input:{value:110,mean:100,standardDeviation:10},expected:{zScore:1,deviation:10,steps:["Deviation = 110 - 100 = 10","z = deviation / standard deviation = 1"]}}],goldenTests:[{label:"One SD above mean",input:{value:110,mean:100,standardDeviation:10},expected:{zScore:1,deviation:10,steps:["Deviation = 110 - 100 = 10","z = deviation / standard deviation = 1"]}}]};
export const statisticsBatch1Definitions=[meanMedianModeRangeCalculator,standardDeviationCalculator,varianceCalculator,zScoreCalculator]as const;