import { z } from "zod";
import type { CalculatorDefinition } from "../types";

type Out={value:number;steps:readonly string[]};
const positive=z.number().finite().positive().max(1e100);
const nonnegative=z.number().finite().min(0).max(1e100);
const percent=z.number().finite().min(0).max(100);
const checked=(v:number)=>{if(!Number.isFinite(v))throw new Error("Calculated result is outside the supported finite range");return v};
const def=<I>(x:CalculatorDefinition<I,Out>)=>x;
const src={label:"CalcuMint Engineering Methodology",note:"Deterministic planning calculation using explicitly supplied physical or project assumptions; applicable codes, manufacturer data, site conditions and professional design requirements must be checked separately."};
const ceilUnits=(v:number)=>{const n=Math.round(v);const tol=Math.min(1e-9,Number.EPSILON*Math.max(1,Math.abs(v))*8);return Math.abs(v-n)<=tol?n:Math.ceil(v)};
const mk=<I>(id:string,slug:string,title:string,schema:z.ZodType<I>,calc:(x:I)=>number,expression:string,description:string,example:I,expected:number)=>def({id,slug,title,category:"engineering-construction",version:1,riskClass:"standard",reviewStatus:"reviewed",inputSchema:schema,calculate:(input:I)=>{const value=checked(calc(input));return{value,steps:[title.replace(" Calculator","")+" = "+value]}},formulas:[{id:slug,expression,description}],sources:[src],examples:[{label:"Verified example",input:example,expected:{value:expected,steps:[title.replace(" Calculator","")+" = "+expected]}}],goldenTests:[{label:"Verified example",input:example,expected:{value:expected,steps:[title.replace(" Calculator","")+" = "+expected]}}]});

export const poolVolumeCalculator=mk("engineering.pool-volume","pool-volume-calculator","Pool Volume Calculator",z.object({lengthMeters:positive,widthMeters:positive,averageDepthMeters:positive}),x=>x.lengthMeters*x.widthMeters*x.averageDepthMeters,"V=L×W×D","Rectangular pool volume from length, width and explicitly supplied average depth.",{lengthMeters:10,widthMeters:5,averageDepthMeters:1.5},75);
export const waterTankCalculator=mk("engineering.water-tank","water-tank-calculator","Water Tank Calculator",z.object({lengthMeters:positive,widthMeters:positive,heightMeters:positive}),x=>x.lengthMeters*x.widthMeters*x.heightMeters,"V=L×W×H","Rectangular tank capacity in cubic metres from internal dimensions.",{lengthMeters:2,widthMeters:1.5,heightMeters:2},6);
export const pipeVolumeCalculator=mk("engineering.pipe-volume","pipe-volume-calculator","Pipe Volume Calculator",z.object({lengthMeters:positive,internalDiameterMeters:positive}),x=>Math.PI*Math.pow(x.internalDiameterMeters/2,2)*x.lengthMeters,"V=π(d/2)²L","Internal cylindrical pipe volume using the supplied internal diameter and length.",{lengthMeters:10,internalDiameterMeters:.1},0.07853981633974483);
export const electricalLoadCalculator=mk("engineering.electrical-load","electrical-load-calculator","Electrical Load Calculator",z.object({voltageVolts:positive,currentAmps:positive}),x=>x.voltageVolts*x.currentAmps,"P=V×I","Apparent electrical power in volt-amperes for supplied voltage and current.",{voltageVolts:230,currentAmps:10},2300);
export const voltageDropCalculator=mk("engineering.voltage-drop","voltage-drop-calculator","Voltage Drop Calculator",z.object({currentAmps:positive,oneWayLengthMeters:positive,resistanceOhmsPerMeter:positive,conductors:positive.int().max(2)}),x=>x.currentAmps*x.oneWayLengthMeters*x.resistanceOhmsPerMeter*x.conductors,"ΔV=I×L×R×N","Voltage drop using supplied current, one-way conductor length, resistance per metre and number of conductors in the circuit path.",{currentAmps:10,oneWayLengthMeters:20,resistanceOhmsPerMeter:.001,conductors:2},0.4);
export const resistorCalculator=mk("engineering.resistor","resistor-calculator","Resistor Calculator",z.object({voltageVolts:positive,currentAmps:positive}),x=>x.voltageVolts/x.currentAmps,"R=V/I","Resistance from supplied voltage and current using Ohm's law.",{voltageVolts:12,currentAmps:.5},24);
export const hvacBtuCalculator=mk("engineering.hvac-btu","hvac-btu-calculator","HVAC BTU Calculator",z.object({floorAreaSquareMeters:positive,ceilingHeightMeters:positive,btuPerCubicMeter:positive}),x=>x.floorAreaSquareMeters*x.ceilingHeightMeters*x.btuPerCubicMeter,"BTU/h=area×ceiling height×BTU per cubic metre","Planning heat-load estimate using user-supplied volumetric BTU/h factor; it does not infer climate, insulation, glazing or occupancy.",{floorAreaSquareMeters:50,ceilingHeightMeters:2.5,btuPerCubicMeter:12},1500);
export const solarPanelRequirementCalculator=mk("engineering.solar-panel","solar-panel-requirement-calculator","Solar Panel Requirement Calculator",z.object({dailyEnergyKwh:positive,panelWatts:positive,peakSunHours:positive,systemEfficiencyPercent:percent.refine(v=>v>0)}),x=>ceilUnits(x.dailyEnergyKwh*1000/(x.panelWatts*x.peakSunHours*(x.systemEfficiencyPercent/100))),"panels=ceil(daily energy×1000/(panel watts×sun hours×efficiency))","Whole solar panels required from daily energy demand, panel rating, peak-sun hours and explicitly supplied system efficiency.",{dailyEnergyKwh:10,panelWatts:400,peakSunHours:5,systemEfficiencyPercent:80},7);
export const batteryStorageCalculator=mk("engineering.battery-storage","battery-storage-calculator","Battery Storage Calculator",z.object({dailyEnergyKwh:positive,backupDays:positive,depthOfDischargePercent:percent.refine(v=>v>0),systemEfficiencyPercent:percent.refine(v=>v>0)}),x=>x.dailyEnergyKwh*x.backupDays/((x.depthOfDischargePercent/100)*(x.systemEfficiencyPercent/100)),"storage=Daily energy×backup days/(DoD×efficiency)","Nominal battery energy capacity required from daily energy, backup duration, usable depth of discharge and system efficiency.",{dailyEnergyKwh:10,backupDays:1,depthOfDischargePercent:80,systemEfficiencyPercent:90},13.88888888888889);

const nistElectricalSource={label:"NIST Guide to the SI",url:"https://www.nist.gov/pml/special-publication-811/nist-guide-si-chapter-4-two-classes-si-units-and-si-prefixes",note:"NIST defines the volt as W/A and the ohm as V/A, supporting the SI unit relationships used by the electrical calculators."};
const nistOhmSource={label:"NIST — Ohm's Law",url:"https://www.nist.gov/si-redefinition/ampere/ampere-present",note:"NIST describes Ohm's law as I=V/R; rearranging gives R=V/I for the Resistor Calculator."};
const ashraeSource={label:"ASHRAE Load Calculation Applications Manual",url:"https://resourcecenter.ashrae.org/technical-resources/bookstore/load-calculation-applications-manual",note:"ASHRAE documents detailed heating/cooling load methods; the CalcuMint HVAC calculator is intentionally a simplified planning estimate using a user-supplied factor and is not a full load calculation."};
const solarSource={label:"U.S. Department of Energy — Solar Powering Your Community",url:"https://www.energy.gov/cmei/systems/articles/solar-powering-your-community-guide-local-governments-book-energy-efficiency",note:"DOE defines peak sun hours as equivalent hours per day at 1,000 W/m², supporting the meaning of the user-supplied peak-sun-hours input."};
const batterySource={label:"NREL — Technology Tips for Solar + Storage",url:"https://www.nrel.gov/docs/fy24osti/90582.pdf",note:"NREL discusses storage sizing using energy capacity and hours of autonomy, supporting explicit backup-duration and usable-capacity assumptions."};
electricalLoadCalculator.sources=[src,nistElectricalSource];
voltageDropCalculator.sources=[src,nistElectricalSource];
resistorCalculator.sources=[src,nistOhmSource];
hvacBtuCalculator.sources=[src,ashraeSource];
solarPanelRequirementCalculator.sources=[src,solarSource];
batteryStorageCalculator.sources=[src,batterySource];

export const engineeringConstructionBatch3Definitions=[poolVolumeCalculator,waterTankCalculator,pipeVolumeCalculator,electricalLoadCalculator,voltageDropCalculator,resistorCalculator,hvacBtuCalculator,solarPanelRequirementCalculator,batteryStorageCalculator] as const;
