import { z } from "zod";
import type { CalculatorDefinition } from "../types";
const positive=z.number().finite().positive().max(1e100),nonnegative=z.number().finite().min(0).max(1e100),waste=z.number().finite().min(0).max(100);
type Out={value:number;steps:readonly string[]};
// Avoid over-counting whole purchasable units when binary floating point lands infinitesimally above an exact integer.
const ceilUnits=(value:number)=>{const nearest=Math.round(value);const tolerance=Number.EPSILON*Math.max(1,Math.abs(value))*8;return Math.abs(value-nearest)<=tolerance?nearest:Math.ceil(value)};
const checked=(v:number)=>{if(!Number.isFinite(v))throw new Error("Calculated result is outside the supported finite range");return v};
function def<I>(x:CalculatorDefinition<I,Out>){return x}
const src={label:"CalcuMint Engineering Methodology",note:"Deterministic geometric/material-estimation method; project-specific codes, product coverage and site conditions must be checked separately."};
const mk=<I>(id:string,slug:string,title:string,schema:z.ZodType<I>,calc:(x:I)=>number,expression:string,description:string,example:I,expected:number)=>{const label=title.replace(" Calculator","");return def({id,slug,title,category:"engineering-construction",version:1,riskClass:"standard",reviewStatus:"reviewed",inputSchema:schema,calculate:(input:I)=>{const value=checked(calc(input));return{value,steps:[label+" = "+value]}},formulas:[{id,expression,description}],sources:[src],examples:[{label:"Verified example",input:example,expected:{value:expected,steps:[label+" = "+expected]}}],goldenTests:[{label:"Verified example",input:example,expected:{value:expected,steps:[label+" = "+expected]}}]})};
export const stairCalculator=mk("engineering.stair","stair-calculator","Stair Calculator",z.object({totalRiseCm:positive,targetRiserHeightCm:positive}),x=>ceilUnits(x.totalRiseCm/x.targetRiserHeightCm),"risers=ceil(total rise/target riser height)","Number of equal risers needed to span the total rise.",{totalRiseCm:280,targetRiserHeightCm:17.5},16);
export const fenceCalculator=mk("engineering.fence","fence-calculator","Fence Calculator",z.object({fenceLengthMeters:positive,panelWidthMeters:positive,wastePercent:waste}),x=>ceilUnits(x.fenceLengthMeters/x.panelWidthMeters*(1+x.wastePercent/100)),"panels=ceil(length/panel width×(1+w/100))","Whole fence panels required including waste allowance.",{fenceLengthMeters:30,panelWidthMeters:2,wastePercent:10},17);
export const deckingCalculator=mk("engineering.decking","decking-calculator","Decking Calculator",z.object({deckAreaSquareMeters:positive,boardWidthMeters:positive,boardLengthMeters:positive,wastePercent:waste}),x=>ceilUnits(x.deckAreaSquareMeters/(x.boardWidthMeters*x.boardLengthMeters)*(1+x.wastePercent/100)),"boards=ceil(area/(board width×board length)×(1+w/100))","Whole decking boards required from deck area and board face area.",{deckAreaSquareMeters:20,boardWidthMeters:.14,boardLengthMeters:4,wastePercent:10},40);
export const gravelCalculator=mk("engineering.gravel","gravel-calculator","Gravel Calculator",z.object({lengthMeters:positive,widthMeters:positive,depthMeters:positive,wastePercent:waste}),x=>x.lengthMeters*x.widthMeters*x.depthMeters*(1+x.wastePercent/100),"V=L×W×D×(1+w/100)","Gravel volume in cubic metres including waste allowance.",{lengthMeters:10,widthMeters:5,depthMeters:.1,wastePercent:10},5.5);
export const asphaltCalculator=mk("engineering.asphalt","asphalt-calculator","Asphalt Calculator",z.object({lengthMeters:positive,widthMeters:positive,depthMeters:positive,densityKgPerCubicMeter:positive,wastePercent:waste}),x=>x.lengthMeters*x.widthMeters*x.depthMeters*x.densityKgPerCubicMeter*(1+x.wastePercent/100),"mass=L×W×D×density×(1+w/100)","Estimated asphalt mass in kilograms using user-supplied compacted density.",{lengthMeters:10,widthMeters:5,depthMeters:.05,densityKgPerCubicMeter:2400,wastePercent:5},6300);
export const excavationCalculator=mk("engineering.excavation","excavation-calculator","Excavation Calculator",z.object({lengthMeters:positive,widthMeters:positive,depthMeters:positive,bulkingPercent:nonnegative}),x=>x.lengthMeters*x.widthMeters*x.depthMeters*(1+x.bulkingPercent/100),"loose volume=L×W×D×(1+bulking/100)","Loose excavated volume in cubic metres from in-situ dimensions and a user-supplied bulking allowance.",{lengthMeters:10,widthMeters:4,depthMeters:2,bulkingPercent:20},96);
export const wallpaperCalculator=mk("engineering.wallpaper","wallpaper-calculator","Wallpaper Calculator",z.object({wallAreaSquareMeters:positive,rollCoverageSquareMeters:positive,wastePercent:waste}),x=>ceilUnits(x.wallAreaSquareMeters/x.rollCoverageSquareMeters*(1+x.wastePercent/100)),"rolls=ceil(area/roll coverage×(1+w/100))","Whole wallpaper rolls required using stated usable roll coverage and waste allowance.",{wallAreaSquareMeters:40,rollCoverageSquareMeters:5,wastePercent:10},9);
export const insulationCalculator=mk("engineering.insulation","insulation-calculator","Insulation Calculator",z.object({areaSquareMeters:positive,packCoverageSquareMeters:positive,wastePercent:waste}),x=>ceilUnits(x.areaSquareMeters/x.packCoverageSquareMeters*(1+x.wastePercent/100)),"packs=ceil(area/pack coverage×(1+w/100))","Whole insulation packs required using stated pack coverage and waste allowance.",{areaSquareMeters:100,packCoverageSquareMeters:10,wastePercent:10},11);
export const engineeringConstructionBatch2Definitions=[stairCalculator,fenceCalculator,deckingCalculator,gravelCalculator,asphaltCalculator,excavationCalculator,wallpaperCalculator,insulationCalculator] as const;
