import { z } from "zod";
import { roundTo } from "../precision";
import type { CalculatorDefinition } from "../types";

const debtSchema=z.object({name:z.string().trim().min(1).max(80),balance:z.number().finite().positive(),annualRatePercent:z.number().finite().min(0).max(1000),minimumPayment:z.number().finite().min(0)});
const inputSchema=z.object({debts:z.array(debtSchema).min(1).max(50),extraMonthlyPayment:z.number().finite().min(0).default(0),strategy:z.enum(["avalanche","snowball"]).default("avalanche")});
type Input=z.infer<typeof inputSchema>;
type Output={strategy:"avalanche"|"snowball";monthsToPayoff:number;totalInterest:number;totalPaid:number;startingBalance:number;payoffOrder:string[]};
function finite(v:number,label:string){if(!Number.isFinite(v))throw new Error(`${label} exceeds supported numeric range`);return v;}
export function simulateDebtPayoff(input:Input):Output{const debts=input.debts.map((d,i)=>({...d,index:i,balance:d.balance}));const startingBalance=finite(debts.reduce((s,d)=>s+d.balance,0),"Starting balance");let totalInterest=0,totalPaid=0,months=0;const payoffOrder:string[]=[];while(debts.some(d=>d.balance>0.005)&&months<1200){months++;for(const d of debts){if(d.balance<=0.005)continue;const interest=finite(d.balance*(d.annualRatePercent/100/12),"Debt interest");d.balance=finite(d.balance+interest,"Debt balance");totalInterest=finite(totalInterest+interest,"Total interest");}
let pool=input.extraMonthlyPayment;for(const d of debts){if(d.balance<=0.005)continue;const pay=Math.min(d.minimumPayment,d.balance);d.balance-=pay;pool+=Math.max(0,d.minimumPayment-pay);totalPaid=finite(totalPaid+pay,"Total paid");if(d.balance<=0.005&&!payoffOrder.includes(d.name))payoffOrder.push(d.name);}
const active=debts.filter(d=>d.balance>0.005).sort((a,b)=>input.strategy==="avalanche"?(b.annualRatePercent-a.annualRatePercent||a.balance-b.balance||a.index-b.index):(a.balance-b.balance||b.annualRatePercent-a.annualRatePercent||a.index-b.index));if(active.length&&pool>0){const target=active[0];const pay=Math.min(pool,target.balance);target.balance-=pay;totalPaid=finite(totalPaid+pay,"Total paid");if(target.balance<=0.005&&!payoffOrder.includes(target.name))payoffOrder.push(target.name);}
const activeAfter=debts.filter(d=>d.balance>0.005);if(activeAfter.length&&activeAfter.every(d=>d.minimumPayment<=d.balance*(d.annualRatePercent/100/12)+0.000001)&&input.extraMonthlyPayment===0)throw new Error("Minimum payments do not reduce the modeled debt balances");}
if(debts.every(d=>d.balance<=0.005))break;}
if(debts.some(d=>d.balance>0.005))throw new Error("Debt payoff exceeds supported 1200-month horizon");return{strategy:input.strategy,monthsToPayoff:months,totalInterest:roundTo(totalInterest,2),totalPaid:roundTo(totalPaid,2),startingBalance:roundTo(startingBalance,2),payoffOrder};}
export const debtPayoffCalculator:CalculatorDefinition<Input,Output>={id:"finance.debt-payoff",slug:"debt-payoff-calculator",title:"Debt Snowball & Avalanche Calculator",category:"loans-mortgages",version:1,riskClass:"financial",reviewStatus:"draft",inputSchema,calculate:(input)=>simulateDebtPayoff(input),formulas:[{id:"monthly-interest",expression:"interest = balance × annual rate / 12",description:"Applies modeled monthly interest to each outstanding balance."},{id:"payoff-priority",expression:"avalanche: highest rate first; snowball: lowest balance first",description:"Minimum payments are applied first, then available extra payment is directed to the selected priority debt."}],sources:[],examples:[],jurisdictions:[{country:"GLOBAL"}],relatedCalculators:["loan-emi-calculator","loan-affordability-calculator","loan-prepayment-calculator"],journeyMemberships:["get-out-of-debt"]};
