import { z } from "zod";
import { roundTo } from "../precision";
import type { CalculatorDefinition } from "../types";
const inputSchema=z.object({amount:z.number().finite().min(0),annualInflationPercent:z.number().finite().gt(-100).max(1000),years:z.number().finite().min(0).max(200)});
type Input=z.infer<typeof inputSchema>;
type Output={futureEquivalentCost:number;futurePurchasingPower:number;cumulativeInflationPercent:number;purchasingPowerLossPercent:number};
function finite(value:number,label:string){if(!Number.isFinite(value))throw new Error(`${label} exceeds supported numeric range`);return value;}
export function calculateInflation(input:Input):Output{const factor=finite(Math.pow(1+input.annualInflationPercent/100,input.years),"Inflation factor");const futureCost=finite(input.amount*factor,"Future equivalent cost");const purchasingPower=finite(input.amount/factor,"Future purchasing power");const cumulative=(factor-1)*100;const loss=(1-1/factor)*100;return{futureEquivalentCost:roundTo(futureCost,2),futurePurchasingPower:roundTo(purchasingPower,2),cumulativeInflationPercent:roundTo(cumulative,6),purchasingPowerLossPercent:roundTo(loss,6)};}
export const inflationCalculator:CalculatorDefinition<Input,Output>={id:"finance.inflation",slug:"inflation-calculator",title:"Inflation & Purchasing Power Calculator",category:"finance",version:1,riskClass:"financial",reviewStatus:"draft",inputSchema,calculate:(input)=>calculateInflation(input),formulas:[{id:"future-cost",expression:"future equivalent=amount×(1+inflation)^years",description:"Projects the nominal amount needed to match today's modeled purchasing power."},{id:"purchasing-power",expression:"future purchasing power=amount/(1+inflation)^years",description:"Estimates the purchasing power of an unchanged nominal amount after the modeled period."}],sources:[],examples:[],jurisdictions:[{country:"GLOBAL"}],ui:{simpleInputKeys:["amount","annualInflationPercent","years"]},relatedCalculators:["investment-growth-calculator","savings-goal-calculator","roi-calculator"],journeyMemberships:["invest-for-a-goal","plan-retirement"]};
