import { describe, expect, it } from "vitest";
import { calculateLoanAffordability, loanAffordabilityCalculator } from "./loan-affordability";

describe("DTI and loan affordability",()=>{
  it("derives debt capacity and reverse-solves principal",()=>{const r=calculateLoanAffordability({grossMonthlyIncome:10000,existingMonthlyDebt:1000,targetDtiPercent:40,annualRatePercent:6,termMonths:360,downPayment:50000});expect(r.currentDtiPercent).toBe(10);expect(r.maximumTotalMonthlyDebt).toBe(4000);expect(r.availableMonthlyLoanPayment).toBe(3000);expect(r.maximumLoanPrincipal).toBeGreaterThan(0);expect(r.maximumPurchasePrice-r.maximumLoanPrincipal).toBeCloseTo(50000,2);expect(r.modeledPaymentAtMaximumPrincipal).toBeCloseTo(3000,2);});
  it("returns zero new borrowing capacity when existing debt already reaches the target DTI",()=>{const r=calculateLoanAffordability({grossMonthlyIncome:5000,existingMonthlyDebt:2500,targetDtiPercent:40,annualRatePercent:7,termMonths:240,downPayment:10000});expect(r.availableMonthlyLoanPayment).toBe(0);expect(r.maximumLoanPrincipal).toBe(0);expect(r.maximumPurchasePrice).toBe(10000);});
  it("handles zero-rate reverse affordability",()=>{const r=calculateLoanAffordability({grossMonthlyIncome:6000,existingMonthlyDebt:0,targetDtiPercent:25,annualRatePercent:0,termMonths:120,downPayment:0});expect(r.availableMonthlyLoanPayment).toBe(1500);expect(r.maximumLoanPrincipal).toBe(180000);expect(r.modeledPaymentAtMaximumPrincipal).toBe(1500);});
  it("does not treat the modeled DTI threshold as lender approval",()=>{const r=loanAffordabilityCalculator.calculate({grossMonthlyIncome:8000,existingMonthlyDebt:800,targetDtiPercent:35,annualRatePercent:5.5,termMonths:300,downPayment:20000},{});expect(Number.isFinite(r.maximumLoanPrincipal)).toBe(true);expect(r.currentDtiPercent).toBe(10);});
  it("rejects unsafe direct affordability inputs",()=>{expect(()=>calculateLoanAffordability({grossMonthlyIncome:0,existingMonthlyDebt:0,targetDtiPercent:40,annualRatePercent:6,termMonths:360,downPayment:0})).toThrow();expect(()=>calculateLoanAffordability({grossMonthlyIncome:5000,existingMonthlyDebt:-1,targetDtiPercent:40,annualRatePercent:6,termMonths:360,downPayment:0})).toThrow();expect(()=>calculateLoanAffordability({grossMonthlyIncome:5000,existingMonthlyDebt:0,targetDtiPercent:101,annualRatePercent:6,termMonths:360,downPayment:0})).toThrow();expect(()=>calculateLoanAffordability({grossMonthlyIncome:5000,existingMonthlyDebt:0,targetDtiPercent:40,annualRatePercent:6,termMonths:12.5,downPayment:0})).toThrow();});
  it("rejects purchase-price aggregate overflow",()=>{expect(()=>calculateLoanAffordability({grossMonthlyIncome:Number.MAX_VALUE,existingMonthlyDebt:0,targetDtiPercent:100,annualRatePercent:0,termMonths:1200,downPayment:Number.MAX_VALUE})).toThrow(/numeric range/);});
});
