import { describe, expect, it } from "vitest";
import { compareLoanRefinance, loanRefinanceCalculator } from "./loan-refinance";

describe("loan refinance engine",()=>{
  it("shows savings for a lower-rate same-term refinance with no costs",()=>{const r=compareLoanRefinance({remainingBalance:250000,currentAnnualRatePercent:7,currentRemainingMonths:240,newAnnualRatePercent:5.5,newTermMonths:240,refinanceCosts:0});expect(r.newMonthlyPayment).toBeLessThan(r.currentMonthlyPayment);expect(r.grossInterestSavings).toBeGreaterThan(0);expect(r.netLifetimeSavings).toBe(r.grossInterestSavings);expect(r.breakEvenMonths).toBe(0);});
  it("can identify costs that erase lifetime savings",()=>{const r=compareLoanRefinance({remainingBalance:250000,currentAnnualRatePercent:7,currentRemainingMonths:240,newAnnualRatePercent:6.75,newTermMonths:240,refinanceCosts:50000});expect(r.netLifetimeSavings).toBeLessThan(0);});
  it("reports no payment-based break-even when replacement payment is not lower",()=>{const r=compareLoanRefinance({remainingBalance:200000,currentAnnualRatePercent:5,currentRemainingMonths:240,newAnnualRatePercent:5,newTermMonths:180,refinanceCosts:3000});expect(r.newMonthlyPayment).toBeGreaterThan(r.currentMonthlyPayment);expect(r.breakEvenMonths).toBeNull();});
  it("does not invent an immediate break-even for zero costs without payment savings",()=>{const r=compareLoanRefinance({remainingBalance:100000,currentAnnualRatePercent:6,currentRemainingMonths:120,newAnnualRatePercent:6,newTermMonths:120,refinanceCosts:0});expect(r.currentMonthlyPayment).toBe(r.newMonthlyPayment);expect(r.breakEvenMonths).toBeNull();});
  it("keeps same-rate same-term economics equal before refinance costs",()=>{const r=compareLoanRefinance({remainingBalance:100000,currentAnnualRatePercent:6,currentRemainingMonths:120,newAnnualRatePercent:6,newTermMonths:120,refinanceCosts:2500});expect(r.currentMonthlyPayment).toBe(r.newMonthlyPayment);expect(r.grossInterestSavings).toBeCloseTo(0,2);expect(r.netLifetimeSavings).toBeCloseTo(-2500,2);expect(r.breakEvenMonths).toBeNull();});
  it("exposes a structured calculator result",()=>{const r=loanRefinanceCalculator.calculate({remainingBalance:300000,currentAnnualRatePercent:7.25,currentRemainingMonths:300,newAnnualRatePercent:6,newTermMonths:240,refinanceCosts:4000},{});expect(Number.isFinite(r.currentRemainingInterest)).toBe(true);expect(Number.isFinite(r.newLoanInterest)).toBe(true);expect(r.refinanceCosts).toBe(4000);});
  it("rejects unsafe direct refinance inputs",()=>{expect(()=>compareLoanRefinance({remainingBalance:Number.NaN,currentAnnualRatePercent:7,currentRemainingMonths:120,newAnnualRatePercent:6,newTermMonths:120,refinanceCosts:0})).toThrow();expect(()=>compareLoanRefinance({remainingBalance:100000,currentAnnualRatePercent:-1,currentRemainingMonths:120,newAnnualRatePercent:6,newTermMonths:120,refinanceCosts:0})).toThrow();expect(()=>compareLoanRefinance({remainingBalance:100000,currentAnnualRatePercent:7,currentRemainingMonths:120.5,newAnnualRatePercent:6,newTermMonths:120,refinanceCosts:0})).toThrow();expect(()=>compareLoanRefinance({remainingBalance:100000,currentAnnualRatePercent:7,currentRemainingMonths:120,newAnnualRatePercent:6,newTermMonths:120,refinanceCosts:-1})).toThrow();});
});
