import { z } from "zod";
import { roundTo } from "../precision";
import type { CalculatorDefinition } from "../types";
import { maxPrincipalForPayment, paymentForLoan } from "./loan-analysis";

const inputSchema=z.object({grossMonthlyIncome:z.number().finite().positive(),existingMonthlyDebt:z.number().finite().min(0).default(0),targetDtiPercent:z.number().finite().positive().max(100),annualRatePercent:z.number().finite().min(0).max(1000),termMonths:z.number().int().min(1).max(1200),downPayment:z.number().finite().min(0).default(0)});
type Input=z.infer<typeof inputSchema>;
type Output={currentDtiPercent:number;maximumTotalMonthlyDebt:number;availableMonthlyLoanPayment:number;maximumLoanPrincipal:number;maximumPurchasePrice:number;modeledPaymentAtMaximumPrincipal:number};
function finite(v:number,label:string){if(!Number.isFinite(v))throw new Error(`${label} exceeds supported numeric range`);return v;}
export function calculateLoanAffordability(input:Input):Output{const currentDti=finite(input.existingMonthlyDebt/input.grossMonthlyIncome*100,"Current DTI");const maxDebt=finite(input.grossMonthlyIncome*input.targetDtiPercent/100,"Maximum monthly debt");const available=Math.max(0,finite(maxDebt-input.existingMonthlyDebt,"Available monthly loan payment"));const principal=available===0?0:finite(maxPrincipalForPayment(available,input.annualRatePercent,input.termMonths),"Maximum loan principal");const payment=principal===0?0:finite(paymentForLoan(principal,input.annualRatePercent,input.termMonths),"Modeled payment");return{currentDtiPercent:roundTo(currentDti,2),maximumTotalMonthlyDebt:roundTo(maxDebt,2),availableMonthlyLoanPayment:roundTo(available,2),maximumLoanPrincipal:roundTo(principal,2),maximumPurchasePrice:roundTo(principal+input.downPayment,2),modeledPaymentAtMaximumPrincipal:roundTo(payment,2)};}
export const loanAffordabilityCalculator:CalculatorDefinition<Input,Output>={id:"finance.loan-affordability",slug:"loan-affordability-calculator",title:"DTI & Loan Affordability Calculator",category:"loans-mortgages",version:1,riskClass:"financial",reviewStatus:"draft",inputSchema,calculate:(input)=>calculateLoanAffordability(input),formulas:[{id:"dti",expression:"DTI = monthly debt / gross monthly income",description:"Measures modeled monthly debt obligations relative to gross monthly income."},{id:"available-payment",expression:"available payment = income × target DTI − existing monthly debt",description:"Derives the monthly payment capacity under the user-selected DTI assumption."},{id:"reverse-loan",expression:"P = M × (1 − (1+r)^(-n)) / r",description:"Reverse-solves the maximum modeled principal supported by the available payment, rate and term."}],sources:[],examples:[],jurisdictions:[{country:"GLOBAL"}],ui:{simpleInputKeys:["grossMonthlyIncome","targetDtiPercent","annualRatePercent","termMonths"],advancedInputKeys:["existingMonthlyDebt","downPayment"]},reverseSolvers:[{id:"maximum-loan-from-dti",target:"maximumLoanPrincipal",description:"Solves the maximum modeled loan principal from gross income, existing monthly debt, a user-selected DTI threshold, rate and term."}],relatedCalculators:["loan-emi-calculator","loan-comparison-calculator","loan-refinance-calculator"],journeyMemberships:["buy-a-home","get-out-of-debt"]};
