import { z } from "zod";
import { roundTo } from "../precision";
import type { CalculatorDefinition } from "../types";
import { paymentForLoan } from "./loan-analysis";

const inputSchema=z.object({principal:z.number().finite().positive(),annualRatePercent:z.number().finite().min(0).max(1000),originalTermMonths:z.number().int().min(1).max(1200),paymentsMade:z.number().int().min(0).max(1199),lumpSumPrepayment:z.number().finite().min(0).default(0),prepaymentFee:z.number().finite().min(0).default(0)}).refine(v=>v.paymentsMade<v.originalTermMonths,{message:"paymentsMade must be less than originalTermMonths",path:["paymentsMade"]});
type Input=z.infer<typeof inputSchema>;
type Output={scheduledPayment:number;remainingBalanceBeforePrepayment:number;prepaymentApplied:number;remainingBalanceAfterPrepayment:number;remainingMonthsWithoutPrepayment:number;remainingMonthsAfterPrepayment:number;monthsSaved:number;remainingInterestWithoutPrepayment:number;remainingInterestAfterPrepayment:number;grossInterestSaved:number;prepaymentFee:number;netSavingsAfterFee:number;foreclosureAmount:number};
function finite(v:number,label:string){if(!Number.isFinite(v))throw new Error(`${label} exceeds supported numeric range`);return v;}
export function remainingLoanBalance(principal:number,annualRatePercent:number,termMonths:number,paymentsMade:number):number{if(paymentsMade<=0)return principal;if(paymentsMade>=termMonths)return 0;const r=annualRatePercent/100/12;const p=paymentForLoan(principal,annualRatePercent,termMonths);return finite(r===0?principal-p*paymentsMade:principal*(1+r)**paymentsMade-p*((1+r)**paymentsMade-1)/r,"Remaining balance");}
function payoff(balance:number,ratePercent:number,payment:number){const r=ratePercent/100/12;let b=balance,totalInterest=0,months=0;while(b>0.005&&months<1200){const interest=finite(b*r,"Interest");const paid=Math.min(payment,b+interest);b=Math.max(0,b-(paid-interest));totalInterest=finite(totalInterest+interest,"Interest total");months+=1;}return{months,interest:totalInterest};}
export function analyzeLoanPrepayment(input:Input):Output{const scheduled=finite(paymentForLoan(input.principal,input.annualRatePercent,input.originalTermMonths),"Scheduled payment");const before=Math.max(0,finite(remainingLoanBalance(input.principal,input.annualRatePercent,input.originalTermMonths,input.paymentsMade),"Remaining balance"));const applied=Math.min(input.lumpSumPrepayment,before);const feeApplied=applied>0?input.prepaymentFee:0;const after=Math.max(0,before-applied);const base=payoff(before,input.annualRatePercent,scheduled);const revised=after===0?{months:0,interest:0}:payoff(after,input.annualRatePercent,scheduled);const gross=finite(base.interest-revised.interest,"Gross interest saved");return{scheduledPayment:roundTo(scheduled,2),remainingBalanceBeforePrepayment:roundTo(before,2),prepaymentApplied:roundTo(applied,2),remainingBalanceAfterPrepayment:roundTo(after,2),remainingMonthsWithoutPrepayment:base.months,remainingMonthsAfterPrepayment:revised.months,monthsSaved:Math.max(0,base.months-revised.months),remainingInterestWithoutPrepayment:roundTo(base.interest,2),remainingInterestAfterPrepayment:roundTo(revised.interest,2),grossInterestSaved:roundTo(gross,2),prepaymentFee:roundTo(feeApplied,2),netSavingsAfterFee:roundTo(gross-feeApplied,2),foreclosureAmount:roundTo(before+feeApplied,2)};}
export const loanPrepaymentCalculator:CalculatorDefinition<Input,Output>={id:"finance.loan-prepayment",slug:"loan-prepayment-calculator",title:"Loan Prepayment & Foreclosure Calculator",category:"loans-mortgages",version:1,riskClass:"financial",reviewStatus:"draft",inputSchema,calculate:(input)=>analyzeLoanPrepayment(input),formulas:[{id:"remaining-balance",expression:"B_k = P(1+r)^k − M((1+r)^k−1)/r",description:"Outstanding balance after k scheduled payments for a fixed-rate fully amortizing loan; zero-rate loans use linear principal reduction."},{id:"prepayment-savings",expression:"net savings = remaining interest avoided − applicable prepayment fee",description:"Generic comparison when the scheduled payment is maintained after a positive lump-sum prepayment. The explicit fee is applied only when a prepayment is actually modeled."}],sources:[],examples:[],jurisdictions:[{country:"GLOBAL"}],ui:{simpleInputKeys:["principal","annualRatePercent","originalTermMonths","paymentsMade","lumpSumPrepayment"],advancedInputKeys:["prepaymentFee"]},relatedCalculators:["loan-emi-calculator","loan-refinance-calculator","loan-comparison-calculator","loan-affordability-calculator"],journeyMemberships:["buy-a-home","get-out-of-debt"]};
