import { describe, expect, it } from "vitest";
import { compareLoans, loanComparisonCalculator } from "./loan-comparison";

describe("loan comparison engine",()=>{
  it("identifies the lower payment and lower total cost for otherwise equal loans",()=>{const result=compareLoans({loanA:{principal:250000,annualRatePercent:5,termMonths:360,upfrontCosts:0},loanB:{principal:250000,annualRatePercent:6,termMonths:360,upfrontCosts:0}});expect(result.lowerMonthlyPayment).toBe("A");expect(result.lowerTotalCost).toBe("A");expect(result.loanA.totalInterest).toBeLessThan(result.loanB.totalInterest);});
  it("distinguishes lower monthly payment from lower lifetime cost",()=>{const result=compareLoans({loanA:{principal:200000,annualRatePercent:5,termMonths:360,upfrontCosts:0},loanB:{principal:200000,annualRatePercent:5,termMonths:180,upfrontCosts:0}});expect(result.lowerMonthlyPayment).toBe("A");expect(result.lowerTotalCost).toBe("B");});
  it("includes explicit upfront costs in total modeled cost",()=>{const result=compareLoans({loanA:{principal:100000,annualRatePercent:5,termMonths:120,upfrontCosts:10000},loanB:{principal:100000,annualRatePercent:5,termMonths:120,upfrontCosts:0}});expect(result.loanA.monthlyPayment).toBe(result.loanB.monthlyPayment);expect(result.loanA.totalCost-result.loanB.totalCost).toBeCloseTo(10000,2);expect(result.lowerMonthlyPayment).toBe("equal");expect(result.lowerTotalCost).toBe("B");});
  it("handles zero-rate loans",()=>{const result=compareLoans({loanA:{principal:12000,annualRatePercent:0,termMonths:12,upfrontCosts:0},loanB:{principal:12000,annualRatePercent:0,termMonths:24,upfrontCosts:0}});expect(result.loanA.monthlyPayment).toBe(1000);expect(result.loanA.totalInterest).toBe(0);expect(result.loanB.monthlyPayment).toBe(500);expect(result.lowerTotalCost).toBe("equal");});
  it("returns structured calculator output",()=>{const result=loanComparisonCalculator.calculate({loanA:{principal:150000,annualRatePercent:6,termMonths:180,upfrontCosts:1000},loanB:{principal:150000,annualRatePercent:6.5,termMonths:180,upfrontCosts:0}},{});expect(Number.isFinite(result.loanA.totalCost)).toBe(true);expect(["A","B","equal"]).toContain(result.lowerTotalCost);});
  it("rejects unsafe direct comparison inputs",()=>{expect(()=>compareLoans({loanA:{principal:Number.NaN,annualRatePercent:5,termMonths:12,upfrontCosts:0},loanB:{principal:1000,annualRatePercent:5,termMonths:12,upfrontCosts:0}})).toThrow();expect(()=>compareLoans({loanA:{principal:1000,annualRatePercent:-1,termMonths:12,upfrontCosts:0},loanB:{principal:1000,annualRatePercent:5,termMonths:12,upfrontCosts:0}})).toThrow();expect(()=>compareLoans({loanA:{principal:1000,annualRatePercent:5,termMonths:12.5,upfrontCosts:0},loanB:{principal:1000,annualRatePercent:5,termMonths:12,upfrontCosts:0}})).toThrow();});
  it("keeps comparison differences finite for supported extreme loans",()=>{const r=compareLoans({loanA:{principal:1e300,annualRatePercent:0,termMonths:1200,upfrontCosts:0},loanB:{principal:1e300,annualRatePercent:0,termMonths:1200,upfrontCosts:1e290}});expect(Number.isFinite(r.monthlyPaymentDifference)).toBe(true);expect(Number.isFinite(r.totalCostDifference)).toBe(true);});
});
