import { z } from "zod";
import { roundTo } from "../precision";
import type { CalculatorDefinition } from "../types";
const inputSchema=z.object({initialInvestment:z.number().finite().positive(),finalValue:z.number().finite().min(0),additionalCosts:z.number().finite().min(0).default(0),incomeReceived:z.number().finite().min(0).default(0),holdingMonths:z.number().int().min(1).max(12000)});
type Input=z.infer<typeof inputSchema>;
type Output={netGain:number;totalInvested:number;roiPercent:number;annualizedReturnPercent:number|null};
function finite(v:number,label:string){if(!Number.isFinite(v))throw new Error(`${label} exceeds supported numeric range`);return v;}
export function calculateRoi(input:Input):Output{const invested=finite(input.initialInvestment+input.additionalCosts,"Total invested");const ending=finite(input.finalValue+input.incomeReceived,"Ending value");const gain=finite(ending-invested,"Net gain");const roi=gain/invested*100;const ratio=ending/invested;let annualized:number|null=null;if(ratio>0){annualized=finite((Math.pow(ratio,12/input.holdingMonths)-1)*100,"Annualized return");}return{netGain:roundTo(gain,2),totalInvested:roundTo(invested,2),roiPercent:roundTo(roi,6),annualizedReturnPercent:annualized===null?null:roundTo(annualized,6)};}
export const roiCalculator:CalculatorDefinition<Input,Output>={id:"finance.roi",slug:"roi-calculator",title:"ROI Calculator",category:"finance-investment",version:1,riskClass:"financial",reviewStatus:"draft",inputSchema,calculate:(input)=>calculateRoi(input),formulas:[{id:"roi",expression:"ROI=(ending value + income − initial investment − costs)/(initial investment + costs)",description:"Measures total modeled gain relative to total invested capital."},{id:"annualized",expression:"annualized=(ending/invested)^(12/months)−1",description:"Geometrically annualizes the total holding-period return when ending value is positive."}],sources:[],examples:[],jurisdictions:[{country:"GLOBAL"}],ui:{simpleInputKeys:["initialInvestment","finalValue","holdingMonths"],advancedInputKeys:["additionalCosts","incomeReceived"]},relatedCalculators:["investment-growth-calculator","savings-goal-calculator","effective-interest-rate-calculator"],journeyMemberships:["invest-for-a-goal","start-a-business"]};
