import { z } from "zod";
import { roundTo } from "../precision";
import type { CalculatorDefinition } from "../types";

const inputSchema=z.object({currentSavings:z.number().finite().min(0),targetAmount:z.number().finite().positive(),annualReturnPercent:z.number().finite().min(-99.999).max(1000),months:z.number().int().min(1).max(1200),monthlyContribution:z.number().finite().min(0).optional()});
type Input=z.infer<typeof inputSchema>;
type Output={futureValue:number;gapToTarget:number;requiredMonthlyContribution:number;monthlyContributionUsed:number;targetReached:boolean};
function finite(v:number,label:string){if(!Number.isFinite(v))throw new Error(`${label} exceeds supported numeric range`);return v;}
function growth(rate:number,months:number){return finite(Math.pow(1+rate,months),"Growth factor");}
export function savingsFutureValue(current:number,monthly:number,annualPercent:number,months:number){const r=annualPercent/100/12;if(r<=-1)throw new Error("Monthly return must be greater than -100%");const g=growth(r,months);const annuity=r===0?months:(g-1)/r;return finite(current*g+monthly*annuity,"Savings future value");}
export function requiredMonthlySavings(current:number,target:number,annualPercent:number,months:number){const r=annualPercent/100/12;if(r<=-1)throw new Error("Monthly return must be greater than -100%");const g=growth(r,months);const needed=target-current*g;if(needed<=0)return 0;const factor=r===0?months:(g-1)/r;if(factor<=0||!Number.isFinite(factor))throw new Error("Target cannot be solved within supported assumptions");return finite(needed/factor,"Required monthly contribution");}
export function calculateSavingsGoal(input:Input):Output{const required=requiredMonthlySavings(input.currentSavings,input.targetAmount,input.annualReturnPercent,input.months);const used=input.monthlyContribution??required;const fv=savingsFutureValue(input.currentSavings,used,input.annualReturnPercent,input.months);return{futureValue:roundTo(fv,2),gapToTarget:roundTo(Math.max(0,input.targetAmount-fv),2),requiredMonthlyContribution:roundTo(required,2),monthlyContributionUsed:roundTo(used,2),targetReached:fv+0.005>=input.targetAmount};}
export const savingsGoalCalculator:CalculatorDefinition<Input,Output>={id:"finance.savings-goal",slug:"savings-goal-calculator",title:"Savings Goal Calculator",category:"finance",version:1,riskClass:"financial",reviewStatus:"draft",inputSchema,calculate:(input)=>calculateSavingsGoal(input),formulas:[{id:"future-value",expression:"FV=current×(1+r)^n + contribution×((1+r)^n−1)/r",description:"Projects current savings and level end-of-month contributions using a constant modeled monthly return."},{id:"required-contribution",expression:"contribution=(target−current×(1+r)^n)/annuityFactor",description:"Reverse-solves the level monthly contribution required for a target amount."}],sources:[],examples:[],jurisdictions:[{country:"GLOBAL"}],ui:{simpleInputKeys:["currentSavings","targetAmount","annualReturnPercent","months"],advancedInputKeys:["monthlyContribution"]},relatedCalculators:["sip-calculator","investment-growth-calculator","recurring-deposit-calculator"],journeyMemberships:["invest-for-a-goal"]};
